### PR TITLE
Fix composer width and autocomplete

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/1106.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@Kugeleis, @g6094199, @nickdbush, @mjanssens, @g6094199 and @menaceone please test this patch with the following tarball: [mail.tar.gz](https://github.com/nextcloud/mail/files/2477909/mail.tar.gz)

**Comment by ChristophWurst** [comment]
> When I click "start update" it's not working.
> Do I have to enable some kind of developer mode or something?

Is there anything added to your `data/nextcloud.log` when you click the button?

**Comment by menaceone** [comment]
yep, that should be the corresponding section:

```
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::setDebugLogLevel: Set log level to debug","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":0,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"starting upgrade from 14.0.1.1 to 14.0.1.1","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":3,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"PHP","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"file_put_contents(\/data\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/Setup.php#534","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Repair::info: Repair info: All tables already have the correct collation -> nothing to do","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::appUpgradeStarted: Updating <mail> ...","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Repair::step: Repair step: Purify and migrate collected mail addresses","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":3,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":{"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT COUNT(*) FROM `oc_mail_coll_addresses`':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_mail_coll_addresses' doesn't exist","Code":0,"Trace":[{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":128,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'SELECT COUNT(*) FROM `oc_mail_coll_addresses`':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_mail_coll_addresses' doesn't exist",{"errorInfo":["42S02",1146,"Table 'owncloud.oc_mail_coll_addresses' doesn't exist"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":855,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["42S02",1146,"Table 'owncloud.oc_mail_coll_addresses' doesn't exist"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[]]},{"file":"\/var\/www\/owncloud\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[],[],null]},{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[],[]]},{"file":"\/var\/www\/owncloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/apps\/mail\/lib\/Db\/CollectedAddressMapper.php","line":76,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/apps\/mail\/lib\/Migration\/FixCollectedAddresses.php","line":47,"function":"getTotal","class":"OCA\\Mail\\Db\\CollectedAddressMapper","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/Repair.php","line":89,"function":"run","class":"OCA\\Mail\\Migration\\FixCollectedAddresses","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/var\/www\/owncloud\/lib\/private\/legacy\/app.php","line":966,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/legacy\/app.php","line":903,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["mail",{"step":"OCA\\Mail\\Migration\\FixCollectedAddresses"}]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":370,"function":"updateApp","class":"OC_App","type":"::","args":["mail"]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":250,"function":"doAppUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":126,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["14.0.1.1","14.0.1.1"]},{"file":"\/var\/www\/owncloud\/core\/ajax\/update.php","line":214,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":53,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_mail_coll_addresses' doesn't exist","Code":"42S02","Trace":[{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":852,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`"]},{"file":"\/var\/www\/owncloud\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[],[],null]},{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[],[]]},{"file":"\/var\/www\/owncloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/apps\/mail\/lib\/Db\/CollectedAddressMapper.php","line":76,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/apps\/mail\/lib\/Migration\/FixCollectedAddresses.php","line":47,"function":"getTotal","class":"OCA\\Mail\\Db\\CollectedAddressMapper","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/Repair.php","line":89,"function":"run","class":"OCA\\Mail\\Migration\\FixCollectedAddresses","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/var\/www\/owncloud\/lib\/private\/legacy\/app.php","line":966,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/legacy\/app.php","line":903,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["mail",{"step":"OCA\\Mail\\Migration\\FixCollectedAddresses"}]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":370,"function":"updateApp","class":"OC_App","type":"::","args":["mail"]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":250,"function":"doAppUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":126,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["14.0.1.1","14.0.1.1"]},{"file":"\/var\/www\/owncloud\/core\/ajax\/update.php","line":214,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php","Line":106,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_mail_coll_addresses' doesn't exist","Code":"42S02","Trace":[{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php","line":104,"function":"query","class":"PDO","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`"]},{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":852,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`"]},{"file":"\/var\/www\/owncloud\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[],[],null]},{"file":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT COUNT(*) FROM `oc_mail_coll_addresses`",[],[]]},{"file":"\/var\/www\/owncloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/apps\/mail\/lib\/Db\/CollectedAddressMapper.php","line":76,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/apps\/mail\/lib\/Migration\/FixCollectedAddresses.php","line":47,"function":"getTotal","class":"OCA\\Mail\\Db\\CollectedAddressMapper","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/Repair.php","line":89,"function":"run","class":"OCA\\Mail\\Migration\\FixCollectedAddresses","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/var\/www\/owncloud\/lib\/private\/legacy\/app.php","line":966,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/legacy\/app.php","line":903,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["mail",{"step":"OCA\\Mail\\Migration\\FixCollectedAddresses"}]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":370,"function":"updateApp","class":"OC_App","type":"::","args":["mail"]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":250,"function":"doAppUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"\/var\/www\/owncloud\/lib\/private\/Updater.php","line":126,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["14.0.1.1","14.0.1.1"]},{"file":"\/var\/www\/owncloud\/core\/ajax\/update.php","line":214,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php","Line":104}},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":3,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\TableNotFoundException: An exception occurred while executing 'SELECT COUNT(*) FROM `oc_mail_coll_addresses`':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_mail_coll_addresses' doesn't exist","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":3,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"PfEs06W0PZ9M4sPfsU4k","level":1,"time":"2018-10-15T15:08:01+02:00","remoteAddr":"185.225.140.18","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=x1hltR6czjAK%2B3kGRsl3kWtILv9btk5iVJUEFVfjdAA%3D%3AszBWh3XRiFNSyilFHKoGvi4QSLU28CwsYdFMcgK3Pnc%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Info(1)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0 IAV\/FF62","version":"14.0.1.1"}
{"reqId":"ArujMkNXNUX1ytmgltg0","level":3,"time":"2018-10-15T15:17:44+02:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined variable: undefinedVariable at \/var\/www\/owncloud\/3rdparty\/nikic\/php-parser\/lib\/PhpParser\/Lexer.php#70","userAgent":"--","version":"14.0.1.1"}
```

**Comment by ChristophWurst** [comment]
Sounds related to #1061. @danielkesselberg any ideas?

@menaceone what version of the app was installed before? What is the current version in your local https://github.com/nextcloud/mail/blob/master/appinfo/info.xml#L8?

**Comment by menaceone** [comment]
my current version is `0.10.0`

**Comment by danielkesselberg** [comment]
Looks like the repair step (FixCollectedAddresses in this case) is executed before the migration.

**Comment by danielkesselberg** [comment]
I have an idea :smile: When the `appinfo\database.xml` is still present migration service is not executed.
https://github.com/nextcloud/server/blob/ea21aa3f7a12c5d1bd80eea329de3eb695fde4e5/lib/private/legacy/app.php#L896-L901

@menaceone is `appinfo\database.xml` present? If so could you delete the file and try the update again? I would assume that you just extracted the mail.tar.gz in the apps folder without deleting the old mail app?

**Comment by menaceone** [comment]
>  I would assume that you just extracted the mail.tar.gz in the apps folder without deleting the old mail app?

Exactly that was it, now it's working, thank you for your help.

@ChristophWurst 
Autocompletion from addressbook **works as intended** with that patch. Very nice!

**Comment by mjanssens** [comment]
Seems to be working fine. (parts of email address and usernames are autocompleted)
Tested on NC14.0.1, deleted the mail app and extracted the tarball.
Got an upgrade message in NC web-interface, but I guess that's what normally happens in background when you upgrade an application through the app store.

**Comment by ChristophWurst** [comment]
Perfect, thanks for testing! I will try to release this ASAP and will notify you one more time to test the beta :wink:

**Pull request merged**
