### PR TITLE
First draft of a "Download all attachments" feature

### PR DESCRIPTION
**Pull request by jakobsack**
This PR adds the functionality of downloading all attachments of an email as a zip file (#552).

However, this PR has one major drawback: it uses OC\Streamer. It works fine, but it's not in the OCP namespace.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> However, this PR has one major drawback: it uses OC\Streamer.

We must not use this private class. Until we've found a solution for this, this PR is put on hold.

**Comment by jakobsack** [comment]
waiting for nextcloud/server#7589

**Comment by ChristophWurst** [comment]
Blocked by https://github.com/nextcloud/server/issues/7589#issuecomment-359202624

**Comment by ChristophWurst** [comment]
Ouch. Just tried to merge latest master into this feature branch just to keep it up-to-date but there are tons of conflicts. Thus I suggest to close this here and apply the necessary changes manually when the server PR got merged. Resolving all the conflicts is not worth the effort.

**Pull request closed without merging**
