### PR TITLE
Update version on main

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by st3iny** [comment]
We released [v1.12.0-rc.1](https://github.com/nextcloud/mail/releases/tag/v1.12.0-rc.1) but didn't branch off stable1.12 yet. I'm hesitant with approving merging this.

@miaulalala @ChristophWurst

**Comment by nickvergessen** [comment]
Yeah just wait until the final is out.
I have this app in the "multi branch support" folder, if you use stable branches I can also move it there

**Review by st3iny — APPROVED** [review]
:rocket:

**Comment by st3iny** [comment]
Failure of static analysis is unrelated.

**Pull request merged**
