### PR TITLE
Sets focus on subject field for mailto links

### LINKED ISSUE #531: For mailto: composer, focus subject field after filling »to« address
Click any mailto link on a website, and the composer is autofilled with the email address (correctly). However the focus is still in the »to« field. It would be better if the Subject were focused so you can directly continue typing.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/49363555-for-mailto-composer-focus-subject-field-after-filling-to-address?utm_campaign=plugin&utm_content=tracker%2F44154351&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44154351&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sagorika1996**
Fixes #531

### CODE REVIEW

**Comment by ChristophWurst** [comment]
```
$ sh -c "if [ '$TEST_JS' = 'TRUE' ]; then grunt; fi"
Running "jscs:src" (jscs) task
requireSpaceAfterKeywords: One space required after "if" keyword at js/views/foldercontent.js :
   125 |   }
   126 |
   127 |   if(!data.to.length) {
-------------^
   128 |    // focus 'to' field automatically on clicking New message button
   129 |    this.composer.focusTo();
requireSpaceAfterKeywords: One space required after "if" keyword at js/views/foldercontent.js :
   128 |    // focus 'to' field automatically on clicking New message button
   129 |    this.composer.focusTo();
   130 |   } else if(!data.subject) {
--------------------^
   131 |    this.composer.focusSubject();
   132 |   } else {
disallowMultipleLineBreaks: } and if should have at most 2 line(s) between them at js/views/foldercontent.js :
   132 |   } else {
   133 |    this.composer.focusMessageBody();
   134 |   }
------------^
   135 |
   136 |
>> 3 code style errors found!
Warning: Task "jscs:src" failed. Use --force to continue.
```

**Comment by ChristophWurst** [comment]
@jancborchardt @nextcloud/mail ping

**Comment by ChristophWurst** [comment]
Do mailto links actually work? I get errors because a string is passed as `to` value and this fails when the view is rendered in the `printAddressListPlain` helper that expects an array as input.

**Comment by sagorika1996** [comment]
@ChristophWurst Ya, it wasn't working for me either.

However, setting the focus to message-body/subject field can also be useful for draft/forward mails.

**Comment by ChristophWurst** [comment]
@jancborchardt ping

**Comment by ChristophWurst** [comment]
@sagorika1996 a fix for the general mailto issue would be highly appreciated if you'd like to look into that :wink:

**Pull request merged**
