### PR TITLE
Log and continue after mailbox status error

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/2412

I can not test because my setups do not have these issues. @stweil could you give this a go?

### CODE REVIEW

**Comment by stweil** [comment]
Creating a new mail account still produces a log message:

    [mail] Error: Horde_Imap_Client_Exception_ServerResponse: IMAP error reported by server. at <<closure>>

     0. /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php line 4314
        Horde_Imap_Client_Socket->_getLine(Horde_Imap_Clien ... }})
     1. /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php line 4242
        Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_Clien ... }}, [Horde_Imap_Clie ... }])
     2. /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php line 1751
        Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_Clien ... }})
     3. /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php line 1733
        Horde_Imap_Client_Socket->_status([Horde_Imap_Clie ... }], 63)
     4. /var/www/cloud/apps/mail/lib/IMAP/FolderMapper.php line 115
        Horde_Imap_Client_Base->status({INBOX: "INBOX", ... "})
     5. /var/www/cloud/apps/mail/lib/IMAP/MailboxSync.php line 92
        OCA\Mail\IMAP\FolderMapper->getFoldersStatus({INBOX: OCA\Mail ... }}, Horde_Imap_Clien ... e})
     6. /var/www/cloud/apps/mail/lib/Service/MailManager.php line 101
        OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {})
     7. /var/www/cloud/apps/mail/lib/Controller/FoldersController.php line 93
        OCA\Mail\Service\MailManager->getFolders(OCA\Mail\Account {})
     8. /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php line 170
        OCA\Mail\Controller\FoldersController->index(30)
     9. /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php line 100
        OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\FoldersController {}, "index")
    10. /var/www/cloud/lib/private/AppFramework/App.php line 137
        OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "index")
    11. /var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
        OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "index", OC\AppFramework\ ... {}, {accountId: "30" ... "})
    12. <<closure>>
        OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "30" ... "})
    13. /var/www/cloud/lib/private/Route/Router.php line 297
        call_user_func(OC\AppFramework\ ... {}, {accountId: "30" ... "})
    14. /var/www/cloud/lib/base.php line 1007
        OC\Route\Router->match("/apps/mail/api/accounts/30/folders")
    15. /var/www/cloud/index.php line 37
        OC::handleRequest()

**Comment by ChristophWurst** [comment]
> Creating a new mail account works, but still produces a log message:

For the newly created account or an existing one?

**Comment by stweil** [comment]
I removed the account and created a new one with the same data.

**Comment by ChristophWurst** [comment]
I'm not quite sure why you still ran into the error. How did you patch your system? I've updated the PR so it will allow failure of individual mailboxes. The previous version aborted with the first error, meaning that the rest of the mailboxes do not get a chance to receive their status info.

**Comment by stweil** [comment]
I now patched with both commits and get no more error messages in Nextcloud log when creating a mail account, but got a new error while reading mails:

    [mail] Error: OCA\Mail\Exception\ServiceException: Can not get messages from mailbox shared.Archives01: Could not open mailbox "shared.Archives01". at <<closure>>

    0. /var/www/cloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 199
       OCA\Mail\Service\Sync\ImapToDbSynchronizer->runInitialSync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 443})
    1. /var/www/cloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 114
       OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 443}, 42, null, false)
    2. /var/www/cloud/apps/mail/lib/BackgroundJob/SyncJob.php line 92
       OCA\Mail\Service\Sync\ImapToDbSynchronizer->syncAccount(OCA\Mail\Account {})
    3. /var/www/cloud/lib/public/BackgroundJob/Job.php line 80
       OCA\Mail\BackgroundJob\SyncJob->run({accountId: 31})
    4. /var/www/cloud/lib/public/BackgroundJob/TimedJob.php line 61
       OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
    5. /var/www/cloud/cron.php line 126
       OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

**Comment by stweil** [comment]
Unrelated: While testing I noticed that Nextcloud mail only gives access to the first two levels of folders. It also does not allow to create sub-sub folders.

**Comment by stweil** [comment]
I am afraid that the fix has an unwanted side effect: a user who still had an old invalid mail account in Nextcloud can no longer see that account or remove it. The Nextcloud log shows the error:

    [mail] Error: OCA\Mail\Exception\ServiceException: IMAP errorMail server denied authentication. at <<closure>>

**Comment by stweil** [comment]
> I am afraid that the fix has an unwanted side effect

It looks like I was wrong. That's not a regression, but the problem with old accounts which were removed on the IMAP server side already existed before that pull request.

**Comment by ChristophWurst** [comment]
> Unrelated: While testing I noticed that Nextcloud mail only gives access to the first two levels of folders. It also does not allow to create sub-sub folders.

Known!

**Comment by ChristophWurst** [comment]
> I now patched with both commits and get no more error messages in Nextcloud log when creating a mail account, but got a new error while reading mails

Is that when you open the problematic mailbox, right?

**Comment by ChristophWurst** [comment]
I have some mixed impressions with your comments here and the one in the ticket. Please clarify if this improves things, makes the worse or is just neutral.

**Comment by stweil** [comment]
The pull request improves things a lot because mail accounts which have folders without access permission no longer prevent accessing the account at all. It also allows creating a new mail account for an IMAP server with inaccessible folders.

The fix is still incomplete because it looks like not all accessible folders are shown to the user. Maybe parsing the folder list stops at the first inaccessible folder, so accessible folders which come later are skipped.

**Comment by ChristophWurst** [comment]
Let's not do this if it improves things just a bit. This smells like it cause some other troubles.

**Pull request closed without merging**
