### PR TITLE
fix(message-filter): Show starred messages in Favourites again

### PR DESCRIPTION
**Pull request by JohannesGGE**
Fix: #7988 

Show starred messages in 'Favourites' again.

### CODE REVIEW

**Comment by JohannesGGE** [comment]
Currently only starred messages in the INBOX are shown. So maybe we should filter all mailboxes?

**Comment by ChristophWurst** [comment]
> Currently only starred messages in the INBOX are shown. So maybe we should filter all mailboxes?

It's intentionally just INBOX

**Review by ChristophWurst — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Review by st3iny — APPROVED** [review]

**Pull request merged**
