### PR TITLE
fix: dashboard loading forever

### PR DESCRIPTION
**Pull request by st3iny**
Ref https://github.com/browserify/node-util/issues/57#issuecomment-764436352

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I though this was addressed already with https://github.com/nextcloud/mail/pull/8152

**Comment by ChristophWurst** [comment]
```
├── @nextcloud/dialogs@3.2.0
├─┬ @nextcloud/vue-dashboard@2.0.1
│ └─┬ @nextcloud/vue@3.9.0
│   └── @nextcloud/dialogs@3.2.0 deduped
└─┬ @nextcloud/vue@7.8.0
  └── @nextcloud/dialogs@4.0.1
``` 

^ guess it's back

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
fyi main is v3.1, 3.0 lives on stable3.0

**Comment by st3iny** [comment]
Test failure is unrelated and fixed on main.

**Pull request merged**
