### PR TITLE
fix(provisioning): Clear config cache after every mutation

### PR DESCRIPTION
**Pull request by ChristophWurst**
Refinement of https://github.com/nextcloud/mail/pull/6325.

The cached config can cause the recreation of a deleted provisioned account

1) Config created and cached, accounts provisioned
2) Config deleted and accounts deleted
3) User opens the app, cached config is used, provisioned account is missing -> account created

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]
LGTM

**Comment by ChristophWurst** [comment]
Mind giving this a test?

**Comment by miaulalala** [comment]
Tested the following:

Domain match: test.com
User email: test@test.com

Matched on first login, provisioned

Deleted provisioning config - user had no provisioning on next login

Tried wildcard provisioning - that didn't find any users as the provisioning domain wasn't updated:

The payload was:

```json
{
    "data": {
        "id": null,
        "active": true,
        "emailTemplate": "%USERID%@giga.cube",
        "provisioningDomain": "*",
        "imapUser": "%USERID%@giga.cube",
        "imapHost": "mx.giga.cube",
        "imapPort": 993,
        "imapSslMode": "ssl",
        "smtpUser": "%USERID%@giga.cube",
        "smtpHost": "mx.giga.cube",
        "smtpPort": 587,
        "smtpSslMode": "tls",
        "sieveEnabled": "",
        "sieveUser": "",
        "sieveHost": "",
        "sievePort": "",
        "sieveSslMode": "",
        "ldapAliasesProvisioning": false,
        "ldapAliasesAttribute": ""
    }
}
```

which is converted to an int somewhere leading to the provisioningmapper setting the ID to 0, which then can't be found in the DB which leads to a NOOP basically.

I think there's a bug in the vue side.

**Comment by ChristophWurst** [comment]
Right. The config can only be deleted if you reload the page after creation.

**Comment by miaulalala** [comment]
> Right. The config can only be deleted if you reload the page after creation.

that must be a side effect too, yeah.

Basically, I tried to update a provisioning config that already existed, but that didn't work.

**Comment by st3iny** [comment]
Conflicts!

```diff
diff --cc lib/Service/Provisioning/Manager.php
index 39575ade7,09af07cb5..000000000
--- a/lib/Service/Provisioning/Manager.php
+++ b/lib/Service/Provisioning/Manager.php
@@@ -252,9 -253,13 +253,17 @@@ class Manager 
  	 * @throws ValidationException
  	 * @throws \OCP\DB\Exception
  	 */
 -	public function newProvisioning(array $data): void {
 +	public function newProvisioning(array $data): Provisioning {
  		$provisioning = $this->provisioningMapper->validate($data);
++<<<<<<< HEAD
 +		return $this->provisioningMapper->insert($provisioning);
++=======
+ 		$this->provisioningMapper->insert($provisioning);
+ 		if ($this->cacheFactory->isAvailable()) {
+ 			$cache = $this->cacheFactory->createDistributed(self::MAIL_PROVISIONINGS);
+ 			$cache->clear();
+ 		}
++>>>>>>> 735ec7ee0 (fix(provisioning): Clear config cache after every mutation)
  	}
  
  	/**
```

**Review by st3iny — APPROVED** [review]
Tested and works. Was able to reproduce the bug without this PR. The provisioned accounts are not recreated with this PR.

**Pull request merged**
