### PR TITLE
Open image, video, audio and PDF attachments with viewer

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/6983

- [x] Requires https://github.com/nextcloud/viewer/pull/1338
- [x] Requires https://github.com/nextcloud/files_pdfviewer/pull/646
- [x] Requires https://github.com/nextcloud/viewer/pull/1350
- [x] Keep allow list of mimes we know work, because there are a handful of Viewer handlers that don't work at the moment
- [x] Requires https://github.com/nextcloud/viewer/pull/1348 to close the Viewer again
- [x] Requires https://github.com/nextcloud/viewer/pull/1349 for a working *Download* action inside the Viewer
- [x] Requires https://github.com/nextcloud/files_pdfviewer/pull/648 for the PDF viewer to work
- [x] Version check to make this only available with 25+ (older Viewer would error out)

## Tested media

* PDFs
* JPEG
* GIF
* OGG
* MP4

## How to test

1) Create an account
2) Send an email to yourself with various attachments
3) Open the email
4) Click the attachment - it will open if its supported

### CODE REVIEW

**Comment by GretaD** [comment]
i am having this error when i click the attachment(all of the formats)

```
`vue.runtime.esm.js:4573 [Vue warn]: Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'startsWith')"

found in

---> <MessageAttachment> at src/components/MessageAttachment.vue
       <MessageAttachments> at src/components/MessageAttachments.vue
         <Message> at src/components/Message.vue
           <ThreadEnvelope> at src/components/ThreadEnvelope.vue
             <NcAppContentDetails>
               <Thread> at src/components/Thread.vue
                 <Pane>
                   <Splitpanes>
                     <NcAppContent>
                       <MailboxThread> at src/components/MailboxThread.vue
                         <Content>
                           <Home> at src/views/Home.vue
                             <App> at src/App.vue
                               <Root>`
```

**Comment by GretaD** [comment]
Screenshot from 2022-09-01 15-42-23

**Comment by ChristophWurst** [comment]
Inspect the MessagesAttachemnt**s** component. It has a `fileInfos` computed prop. Do all objects in the array have a `mime` property?

**Review by JuliaKirschenheuter — APPROVED** [review]
works well!

**Comment by JuliaKirschenheuter** [comment]
> i am having this error when i click the attachment(all of the formats)

i've checked it too but can't reproduce it

**Comment by sazanof** [comment]
Maybe because 

image
```
open({ path, list = [], loadMore = () => ([]), canLoop = true, onPrev = () => {}, onNext = () => {}, onClose = () => {} } = {}) {
```
 that an object is passed instead of string (path variable === fileInfo)?


> Inspect the MessagesAttachemnt**s** component. It has a `fileInfos` computed prop. Do all objects in the array have a `mime` property?

Yep. 
image

**Comment by ChristophWurst** [comment]
> Requires https://github.com/nextcloud/viewer/pull/1338

Pull the latest `master` of https://github.com/nextcloud/viewer/. It now allows passing a fileinfo object, not just paths.

**Comment by sazanof** [comment]
> > Requires [nextcloud/viewer#1338](https://github.com/nextcloud/viewer/pull/1338)
> 
> Pull the latest `master` of https://github.com/nextcloud/viewer/. It now allows passing a fileinfo object, not just paths.

Yes, thank you. Now images are open in modal correct. But only images, not PDF or audio files.

canPreview is false, because `application/pdf` not found in `OCA.Viewer.mimetypes`

**Pull request merged**
