### PR TITLE
fix background touches search input

### LINKED ISSUE #7919: Envelope hover/active background touches mailbox search input
### Steps to reproduce

1. Open the app
2. Configure an account
3. Open your inbox (**not** priority or all inboxes)

### Expected behavior

Nice design

### Actual behavior

Bildschirmfoto vom 2023-01-19 10-25-53

### Mail app version

1.15

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
Fixes #7919 

**Before:**
image

**After:**
image

Signed-off-by: hamza221 <hamzamahjoubi221@gmail.com>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Please add before/after screenshots to your PR description

**Review by GretaD — APPROVED** [review]
works

**Comment by ChristophWurst** [comment]
Let's get this fix out for Nextcloud 24 and 25. According to https://apps.nextcloud.com/apps/mail that is v2.2.x and v1.15.x

**Comment by ChristophWurst** [comment]
@hamza221 try your luck with a manual backport following https://docs.nextcloud.com/server/latest/developer_manual/getting_started/development_process.html#manual-backport. If the code isn't there then we can skip the backport.

**Comment by ChristophWurst** [comment]
I believe the search input wasn't there before v2.

https://github.com/nextcloud/mail/pull/8016 conflicts as well.

**Comment by hamza221** [comment]
> I believe the search input wasn't there before v2.

So we can skip the backport?

**Comment by hamza221** [comment]
> I believe the search input wasn't there before v2.
> 
> #8016 conflicts as well.

image

We can still apply the changes to v2.2  the conflict is because the attribute I'm removing was not added yet

**Pull request merged**
