### PR TITLE
Message view cleared, when last message is deleted from a folder

### LINKED ISSUE #638: When deleting last message from a folder, clear the message view
When you delete the last message from a folder, the content of that last message is still shown in the right content column.

As proper feedback that it is removed, that message view should also be cleared. (Just like it advances to the next message when there’s still others in the folder.)

### PR DESCRIPTION
**Pull request by sagorika1996**
Fixes #638

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@jancborchardt give this a quick test please :)

**Comment by ChristophWurst** [comment]
> First-time contributo

Congrats on your first contribution to this app :fireworks:

**Comment by ChristophWurst** [comment]
@jancborchardt ping

**Comment by sagorika1996** [comment]
This doesn't work, so I'm closing it for now. I'll try to fix the issue soon.

**Comment by sagorika1996** [comment]
@ChristophWurst @jancborchardt Don't know if its the correct way to do fix this, but its working now. Can someone review this PR.

**Comment by ChristophWurst** [comment]
@jancborchardt please test

**Comment by jancborchardt** [comment]
@sagorika1996 congrats on your contribution! :)

**Pull request merged**
