### PR TITLE
Show itinerary info

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Very nice! Only some small issues at the moment:
- [ ] If I click one of the "Plus"-Buttons in a list with multiple itinerary steps, all of them show a spinner
- [ ] The min-width is a bit wide, meaning on smartphones stuff overflows to the right. Could be fixed by wrapping the part with the reservation code below the flight name. (Have tried with `white-space:` CSS but didn’t work?

Otherwise we should really make sure to check with different companies, platforms etc so we make sure we show itinerary info from the most common ones. :)

**Comment by ChristophWurst** [comment]
Build 1a40f6310ada1e397e35820bb88e5e204706be61 [mail.tar.gz](https://github.com/nextcloud/mail/files/3920803/mail.tar.gz)

**Comment by ChristophWurst** [comment]
Build 9b9bad1974ac54412488e99a5f4fdc0e9971054a [mail.tar.gz](https://github.com/nextcloud/mail/files/3921157/mail.tar.gz)

**Comment by ChristophWurst** [comment]
> Otherwise we should really make sure to check with different companies, platforms etc so we make sure we show itinerary info from the most common ones. :)

This is out of scope for us. https://community.kde.org/KDE_PIM/KItinerary/Supported_Providers is the limiting factor here. Anything they support will show up here.

**Comment by ChristophWurst** [comment]
Build a230ad96c6149d9253e9ddf4359db876aa020f16 [mail.tar.gz](https://github.com/nextcloud/mail/files/3922704/mail.tar.gz)

**Comment by ChristophWurst** [comment]
3c6c2b70d6a9cb4775bad8918174b9fe4014381c fixes the issue that the special flagged inbox didn't work before as we tried to open an IMAP mailbox that only virtually exists. @mario you don't know that I know but you ran into this. Props to Sentry for capturing this :)

**Comment by ChristophWurst** [comment]
>     * If I click one of the "Plus"-Buttons in a list with multiple itinerary steps, all of them show a spinner

Not reproducible here.

>     * The min-width is a bit wide, meaning on smartphones stuff overflows to the right. Could be fixed by wrapping the part with the reservation code below the flight name. (Have tried with `white-space:` CSS but didn’t work?

Can be fixed in a follow-up

**Comment by StCyr** [comment]
Don't know how to test this.

I'm guesssing this needs Linux/KDE for it to be effective.

Anyway it builds, upgrade, and runs properly here.

**Comment by ChristophWurst** [comment]
> Don't know how to test this.
> 
> I'm guesssing this needs Linux/KDE for it to be effective.

Just open an email with something like a train ticket or flight ticket.

It works out of the box, but not on all systems. If you don't run Linux x86_64 it won't show anything.

Make sure you install composer dependencies with `composer install` :)

**Pull request merged**
