### PR TITLE
Fix to #4218

### LINKED ISSUE #4218: Reply to sender only doesn't work in ThreadEnvelope's action menu entry
### Expected behavior
Clicking on 'Reply to sender only' on a ThreadEnvelope's action menu should open a new message 

### Actual behavior
Nothing happens and the following shows up in the console:

```
 [Vue warn]: Error in v-on handler: "TypeError: handler.apply is not a function"

found in

---> <ActionButton>
       <VPopover>
         <Popover>
           <Actions>
             <ThreadEnvelope> at src/components/ThreadEnvelope.vue
               <AppContentDetails>
                 <Thread> at src/components/Thread.vue
                   <AppContent>
                     <MailboxThread> at src/components/MailboxThread.vue
                       <Content>
                         <Home> at src/views/Home.vue
                           <App> at src/App.vue
                             <Root>
```

### Mail app

**Mail app version:** master and 1.7.1

### PR DESCRIPTION
**Pull request by StCyr**
Apparently, ActionButton don't like computed properties

Fixes #4218

Signed-off-by: Cyrille Bollu <cyr.debian@bollu.be>

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Comment by ChristophWurst** [comment]
backports?

**Comment by StCyr** [comment]
I suppose

**Comment by ChristophWurst** [comment]
This broke the reply button

**Pull request merged**
