### PR TITLE
Support for selecting messages with crtl key

### LINKED ISSUE #8048: Support Multiselect of Emails using Shift key
### Is your feature request related to a problem? Please describe.

Right now you need to start multiselect of emails via the ... menu which is cumbersome. I would expect that pressing shift would allow me to select multiple messages but instead it opens (in chrome) a new window.

### Describe the solution you'd like

Implement multiselect using shift + click on the keyboard for many messages and ctrl/cmd + click for selected few messages.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rcsilva83**
Partially fixes #8048 because using shift key only works after some message is selected.

### CODE REVIEW

**Comment by rcsilva83** [comment]
My PR doesn't have any PHP code modifications. I think these test failures have nothing to do with my code.

**Comment by ChristophWurst** [comment]
It's only the coverage report upload that fails :+1:

**Comment by Chartman123** [comment]
@GretaD @ChristophWurst I just updated to Mail 3.3.0 on my instance and selecting mails with ctrl key opens every mail in a new tab... Should I open a separate issue?

**Comment by rcsilva83** [comment]
> @GretaD @ChristophWurst I just updated to Mail 3.3.0 on my instance and selecting mails with ctrl key opens every mail in a new tab... Should I open a separate issue?

Just made a pull request to fix this: https://github.com/nextcloud/mail/pull/8798

**Pull request merged**
