### PR TITLE
Increased the space between label from and to

### PR DESCRIPTION
**Pull request by RucajDenisa**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Actually, the dropdown an the other inputs should stick together, like the inputs on the setup screen:
bildschirmfoto von 2016-09-23 10-05-19

cc @jancborchardt since you once wanted to fix that too :wink:

**Comment by ChristophWurst** [comment]
@RucajDenisa ping :-)

**Comment by jancborchardt** [comment]
I totally agree with the missing whitespace issue. So I took it a step further here: https://github.com/nextcloud/mail/pull/162 :) What do you think?

**Comment by ChristophWurst** [comment]
I'd say this can be closed now. Thanks :-)

**Comment by jancborchardt** [comment]
Thank you for the inspiration @rucajdenisa! :) Hope you like the new design

**Pull request closed without merging**
