### PR TITLE
fix IDb to IDBConnection, fix #237

### LINKED ISSUE #237: IDb was deprecated for 3 years already and is going to be removed for 12
But it's still used:
```
grep "IDb " -i -r apps/mail/
appstank/mail/lib/Db/CollectedAddressMapper.php:	 * @param IDb $db
appstank/mail/lib/Db/CollectedAddressMapper.php:	public function __construct(IDb $db) {
appstank/mail/lib/Db/AliasMapper.php:	 * @param IDb $db
appstank/mail/lib/Db/AliasMapper.php:	public function __construct(IDb $db) {
appstank/mail/lib/Db/MailAccountMapper.php:	 * @param IDb $db
appstank/mail/lib/Db/MailAccountMapper.php:	public function __construct(IDb $db) {
```

@ChristophWurst

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #237, ref https://github.com/nextcloud/server/pull/2665

Please review @nextcloud/mail

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Nice 🚀. To make Travis happy you have to bump the max-version of Nextcloud in info.xml here too :-)

**Comment by jancborchardt** [comment]
Cherry-picked the version change over ;)

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/search?utf8=%E2%9C%93&q=%22new+db%22&type=Code

**Comment by jancborchardt** [comment]
@ChristophWurst that’s where my search-replace magic ends I guess. Any help cc @nickvergessen?

**Comment by nickvergessen** [comment]
Not really hard either, pushed

**Comment by jancborchardt** [comment]
@nickvergessen looking at the changes, it is of course hard for someone who is not a PHP developer. ;) So thanks!

**Pull request merged**
