### PR TITLE
add proper COPYING agplv3 license file

### PR DESCRIPTION
**Pull request by ChristophWurst**
I just noticed we should add a COPYING file to our repo.

cc @nextcloud/mail

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! :+1:

**Comment by ChristophWurst** [comment]
hehe, now GitHub recognizes our license too
bildschirmfoto von 2016-09-13 11-32-47

**Comment by jancborchardt** [comment]
Haha I just wanted to merge, how quick are you? :D

**Comment by ChristophWurst** [comment]
maybe you're too slow? :-P

**Pull request merged**
