### PR TITLE
Move the Alias/AliasMapper to the QBMapper

### PR DESCRIPTION
**Pull request by rullzer**
Properly use the query builder.
Typehinting
Strict

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Travis is not happy

**Comment by rullzer** [comment]
Yeah you need to make the app 16 compatible ;)

**Comment by ChristophWurst** [comment]
> you

https://www.agilealliance.org/glossary/collective-ownership/ :wink:

**Comment by ChristophWurst** [comment]
@rullzer rebase
@rullzer merge

**Comment by ChristophWurst** [comment]
Thanks!

**Pull request merged**
