### PR TITLE
Add loading skeletons without avatars

### PR DESCRIPTION
**Pull request by hamza221**
With avatar
image
Without avatar 
image

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Comment by ChristophWurst** [comment]
What does this change and is it a fix or a feature? Do we need backports?

**Comment by hamza221** [comment]
> What does this change and is it a fix or a feature? Do we need backports?

The condition was missing, to show loading skeletons without avatars. but the prop was already there. 
I'll add screenshots for with/without skeletons. 
We need backports I think, i'll check when this was introduced and add them

**Comment by hamza221** [comment]
@ChristophWurst we never needed this use case before thread summary, even tho the condition is missing. I don't think the backport is really needed. what do you think?

**Comment by ChristophWurst** [comment]
skipping backports sounds fine

**Pull request merged**
