### PR TITLE
Add missing methods for important and favorite

### PR DESCRIPTION
**Pull request by GretaD**
Signed-off-by: GretaD <gretadoci@gmail.com>

### CODE REVIEW

**Comment by st3iny** [comment]
Toggling important and favorite flags works without the changes here. What am I supposed to observe before and after?

**Comment by GretaD** [comment]
> Toggling important and favorite flags works without the changes here. What am I supposed to observe before and after?

so you're saying we dont need the div at all? I saw an empty method and added the method for that.

**Comment by ChristophWurst** [comment]
> Toggling important and favorite flags works without the changes here. What am I supposed to observe before and after?

Did you toggle with the action or the start/important icon?

**Comment by st3iny** [comment]
Ahh now I get it :sweat_smile: I didn't know those were buttons. I thought it was about the action menu.

**Review by st3iny — APPROVED** [review]
Both toggles work again

**Comment by ChristophWurst** [comment]
when was the regression introduced? do we need a backport?

**Comment by st3iny** [comment]
Can confirm the regression being present on stable1.9.

**Comment by st3iny** [comment]
I don't know what exactly I tested back then but this regression is not gone on master. I will provide a new PR asap. Sorry :eyes:

**Pull request merged**
