### PR TITLE
Fix font menu size

### PR DESCRIPTION
**Pull request by GretaD**
before
accountmenub
after
accountmenu
before
threadmenub
after
threadmenu
before
mailboxmenub
After
mailboxmenu

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I'm not sure. Why do we need to have our own font size for this? Is there no standard from nc-vue?

**Comment by GretaD** [comment]
> I'm not sure. Why do we need to have our own font size for this? Is there no standard from nc-vue?

it is font-size=normal i think. But it is not applying to all our actions in menus. I agree, it should be nc-vue standard.

**Comment by skjnldsv** [comment]
Yeah, please fix it from the components directly :)

**Comment by GretaD** [comment]
sure

**Pull request closed without merging**
