### PR TITLE
Show recipient avatars only in thread header

### PR DESCRIPTION
**Pull request by st3iny**
Ref https://github.com/nextcloud/mail/pull/4315#issuecomment-786748992

Requires https://github.com/nextcloud/nextcloud-vue/pull/1745

A more compact thread participant header.

compact-thread-header

### CODE REVIEW

**Comment by st3iny** [comment]
Cc @ChristophWurst

**Comment by st3iny** [comment]
Is this something we want to have? If so, I'd be happy to move on with the upstream PR :)

**Comment by ChristophWurst** [comment]
@nimisha-vijay what do you think? :)

**Comment by nimisha-vijay** [comment]
This looks good actually! Although I am concerned about how informative this would be if a participant had a weird email address, because this does not show the name anywhere. With the way it is right now, we are able to identify each person quickly because their names are very easily visible. What do you think?

**Comment by st3iny** [comment]
I agree. It looks nice but losing the ability to quickly grasp participant email addresses isn't worth it.

**Pull request closed without merging**
