### PR TITLE
feat(imap): Persist if mailbox is shared or not

### PR DESCRIPTION
**Pull request by ChristophWurst**
Groundwork for https://github.com/nextcloud/mail/issues/8157

### How to test

1) Add an account that has ACL support and receives mailboxes
2) Inspect oc_mail_mailboxes for that account
3) All received mailboxes have shared=1

### CODE REVIEW

**Comment by GretaD** [comment]
i tested it couple of time and i still see 0 for the shared ones. Am i testing it wrong

did the steps written in this ticket,
also, created a new mailbox and shared it then opened the account that i shared this mailbox, i see the mailbox but shared column has 0

**Comment by ChristophWurst** [comment]
Did you add the account anew or is it an account that existed before you checked out the branch? Mailboxes are cached for 2h

**Comment by GretaD** [comment]
> Did you add the account anew or is it an account that existed before you checked out the branch? Mailboxes are cached for 2h

Yes, and i can see 1 now.

**Review by GretaD — APPROVED** [review]
tested and it works

**Pull request merged**
