### PR TITLE
Filter messages sent in the last 7 days and from me

### LINKED ISSUE #9182: Add filter shortcuts (like Has attachment, Last 7 days and From me)
### Is your feature request related to a problem? Please describe.

To make mail app more efficient we should add some more filter on the advance search modal.
3 proposals would be:

1. Has attachment, 
2. Last 7 days  
3. From me

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #9182 

with pressed state

Screenshot from 2024-04-18 13-23-12
Screenshot from 2024-04-18 13-22-38

### CODE REVIEW

**Comment by GretaD** [comment]
when i click "from me" the from field is field with my email, but the option is not clicked
Screenshot from 2024-04-04 17-36-54

**Comment by ChristophWurst** [comment]
I think the filter shortcuts should be regular buttons, not radio buttons

**Comment by GretaD** [comment]
@st3iny had a comment that he would prefer that the "has attachment" to be a checkbox instead of a button. I left it as a button, as it was requested that the shortcuts to be buttons. But i can change it again, if more agree with Richard.

**Review by st3iny — CHANGES_REQUESTED** [review]
The search is not reset after disabling a button again. I guess that should work?

E.g. I click `Last 7 days` and then click it again and expect that all mails are now shown again as the filter is toggled. However, the filter stays on last 7 days even if the button is not primary any longer.


https://github.com/nextcloud/mail/assets/1479486/327ad8ad-4d5c-42b3-8381-1825ee14645a

**Review by st3iny — APPROVED** [review]
Tested and works.

**Pull request merged**
