### PR TITLE
Bump @nextcloud/vue to v6.0.0-beta4

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/6978
Fixes https://github.com/nextcloud/mail/issues/6979

### CODE REVIEW

**Comment by ChristophWurst** [comment]
- [ ] BUG Nav, actions menu and z-index 

Bildschirmfoto vom 2022-08-23 19-30-01

**Comment by ChristophWurst** [comment]
- [ ] Nitpick: FF scroll bar is a thin line and overlaps buttons in a visually unpleasant way. It feels like the bar should be moved more to the right, or that there should be space between the bar and the buttons. Just a detail.

Bildschirmfoto vom 2022-08-23 19-30-26

**Comment by ChristophWurst** [comment]
- [ ] BUG nav expand icon moved to the right instead of replacing the item icon on hover

Bildschirmfoto vom 2022-08-23 19-40-13

**Comment by GretaD** [comment]
- [ ] 
Screenshot from 2022-08-23 19-43-43

**Comment by ChristophWurst** [comment]
- [ ] BUG active list item radius doesn't match hover radius

Bildschirmfoto vom 2022-08-23 19-48-24

**Comment by ChristophWurst** [comment]
- [ ] BUG actions menu overflows into non-visible are on small screens

Bildschirmfoto vom 2022-08-23 19-49-42

**Comment by ChristophWurst** [comment]
- [ ] BUG Primary envelope actions have inconsistent font size

Bildschirmfoto vom 2022-08-23 19-50-48

**Comment by ChristophWurst** [comment]
- [ ] BUG keyboard shortcut modal *X* button has no pointer cursor (can't screenshot that)
- [ ] BUG same button scrolls out of the modal. Make the window small to force a vertical scroll bar in the modal. Then scroll down.

Bildschirmfoto vom 2022-08-23 19-53-45

**Comment by ChristophWurst** [comment]
With the exception of the keyboard shortcuts modal all regressions are also found with nc/vue@6-beta3 on main, so I've moved them into dedicated tickets.

**Comment by GretaD** [comment]
> Fixes #6978
Screenshot from 2022-08-30 17-03-22

this is still happening, to fix this i have pushed this fix here: https://github.com/nextcloud/mail/pull/7078

**Comment by ChristophWurst** [comment]
> this is still happening, to fix this i have pushed this fix here: #7078

Yes, on beta3 already: https://github.com/nextcloud/mail/issues/7098

**Review by GretaD — APPROVED** [review]

**Pull request merged**
