### PR TITLE
Add threading to frontend

### LINKED ISSUE #5322: thread list grouping not working 100%
How are you grouping the thread list?

In the screenshoot you find 2 spam mails "Rosie Burrows".
The mail app threaded it correctly but in the list it is seperated:

Bildschirmfoto von 2021-07-13 08-17-32

header first e-mail: [1.txt](https://github.com/nextcloud/mail/files/6806334/1.txt)
header second e-mail: [2.txt](https://github.com/nextcloud/mail/files/6806333/2.txt)
(SPAM / no confidential infromation included)

I have other exmaples where threading not works but step by step :)

### PR DESCRIPTION
**Pull request by kesselb**
Fix #5322 

23c0156a0214cbde6a67827f7d11933bd82eecd0 Add a getter to fetch envelopes from store by using a thread root id. 
a4e94c8777c77b7d8236c452dc908dbee993a793 Add helper to append or replace a existing envelope.

| | Before | After |
| --- | --- | --- |
| A reply for a thread already<br/> shown in envelope list | - New thread shown in envelope list<br/>- (When thread selected) message is not shown in message list | - Existing thread in evelope list is updated<br/>- (When thread selected) new reply is shown in message list |

**Open items / To decide**

- [ ] Update route `mail/box/10/thread/$latestMessageId`
- [ ] Rework `Mailbox.onDelete` /  `fetchNextEnvelopes` to not load new messages when a message but not the whole thread is deleted.

**How to test**
- Take email from https://github.com/nextcloud/mail/issues/5322
- Import to mail account (e.g. via thunderbird)
- Open mail and view mailbox
- Import the same message again to mail account
- Wait a few seconds orpress refresh mailbox button (but don't reload the page)

### CODE REVIEW

**Comment by kesselb** [comment]
**Before**

https://user-images.githubusercontent.com/3902676/168052210-74c972f6-4b83-42e0-a59c-d25140ea106c.mp4

**After**


https://user-images.githubusercontent.com/3902676/168052370-6fc49c08-70a3-4bd8-ad8c-f08484dd363d.mp4

**Comment by st3iny** [comment]
Please rebase to main.

**Comment by kesselb** [comment]
@st3iny done done

**Review by st3iny — COMMENTED** [review]
It works well. 

However, I noticed one strange issue: Threading data seems to be shared across accounts. I have 2 mail accounts in my test setup and sent emails back and forth between them. The threading view always showed each message twice (once for every account I believe) because it is in the sent folder of user A and the inbox of user B. When I deleted one of the mail accounts the problem disappeared.

I can't remember this to happen previously.

**Comment by kesselb** [comment]
Good catch :+1: 

I guess the former `threadId` was a reference to the database id and unique for the current account. All messages are stored in the same store and a query for all message with threadRootId x will find all messages in the store for this threadRootId :see_no_evil: 

Let's see if adding the account id is already enough to fix it ;)

**Review by st3iny — APPROVED** [review]
Tested and works. The issue I mentioned earlier is fixed. Code looks good too.

**Comment by ChristophWurst** [comment]
Front-end test ``Vuex store getters – return envelopes by thread root id`` fails

**Comment by kesselb** [comment]
> After merge I see the open todo. Did I merge too early?

No. I think we decided against it a while ago and can still do it in a follow-up.

**Pull request merged**
