### PR TITLE
Use composer v1 on Github CI

### PR DESCRIPTION
**Pull request by ChristophWurst**
Horde doesn't work with composer v2 yet.

tehc

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@backportbot-nextcloud try harder

**Comment by ChristophWurst** [comment]
damn

**Comment by MorrisJobke** [comment]
Did the backport happen?

**Comment by ChristophWurst** [comment]
Yes, via https://github.com/nextcloud/mail/pull/3912

**Pull request merged**
