### PR TITLE
Close #2375

### LINKED ISSUE #2375: "Delete account" should be last entry in account menu
In the account menu in the app navigation, "Delete account" is the second entry for each account.

Instead it should always be last. As always, the destructive action is last in a list.

@ChristophWurst if you point out where this would have to be changed, this would make for a nice "good first issue". :)

### PR DESCRIPTION
**Pull request by sayashraaj**
Moved delete action down the list

### CODE REVIEW

**Comment by ChristophWurst** [comment]
FYI you could have pushed your changes to https://github.com/nextcloud/mail/pull/2379 but let's continue here :)

**Comment by ChristophWurst** [comment]
You have to sign off your commits: https://github.com/nextcloud/mail/pull/2380/checks?check_run_id=353125473. Let me know if you need help with that.

**Comment by sayashraaj** [comment]
Hi,
I have signed off my commits. Is there any other step I need to do? Will there be a merge between my branch and master branch, now that he issue is resolved (I hope), or is there any other step to be followed?
Pardon me if I am asking silly questions, I just want to learn and get the hang of contributing to Open Source
Thank you

**Comment by ChristophWurst** [comment]
> Hi,
> I have signed off my commits. Is there any other step I need to do? Will there be a merge between my branch and master branch, now that the issue is resolved (I hope), or is there any other step to be followed?
> Pardon me if I am asking silly questions, I just want to learn and get the hang of contributing to Open Source
> Thank you

All good :) I'll merge your branch now.

**Comment by jancborchardt** [comment]
Good stuff @sayashraaj! Welcome to Nextcloud Mail :)

**Comment by sayashraaj** [comment]
Wow! Thank you for aiding me in my first contribution to Nextcloud Mail. I will continue contributing!

**Pull request merged**
