### PR TITLE
Fix preview string showing outside box thread

### PR DESCRIPTION
**Pull request by GretaD**
before
Screenshot from 2023-05-03 13-37-41
after
Screenshot from 2023-05-03 15-17-02

### CODE REVIEW

**Comment by ChristophWurst** [comment]
after?

**Comment by st3iny** [comment]
What about an ellipsis (...) via `text-overflow: ellipsis`?

**Comment by ChristophWurst** [comment]
I agree that it should use ellipsis for the overflow. For ellipsis you need to fix the element width AFAIR. Only then it works.

**Comment by st3iny** [comment]
You also need to set overflow and white-space for the ellipsis to work. In some cases the width of the text element also needs to be set (e.g. 100%) as Christoph said.

Example:
```css
text-overflow: ellipsis;
overflow: hidden;
white-space: nowrap;
```

**Review by st3iny — APPROVED** [review]
Tested and works.

**Pull request merged**
