### PR TITLE
Automaticaly sync mailbox on opening

### PR DESCRIPTION
**Pull request by StCyr**
Fixes https://github.com/nextcloud/mail/issues/3951

### CODE REVIEW

**Comment by GretaD** [comment]
right now it looks like this. Did we move the overlay spinner and kept only the load more one? @ChristophWurst 
sync

**Comment by StCyr** [comment]
This PR is somewhat linked to this one => https://github.com/nextcloud/mail/pull/3686

Change made to Composer.vue in https://github.com/nextcloud/mail/pull/3686 should probably be reverted when both PR are implemented

**Comment by ChristophWurst** [comment]
> right now it looks like this. Did we move the overlay spinner and kept only the load more one? @ChristophWurst

The overlay spinner at the top of the list is expected. It shows every time a mailbox is refreshed.

**Review by ChristophWurst — APPROVED** [review]
Works really well

**Pull request merged**
