### PR TITLE
We do not have nightly builds at the moment

### PR DESCRIPTION
**Pull request by ChristophWurst**
We should either remove or fix this.

Generally, I would prefer to have a solution that is maintainable by nc mail devs.

cc @enoch85 @nextcloud/mail

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Okay, I played a bit with Travis' API and we can easily trigger a "special" build by a cronjob script.

```bash
body='{
"request": {
  "message": "Nightly build",
  "branch":"master",
  "config": {
    "env": {
      "matrix": ["DB=sqlite CORE_BRANCH=master TEST_JS=FALSE PHP_COVERAGE=FALSE PACKAGE=TRUE NIGHTLY=TRUE"]
    },
    "php": ["7"],
    "matrix": {
        "fast_finish": false
    }
  }
}}'

curl -s -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Travis-API-Version: 3" \
  -H "Authorization: token xxxxxxx" \
  -d "$body" \
  https://api.travis-ci.org/repo/Nextcloud%2Fmail/requests
```

All we have to do is upload the artifact somewhere. Do you have a FTP server that we could use for that @Gomez? Let's hack something in the next week ;-)

I'd prefer such a solution over the one we had in the past because then everybody can see the nightly build results on travis-ci.org -> https://travis-ci.org/nextcloud/mail/builds/159929194 :rocket: 

The next step would be to also submit the nightly to the shiny new Nextcloud app store.

**Comment by ChristophWurst** [comment]
Relevant app store docu: https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#publish-a-new-app-release – that one-liner can be added to the travis file. Should be doable easily

**Comment by irgendwie** [comment]
Do you want to fix the new nightly builds in a different PR or here?
Anyway the Changes to the README are Ok! :+1:

**Comment by ChristophWurst** [comment]
another PR. We'll first have to find a server we can upload the zip to.

**Comment by enoch85** [comment]
missed this :/

**Pull request merged**
