### PR TITLE
Load more message(s) on delete

### PR DESCRIPTION
**Pull request by StCyr**
fixes https://github.com/nextcloud/mail/issues/863

### CODE REVIEW

**Comment by GretaD** [comment]
Hey Cyrill, can you still reproduce the initial problem? Because the scroll problem thing, it is fixed, the only thing left is that if you delete and dot scroll, no new message are shown. This PR fetches new messages when you delete one, but blocks the scroll. So i cannot load more by scrolling to the end. Also, every time the load more is "activated" this error pops up on console:

**Comment by StCyr** [comment]
> Hey Cyrill, can you still reproduce the initial problem? Because the scroll problem thing, it is fixed, the only thing left is that if you delete and dont scroll, no new message are shown. This PR fetches new messages when you delete one, but blocks the scroll. So i cannot load more by scrolling to the end. Also, every time the load more is "activated" this error pops up on console:

What I'm experiencing here is that it works actually: It just pops up the here under error and doesn't show the loading spining icon.

> mail: could not fetch next envelope page
> Object { app: "mail", uid: "greta", error: TypeError }
> ConsoleLogger.js:54
> log ConsoleLogger.js:54
> error ConsoleLogger.js:80
> _callee5$ Mailbox.vue:388

Yes, I saw that. I'm investigating

**Comment by StCyr** [comment]
Hello @GretaD,

everything is working well now.

Could you have a look at this pr again?

**Comment by GretaD** [comment]
Yep, all looks good now

**Comment by miaulalala** [comment]
Looking good!

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
