### PR TITLE
Fix quoting forwarded messages

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/mail/pull/6663#issuecomment-1148630058.

Regression of https://github.com/nextcloud/mail/pull/2854.

Composer.vue received a new prop `forwardFrom` that never got filled. Therefore neither reply nor forward quoting was used in Composer.vue::initBody.

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
tested and it works

**Comment by ChristophWurst** [comment]
/backport 4063d19bad9d7c08144df098cf4118c4178e95cc to stable1.13

**Pull request merged**
