### PR TITLE
Show message preview in envelope list

### PR DESCRIPTION
**Pull request by ChristophWurst**
Contributes the envelope list part of https://github.com/nextcloud/mail/issues/2579

Bildschirmfoto vom 2022-08-10 14-37-27
Bildschirmfoto vom 2022-08-10 14-36-17
Bildschirmfoto vom 2022-08-10 14-36-15

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
tested and it works

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Very nice! :)
- [x] The line-height is different between the 3 lines, there should be equal space between them. So essentially reduce the top padding/margin of the message preview a bit to match the distance between sender and subject. 
- [x] The avatar is not vertically centered with the first 2 lines (sender name and subject). And it probably looks nicer to vertically center it with the 3 lines now (sender name, subject, preview – but _not_ the tags / attachments line). Ref like the screenshot of Gmail mobile you posted: https://github.com/nextcloud/mail/issues/2579#issuecomment-582909752
- [x] The message preview gets ellipsized nicely, but the message subject doesn’t seem to (also in master though), seen by @nimishavijay 

I assume this also then goes into the thread list on the right in a separate PR?

**Comment by jancborchardt** [comment]
Looks good except the avatar is not vertically centered yet (both lines on the left are same length, both lines on right as well):
mail alignment

**Comment by ChristophWurst** [comment]
I think the problem is that around the actual avatar

Bildschirmfoto vom 2022-08-10 16-29-01

we have some bottom spacing

Bildschirmfoto vom 2022-08-10 16-28-58

although there is no margin or padding set. Ideas?

**Comment by jancborchardt** [comment]
> although there is no margin or padding set. Ideas?

Stupid but works:
`.app-content-list-item-icon { height: 40px; }`

Not sure if this issue comes from the component? It’s not there in Contacts or Talk, but not sure what they use and it seems different.

**Review by JuliaKirschenheuter — APPROVED** [review]
Works well!
I would say small css polishing can be done a bit later.

**Pull request merged**
