### PR TITLE
Bump CKEditor to 27

### PR DESCRIPTION
**Pull request by GretaD**
Signed-off-by: GretaD <gretadoci@gmail.com>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
what version of `npm` do you use?

what is left before review?

**Comment by GretaD** [comment]
> what version of `npm` do you use?
> 
6.14.4

> what is left before review?
>

me making sure that -23.657 removals is alright i didnt do smth wrong

**Comment by ChristophWurst** [comment]
I think the big diff is from npm 6 because the npm lockfile was previously written with v7 and they have switched the format

**Review by ChristophWurst — APPROVED** [review]
Looks good, didn't test

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/mail/commit/0a16e28b6f63857d11483627d4a3c65fc05a736a was better

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Pull request merged**
