### PR TITLE
Settings: reduce amount of sections

### PR DESCRIPTION
**Pull request by GVodyanov**
Fix https://github.com/nextcloud/mail/issues/9837

**Account creation**: account creation
**Appearance and accessibility**: layout, activate body search, gravatar settings, reply text position, sorting, keyboard shortcuts
**Privacy and security**: data collection consent, trusted senders, S/MIME, mailvelope
**Assistance features**: assistance features
**Mailto**: mailto

| A | B |
| - | - |
| image| Screenshot from 2024-07-17 15-51-25 |

Also:
- renamed "Keyboard" to "Keyboard shortcuts"
- added an `h6` tag to describe every setting (`h6` because anything larger would be larger than the 'NcAppSettingsSection` title)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> added an `h6` tag to describe every setting (`h6` because anything larger would be larger than the 'NcAppSettingsSection` title)

use the heading that fits semantically. we have to fix/adjust the font size instead. is the heading too small?

**Comment by GVodyanov** [comment]
> > added an `h6` tag to describe every setting (`h6` because anything larger would be larger than the 'NcAppSettingsSection` title)
> 
> use the heading that fits semantically. we have to fix/adjust the font size instead. is the heading too small?

image

Here's what it looks like when it's "correct" (an `h4` seeing as the `NcAppSettingsSection` is an `h3`)... Gonna make a PR in nextcloud vue ig

**Review by nimishavijay — CHANGES_REQUESTED** [review]
Nice! Way easier to understand now. Agreed about the heading sizes, we should use the semantically correct heading tag. Some additional comments related to mostly wording:

- [x] Wording changes:
  - [x] "Appearance and accessibility" as a heading may be misleading as it contains settings related to composing, searching, etc. We could just use the heading "General" (ref Gmail)
  - [x] "Auto tag text" --> "Mark as important"
  - [x] "Activate body search" --> "Search in body"
  - [x] "Privacy and Security" --> "Privacy and security" (no capital S)
- [x] "Keyboard shortcuts" should be its own category as that's more accessible, it can be the last category 
- [x] "Mailto" as a separate item seems a bit strange, it can just go into the general settings now that it's not related to appearance 
- [x] Order of general settings: 
  - [x] Layout
  - [x] Sorting, 
  - [x] Search in body
  - [x] Reply text position
  - [x] Gravatar
  - [x] Mailto

**Comment by ChristophWurst** [comment]
We out keyboard shortcuts into Appearance and accessibility because server has it there too.

**Comment by GVodyanov** [comment]
> Nice! Way easier to understand now. Agreed about the heading sizes, we should use the semantically correct heading tag. Some additional comments related to mostly wording:
> 
>     * [x]  Wording changes:
>       
>       * [x]  "Appearance and accessibility" as a heading may be misleading as it contains settings related to composing, searching, etc. We could just use the heading "General" (ref Gmail)
>       * [ ]  "Auto tag text" --> "Mark as important"
>       * [x]  "Activate body search" --> "Search in body"
>       * [x]  "Privacy and Security" --> "Privacy and security" (no capital S)
> 
>     * [x]  "Keyboard shortcuts" should be its own category as that's more accessible, it can be the last category
> 
>     * [x]  "Mailto" as a separate item seems a bit strange, it can just go into the general settings now that it's not related to appearance
> 
>     * [x]  Order of general settings:
>       
>       * [x]  Layout
>       * [x]  Sorting,
>       * [x]  Search in body
>       * [x]  Reply text position
>       * [x]  Gravatar
>       * [x]  Mailto

@nimishavijay Done, what do you mean by "auto tag text" though?

**Comment by ChristophWurst** [comment]
> what do you mean by "auto tag text" though?

Automatically classify importance of new email

**Comment by hamza221** [comment]
I think it was closed by mistake

**Comment by GVodyanov** [comment]
Hey @nimishavijay does this look alright?

**Comment by ChristophWurst** [comment]
@nimishavijay's suggestions are addressed. Let's get this in :+1:

**Review by ChristophWurst — APPROVED** [review]
:shipit:

**Pull request merged**
