### PR TITLE
add bountysource badge

### PR DESCRIPTION
**Pull request by ChristophWurst**
cc @jancborchardt @Gomez @jospoortvliet @oparoz

### CODE REVIEW

**Comment by ChristophWurst** [comment]
could someone enable the GitHub tool for this repo please? (edit issue footers/headers and add the 'bounty' label automatically)
@oparoz are you the org admin? https://www.bountysource.com/teams/nextcloud/members

**Comment by oparoz** [comment]
>@oparoz are you the org admin? 

Yeah, I just set that up yesterday when I saw it didn't exist.

I can't make the modifications to some repos as I think BS can't cope with a list of more than 30 projects... I'll keep you posted

**Comment by ChristophWurst** [comment]
cc @jancborchardt

**Comment by irgendwie** [comment]
LGTM :+1:

**Comment by jancborchardt** [comment]
So, time to move my money over to the new repo ;D

**Comment by jancborchardt** [comment]
@rappo @wkonkel from @bountysource: is it possible to move pledges from one project to another, or cancel them at one? We just had a major move of many repositories from an old organization to this new one, so that’s kind of a problem.

Also cc @jospoortvliet @stp-ip cause you helped with the Bountysource stuff :)

**Pull request merged**
