### PR TITLE
init.js is the main/entry module now

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes https://github.com/nextcloud/mail/issues/207.
Probably caused by https://github.com/nextcloud/mail/pull/126.

@jancborchardt @tahaalibra @nextcloud/mail please test

Steps to reproduce:
1. set up app
2. run 'make optimize-js'
3. disable debug mode
4. view app in the browser

### CODE REVIEW

**Comment by jancborchardt** [comment]
Instantly makes it work again :+1: :tada: !

However some console errors, maybe unrelated:
```
/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/385c868c-aaa0-4bc1-9c03-816b08869d18.vcf?photo:1 GET http://localhorst/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/385c868c-aaa0-4bc1-9c03-816b08869d18.vcf?photo net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/cd5a2c8d-4cbd-4c70-9ff4-52c9bb4a2d65.vcf?photo:1 GET http://localhorst/nextcloud/remote.php/dav/addressbooks/users/jan/contacts/cd5a2c8d-4cbd-4c70-9ff4-52c9bb4a2d65.vcf?photo net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
mail.min.js?v=5e2306a…:153 Uncaught TypeError: Cannot read property 'currentView' of undefined
```

**Comment by jancborchardt** [comment]
Ah yep – it breaks avatars :)

**Comment by ChristophWurst** [comment]
> mail.min.js?v=5e2306a…:153 Uncaught TypeError: Cannot read property 'currentView' of undefined

Fix is included in #90.

> Ah yep – it breaks avatars :)

They they work before? Works with current nc master here.

**Comment by jancborchardt** [comment]
Ok then let’s merge it for now cause it fixes the main issue right now. :) Maybe it’s just a checkout bug or other thing.

**Pull request merged**
