### PR TITLE
[stable2.0] Bump @nextcloud/vue to v7.0.1

### PR DESCRIPTION
**Pull request by ChristophWurst**
Backport of https://github.com/nextcloud/mail/pull/7419

### CODE REVIEW

**Comment by GretaD** [comment]
there is this bug on v7.0.1. Also, https://github.com/nextcloud/mail/pull/7419 has 7.0.0, not 7.0.1, so this is not the backport of it, right?

Screenshot from 2022-10-17 09-49-50

**Comment by ChristophWurst** [comment]
This bug only exists for .1? I thought I'd backport and switch to .1 right away in the hopes of getting the latest fixes

**Comment by GretaD** [comment]
> This bug only exists for .1? I thought I'd backport and switch to .1 right away in the hopes of getting the latest fixes

yes, its only on 7.0.1 for me. All looks good on .0

**Comment by ChristophWurst** [comment]
.0 bump done in https://github.com/nextcloud/mail/pull/7441

**Pull request merged**
