### PR TITLE
Correction of the code for the description

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Is this a fix for translations?

**Comment by Valdnet** [comment]
@ChristophWurst No. It's code improvement. Currently Transifex cannot see the current description for translation. It was probably related to the code in the file.

**Comment by ChristophWurst** [comment]
> Transifex cannot see the current description for translation

What do you mean by *description*? The text to translate?

**Comment by Valdnet** [comment]
Current text is missing: 
- Allow the app to collect data about your interactions. Based on this data, the app will adapt to your preferences. The data will only be stored locally.

 to be translated in Transifex.

**Comment by Valdnet** [comment]
I close PR.
Issues: #2987

**Pull request closed without merging**
