### PR TITLE
Document keyboard shortcuts in README.md

### PR DESCRIPTION
**Pull request by connium**
I suppose many users are not aware of the cool keyboard shortcuts the mail app offers. Therefore I added a section to the README.md describing the keyboard shortcuts.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Cool, thanks a lot.

How about using GitHub's special ``<kbd>key</kbd>`` markup to make it look like <kbd>key</kbd>? ref  https://github.com/nextcloud/server/issues/1444#issuecomment-247998136 🚀

**Comment by ChristophWurst** [comment]
nice 👍

**Comment by connium** [comment]
Great idea! Thanks for the hint. Didn't know this github markup feature.
Just changed it accordingly. Looks much nicer now.

**Comment by ChristophWurst** [comment]
Btw: you can get a free t-shirt from github/digital ocean if you submit at least four more pull requests ;-) https://twitter.com/ChristophWurst/status/780821962318815232 🎃 :octocat:

**Pull request merged**
