### PR TITLE
change the composer modal size to large

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/mail/issues/6589

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by GretaD** [comment]
I would wait for Jan's or Nimisha's approval :)

**Review by jancborchardt — CHANGES_REQUESTED** [review]
This would widen the composer window line length from an already wide ~80 characters per line to a huge ~125 characters per line.

The recommended line length is between 45 and 75 characters per line, see:
- https://en.wikipedia.org/wiki/Line_length
- https://baymard.com/blog/line-length-readability

So the composer modal should stay at normal size.

Remember our design is not governed by how much screen space there is, but by human cognition. ;)

**Comment by marcoambrosini** [comment]
@jancborchardt keep in mind that our `large` modal size is not that large. If you look at the composer on a not zoomed in page you'll see it's really really tiny. Gmail's smaller composer is tiny too but they keep the rest of the page interactive while that's deployed, while we're blocking everything else.

To give a point of reference, a size large is the same as the app settings dialog. To me this would be pretty reasonable for Mail's composer. We could also bump the size of the text in the composer to 16 to make it more readable.

reference of a "large" modal window on a 16 inch screen with recommended scaling and no zoom in the web page  
Screenshot 2022-06-17 at 13 16 44

**Comment by Bibo-Joshi** [comment]
> To give a point of reference, a size large is the same as the app settings dialog. To me this would be pretty reasonable for Mail's composer.

Personally I'm used to writing mails in full-page view such that fixing a window size seems undesirable to me. I'd like to have it at least adjustable by the user or even better provide the possibility to edit it on the right hand side as it used to be the case (preferably the default behavior for this would be a setting somewhere).

**Comment by miaulalala** [comment]
I personally have to agree with Marco and Bibo-Joshi. The current modal window is super small. Can we keep the line lenght and increase font size while making the modal bigger, and possibly add an overlay? It feels fiddly.

**Comment by marcoambrosini** [comment]
Oh btw @jancborchardt I just noticed that the composer uses 13px as font size. Is there any reason for that? 
If we bump it to 15px and use the large modal size I think we'd have a reasonable line length.

**Comment by nimishavijay** [comment]
Also agreed, if the composer was a popup composer on the right like in Gmail then it makes sense to keep it small, but seems to me that there is no use of keeping a modal-type focused composer which is so small. If you add attachments that's even lesser of the body text that's not visible. I think it's a good idea to increase the size, and possibly the font size as well :)

**Comment by szaimen** [comment]
I would but where do I adjust that?

**Comment by ChristophWurst** [comment]
Finish or discard?

**Comment by szaimen** [comment]
> Finish or discard?

I asked a question in the comment above :P

**Comment by ChristophWurst** [comment]
@jancborchardt

**Comment by ChristophWurst** [comment]
@jancborchardt please have a look. I think this still makes sense but I'll let you decide.

**Comment by jancborchardt** [comment]
@ChristophWurst The feedback I left in https://github.com/nextcloud/mail/pull/6717#issuecomment-1234559544 still has to be addressed though?

**Comment by ChristophWurst** [comment]
@GretaD 

1) Change ckeditor font size to 15px
2) Enter 80 wide characters and see if the line breaks with the current modal size
3) if not: done
4) if it breaks: increase modal size

**Comment by GretaD** [comment]
i did 2 scenarios, which one should we consider?

Screenshot from 2023-09-29 17-30-12

**Comment by miaulalala** [comment]
This is the big gmail window:

image

The main benefits here are:

1) all the content is hidden by a light grey overlay plus the size of the modal. My eyes do not get caught up on the number of unread emails in my inboxes or any notifications, leaving me free to focus on the task that I want to do **right now** - composing an email.

2) the area I can (accidentally) click on to close the modal is small but still there, making the whole UI feel more stable and less "accidentally closing my email even though I wasn't done" -  prone even though the mechanism is the same as ours.

3) The line lenght takes the whole page but it doesn't matter as I will use line breaks and new paraghraphs to structure my email anyway. For **writing**, the max amount of characters is thus irrelevant.

**Comment by jancborchardt** [comment]
@GretaD you can test with a variety of 80-character lines (not only 2) and increase the modal size/width accordingly, as @ChristophWurst said?

@miaulalala again, the Gmail large window is not standard, we are going in circles here. If we would make it so wide by default (and as the only option) it would severely hamper legibility.

**Comment by GretaD** [comment]
> @GretaD you can test with a variety of 80-character lines (not only 2) and increase the modal size/width accordingly, as @ChristophWurst said?
> 
the text size is 15px.
see:
Screenshot from 2023-10-05 10-30-44

I used: https://charactercounter.de/ to count characters. Spaces are considered characters too in the example above.

**Comment by miaulalala** [comment]
> @miaulalala again, the Gmail large window is not standard, we are going in circles here. If we would make it so wide by default (and as the only option) it would severely hamper legibility.

I disagree that it's not standard. GMX has a massive input field, if oldschool. So does Yahoo Mail. Outlook online is smaller but still more than 80 chars in a line. Clients like Thunderbird do not limit line length either. 

The fiddlyness of the modal we currently have is seriously annoying. And again, legibility is not really an issue in a window that will be structured by my own input - unlike a window that has the structure determined from the other side.

**Comment by ChristophWurst** [comment]
Closing because we will do https://github.com/nextcloud/mail/issues/9100 instead.

**Pull request closed without merging**
