### PR TITLE
Migrate PEAR Horde packages to Bytestream packages

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/5136

Once the Horde packages are migrated to packagist we can jump back to the "original". Let's send patches to both versions for now.

To do
- [x] https://github.com/nextcloud/mail/pull/6342

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@bytestream thanks _a lot_ for your packages. The migration experience was super smooth. I'll send patches for the deprecation notices soon :v:

**Review by st3iny — APPROVED** [review]
Looks good and works so far. When can we release/merge this? Did NC drop PHP 7.3 already?

**Comment by ChristophWurst** [comment]
> Did NC drop PHP 7.3 already?

Only with Nextcloud 24+

**Comment by bytestream** [comment]
For what it's worth, I don't _think_ I actually introduced any PHP 7.4 specific code. You could send PR to https://packagist.org/?query=bytestream%20horde which loosens the PHP requirement to `^7.3 || ^8.0` and updates the GitHub workflow

**Pull request merged**
