### PR TITLE
Delete recipient records when deleting email

### PR DESCRIPTION
**Pull request by miaulalala**
Should help with issues such as #4412 where orphaned records and InnoDB bugs combine to show wrong recipients.

### CODE REVIEW

**Comment by StCyr** [comment]
I don't know what this PR is expected to do 🤔

**Comment by ChristophWurst** [comment]
> I don't know what this PR is expected to do thinking

Delete recipients of a message right away. On master they are expected to be cleaned up by the background clean-up. But as we found out in the ticket the database might insert new messages with the ID of the deleted messages before the cleanup happens.

**Review by st3iny — APPROVED** [review]
Just tested both methods and they work as intended. The failing static code check seems to be unrelated.

**Review by ChristophWurst — APPROVED** [review]
Code looks good!

**Pull request merged**
