### PR TITLE
Feature: print email

### LINKED ISSUE #579: Print stylesheet [$65]
Occasionally a user needs to print an email. CTRL+P will print the page, not the message. Adding a div to the messages-list-item template and some js tied to an action will not address CTRL+P but im not sure if everyone would want to override the browser shortcut anyway.  

There are some tricks in CSS To make the output in the mail-message-container cleaner ( reply attachment and forward buttons for example ) for printing but putting the print button in the message list item would at least prevent that particular control from being printed. 

Alternatively I suppose it would be even better in some cases to pull the message from the mail server again for printing purposes to avoid printing all the extraneous information mentioned above, and in the event someone entered text into the reply but had not sent it yet -- we might not want to print message text that has never been sent. 

Other considerations are whether we want the print preview dialog allowing the user to select a printer or to blindly print to whatever is default.   

Any thoughts on this?  I can probably contribute to this one if its not already in progress or part of NCMail13 but Id like to hear some input from others. 

thx
-d

<bountysource-plugin>

---
There is a **[$65 open bounty](https://www.bountysource.com/issues/50806693-print-stylesheet?utm_campaign=plugin&utm_content=tracker%2F44154351&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44154351&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pierlon**
Fixes #579

### CODE REVIEW

**Comment by tevon456** [comment]
both reviewers are offline right now

**Comment by ChristophWurst** [comment]
Awesome. Will review this soonish.

cc @skjnldsv @jancborchardt for the styling aspects of this patch.

**Comment by pierlon** [comment]
@ChristophWurst thanks.

**Comment by skjnldsv** [comment]
@ChristophWurst  seems ok at first glance, but since we're just stripping the design out of everything not related to the mail, does it really matter? :p 
It's just displaying the email and printing in the end?  :)

**Comment by ChristophWurst** [comment]
> @ChristophWurst seems ok at first glance, but since we're just stripping the design out of everything not related to the mail, does it really matter? :p
> It's just displaying the email and printing in the end? :)

:man_shrugging: :see_no_evil:

**Comment by pierlon** [comment]
@ChristophWurst made changes as requested 😄

**Comment by jancborchardt** [comment]
@ChristophWurst regarding placement of the print button, it might be time to add a "Reply all" button on the top right, with a 3-dot menu next to it containing Reply, Forward, Favorite, Move, Print and Delete. Also that we have this stuff working on mobile. What do you think?

**Comment by ChristophWurst** [comment]
> @ChristophWurst regarding placement of the print button, it might be time to add a "Reply all" button on the top right, with a 3-dot menu next to it containing Reply, Forward, Favorite, Move, Print and Delete. Also that we have this stuff working on mobile. What do you think?

Sounds good. Any chance you have some time to help us with the design?

**Comment by jancborchardt** [comment]
@ChristophWurst yes, for sure! :) The main work however is to put the actions in the popover menu as described in the design guidelines: https://docs.nextcloud.com/server/14/developer_manual/design/popovermenu.html

And left of it simply a `<button class="primary">Reply all</button>`, which would also focus on the reply form on the bottom. And both elements should be in the header element.

I can then help with the exact layout, and also the behavior on mobile. Is that what you mean?

**Comment by ChristophWurst** [comment]
Closing as this needs a bit of rework for the Vue migration and I have not received any feedback within three weeks (https://github.com/nextcloud/mail/pull/1019#pullrequestreview-145537636).

**Pull request closed without merging**
