### PR TITLE
Adds the ckeditor list plugin

### PR DESCRIPTION
**Pull request by StCyr**
I often find myself in need of this feature 

Signed-off-by: Cyrille Bollu <cyr.debian@bollu.be>

### CODE REVIEW

**Comment by StCyr** [comment]
BTW, ckeditor's plugins seem to have changed quite a bit these days. Maybe time to review what plugins to install and enable?

**Comment by ChristophWurst** [comment]
> BTW, ckeditor's plugins seem to have changed quite a bit these days. Maybe time to review what plugins to install and enable?

What changed specifically? In the beginning I wanted to only enable a few features and gradually "allow" more. We can discuss more but let's try to add the slowly so we know if something doesn't work as expected.

**Review by ChristophWurst — APPROVED** [review]
Something's not right with the package lock. Please reset that one file, do a rebase and install the new dependency again

rest looks fine :)

**Comment by StCyr** [comment]
> What changed specifically? In the beginning I wanted to only enable a few features and gradually "allow" more. We can discuss more but let's try to add the slowly so we know if something doesn't work as expected.

Well, here's the toolbar with the addition of the list plugin:

image

And, here's the toolbar of the default balloon build:

image

We are almost there 😄

**Comment by ChristophWurst** [comment]
I meant *what changed in the ckeditor plugins*? :wink: 

or did you mean the ones that we enable changed? It sounded like ckeditor changed their API or so.

**Review by ChristophWurst — APPROVED** [review]
Fixed the lockfile for CI

**Comment by StCyr** [comment]
> 
> 
> I meant _what changed in the ckeditor plugins_? 😉
> 
> or did you mean the ones that we enable changed? It sounded like ckeditor changed their API or so.

No, nothing special has changed, sorry: It's just me that got confused with the sheer number of plugins available (do you know the autosave plugin?) and the difference between builds and sources,...

Thanks for updating my commit 👍

**Pull request merged**
