### PR TITLE
fix translation of "delete 1 thread" in German

### PR DESCRIPTION
**Pull request by MeiKatz**
Signed-off-by: MeiKatz <gregor.mitzka@gmail.com>

### CODE REVIEW

**Comment by st3iny** [comment]
Please update translations at [Transifex](https://www.transifex.com/nextcloud/nextcloud/). Local changes will be overwritten by the bot.

**Comment by MeiKatz** [comment]
> Please update translations at [Transifex](https://www.transifex.com/nextcloud/nextcloud/). Local changes will be overwritten by the bot.

Thanks! I had a look on the translation in Transifex and there it is already fixed. Maybe the translation files should be updated?

**Comment by st3iny** [comment]
> Thanks! I had a look on the translation in Transifex and there it is already fixed. Maybe the translation files should be updated?

The bot may take some time to update the translation because it only runs at most once a day. If this issue persists we might have to look into it.

**Comment by MeiKatz** [comment]
> > Thanks! I had a look on the translation in Transifex and there it is already fixed. Maybe the translation files should be updated?
> 
> The bot may take some time to update the translation because it only runs at most once a day. If this issue persists we might have to look into it.

It would be a comical coincidence if there two persons at the same time who update exactly the same translation. Therefore I guess that the bot did not run for some time. But maybe it is really a coincidence.

**Pull request closed without merging**
