### PR TITLE
fix reply to sender only

### LINKED ISSUE #8621: Reply to sender does not work
### Steps to reproduce

1. Receive an email addressed to more than one recipient. 
2. Click on th 3dot menu. 
3. Click on "reply to sender". 

### Expected behavior

Reply only to sender. 

### Actual behavior

Nada. 

### Mail app version

3.2.3

### Mailserver or service

Imap (dovecot) 

### Operating system

FreeBSD 13.1

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
fixes  #8621

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
:facepalm:

**Review by ChristophWurst — APPROVED** [review]
Leftover of https://github.com/nextcloud/mail/pull/6388

**Review by st3iny — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@GretaD backports please

**Pull request merged**
