### PR TITLE
Fix displaying and notifications for messages with no sender

### LINKED ISSUE #911: this.model.get(...)[0] is undefined.
## Steps to reproduce
1. Log on to nextcloud, click on the mail menu item
2. Select a folder containing a null email

## Expected behaviour
The emails in the folder are listed

## Actual behaviour
An error message appears on top inviting me to file a bug. The list of mails is not displayed. 

## Error
The logs in the backend do not display an error (in debug it says: "loading messages of folder <VHJhc2g=>"). I will try not to forget to check the serverlogs tonight.

Automatically added by the link from within Nextcloud:
```
this.model.get(...)[0] is undefined
onRender@https://xyz.mydomain.tld/apps/mail/js/build/build.js:225:1364
f@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:84546
triggerMethod@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:96256
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:105717
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
addChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:115039
_addChild@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:114690
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
v.forEach@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:135421
_showCollection@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:112827
_renderChildren@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:112493
renderChildren@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:128504
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:128335
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
show@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:98154
showChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:104088
onRender@https://xyz.mydomain.tld/apps/mail/js/build/build.js:283:9339
f@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:84546
triggerMethod@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:96256
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:105717
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
show@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:98154
showChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:104088
showFolderContent@https://xyz.mydomain.tld/apps/mail/js/build/build.js:283:15062
v@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:155118
g@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:154809
h@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:152755
s</o.Backbone</u.trigger@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:154702
l/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:68:18683

```

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/930.
Fixes #911.

Note: I had no data to properly test this. I *hope* this doesn't :boom: on existing data. I used search to identify spots where we blindly assume there's more than one element in `from`.

cc @iamdoubz @itchytm @e-alfred @akaro if anybody has a setup to reproduce the issue, please let me know and I'll provide you with an app archive to test the patch. Thanks!

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@iamdoubz @itchytm @e-alfred @akaro :ping_pong:

**Comment by omegasupreme3** [comment]
I can test this on my setup, because the current state it will constantly reproduce this error when opening the "sent items" folder.

**Comment by omegasupreme3** [comment]
Sorry for the additional post, but maybe you missed the update of my original post. If I get a latest from the master branch, does it include the fix to test?

**Comment by ChristophWurst** [comment]
> Sorry for the additional post, but maybe you missed the update of my original post. If I get a latest from the master branch, does it include the fix to test?

No, please use this package here to test: 
[mail.tar.gz](https://github.com/nextcloud/mail/files/2301156/mail.tar.gz)

Thank you :rocket:

**Comment by iamdoubz** [comment]
[Using this](https://github.com/nextcloud/mail/pull/1031#issuecomment-414196832), I am now able to see inbox messages! Thank you very much for the quick fix and for the support. I will review the changes.

**Comment by ChristophWurst** [comment]
Thanks for testing and reviewing this!

**Comment by ChristophWurst** [comment]
- [ ] Blocked by #1046 

(this will be released with Mail v0.11.0)

**Comment by omegasupreme3** [comment]
As holiday season is over I didn't have the time to test this yet. I focus on doing this coming weekend.

**Pull request merged**
