### PR TITLE
chore(deps): Bump ckeditor5 36.0.1

### PR DESCRIPTION
**Pull request by GretaD**
i cannot push here #8018 so opened a new pr

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Is https://github.com/nextcloud/mail/pull/7960#issuecomment-1408730127 resolved now?

**Comment by GretaD** [comment]
> 

no :(, but at least you have a working dev env

**Comment by ChristophWurst** [comment]
Mine also works with the current version?!

**Comment by GretaD** [comment]
> Mine also works with the current version?!

thats true, i was on https://github.com/nextcloud/mail/pull/8018 branch not on main when i saw the error, i thought i was on main.

**Comment by ChristophWurst** [comment]
conflicts

**Pull request closed without merging**
