### PR TITLE
Drop custom app list active override

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires https://github.com/nextcloud/nextcloud-vue/pull/3147
- [x] Requires https://github.com/nextcloud/nextcloud-vue/pull/3155
- [x] Requires https://github.com/nextcloud/mail/pull/7158

Fixes https://github.com/nextcloud/mail/issues/7098
Supersedes https://github.com/nextcloud/mail/pull/7078

### CODE REVIEW

**Comment by GretaD** [comment]
this should be ready for review because on main we have nc/vuebeta6

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3155/commits/cac98fe4dc76c746852212b1a81c01c9e3aa19f9 is unreleased. We'll need a beta7.

**Review by miaulalala — APPROVED** [review]

**Comment by miaulalala** [comment]
:elephant:

**Pull request merged**
