### PR TITLE
Adds clipboard support to Mail and adds an action to RecipientBubbles to copy their email address to the clipboard.

### PR DESCRIPTION
**Pull request by StCyr**
Fixes https://github.com/nextcloud/mail/issues/4481

Signed-off-by: Cyrille Bollu <cyr.debian@bollu.be>

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
Thanks for the PR. It works fine.

However, I have 2 small remarks:
1. The package lock is dirty. Running `npm install` on my machine results in a changed file. Please run the command and commit all missing changes of the lock file.
2. There is a line break in the text of the new button because the popover is constrained to a max width of 500px. If you're not sure how to fix that I'd be willing to take over. 

Screenshot 2022-01-21 at 10-57-00 Mail - Nextcloud

**Comment by StCyr** [comment]
> Thanks for the PR. It works fine.
> 
> However, I have 2 small remarks:
> 
>     1. The package lock is dirty. Running `npm install` on my machine results in a changed file. Please run the command and commit all missing changes of the lock file.

Must be because I'm running version 12 of nodejs:

>cyrille@vm-cyrille-debian:/var/www/nextcloud/apps/mail$ npm install
>npm WARN EBADENGINE Unsupported engine {
>npm WARN EBADENGINE   package: 'nextcloud-mail@1.11.0',
>npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=7.0.0' },
>npm WARN EBADENGINE   current: { node: 'v12.22.5', npm: '7.5.2' }
>npm WARN EBADENGINE }

I can't do much about it atm since I'm running Debian, and nodejs is in version 12 in all realeases (except "experimental" which I'm not going to install)

> 
>     2. There is a line break in the text of the new button because the popover is constrained to a max width of 500px. If you're not sure how to fix that I'd be willing to take over.
> 

Indeed, I'm not sure how to fix it. But I guess I should be able to figure it out 😉 

> 
> Screenshot 2022-01-21 at 10-57-00 Mail - Nextcloud

**Comment by StCyr** [comment]
> 2\. There is a line break in the text of the new button because the popover is constrained to a max width of 500px. If you're not sure how to fix that I'd be willing to take over.

I've fixed it by applying a `display: flex` property to the various popover entries. It looks fine on my PC.

**Review by st3iny — APPROVED** [review]
Tested and works. The line break issue is fixed now.

I pushed missing changes from the lock as we don't support Node v12.

**Pull request merged**
