### PR TITLE
Support iMIP requests

### PR DESCRIPTION
**Pull request by miaulalala**
## To Do

Server - see https://github.com/nextcloud/server/pull/33001

### Backend:
- [x] Parse Data for frontend in IMAPMessage
- [x] Send the parsed data to the frontend

### Frontend:
- [x] Display REQUEST in frontend like discussed in https://github.com/nextcloud/mail/issues/160#issuecomment-1064010470
- [x] Display REPLY messages appropriately, the design is still unclear but could be anything from a oneliner to a design that emulates the above (if the message doesn't contain any text at all, some calendars will show text)
- [x] Display CANCEL

### Still unclear:
- Recurrences: What to do when a processing fails and a calendar isn't updated?

### Invitation
image

### Update (e.g. participant accepted)
image

### Cancelled
image

### CODE REVIEW

**Comment by miaulalala** [comment]
Example of a REPLY ics when clicking the integrated "accept" button in gmail:

```text
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
DTSTART:20220623T200015Z
DTEND:20220623T210015Z
DTSTAMP:20220623T211813Z
ORGANIZER;CN=admin:mailto:xxxxxxx@gmx.net
UID:0043c2ad-a2c9-4ac8-9c36-c9f1d36a5d54
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=xxxxxxx@gmail.com;X-NUM-GUESTS=0:mailto:xxxxxxx@gmail.com
CREATED:20220623T194731Z
DESCRIPTION:
LAST-MODIFIED:20220623T211813Z
LOCATION:
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:Test
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

```

Interesting to note there will only ever be one ATTENDEE in such a REPLY.

**Comment by miaulalala** [comment]
> @miaulalala I tried to test this with our own invitation mails and realized that they don't work because we are attaching our iMIP data with `Content-Disposition: attachment`. Currently, the new mail backend only picks up iMIP data without a disposition (check the if conditions + return statements inside `getPart()`, especially the first one).

I'm confused, I thought my additional code works fine for that? I have the check on the type first 

https://github.com/nextcloud/mail/blob/0a64080f3401ffc4a53b5920550d0f64795f91f5/lib/Model/IMAPMessage.php#L448

and inside that condition I check for the attachment:

https://github.com/nextcloud/mail/blob/0a64080f3401ffc4a53b5920550d0f64795f91f5/lib/Model/IMAPMessage.php#L449

then for the method (because we could have received a regular ical attachment):

https://github.com/nextcloud/mail/blob/0a64080f3401ffc4a53b5920550d0f64795f91f5/lib/Model/IMAPMessage.php#L462

but irrespective of the `VACALENDAR` being an attachment or not, it should work fine?

> Another issue is that Nextcloud attaches the ics data in base64 encoding. We either have to change this and attach an encoded and an unencoded version (like e.g. Google Calendar does it) or we have to decode base64 data in the new mail backend.

Data is already decoded as far as I can tell: 

https://github.com/nextcloud/mail/blob/0a64080f3401ffc4a53b5920550d0f64795f91f5/lib/Model/IMAPMessage.php#L635-L658

> 
> Do you know what the standard says about this (`Content-Disposition` and `Content-Transfer-Encoding`)?
> 

Encoded is mentioned in the standard, as is encrypted data even (although I haven't seen it in the wild yet). Base64 is definitely compliant for Content-Transfer-Encoding.

**Comment by st3iny** [comment]
Note to reviewers: This is only about displaying iMIP messages. The buttons are not supposed to work (yet).

**Comment by ChristophWurst** [comment]
> Note to reviewers: This is only about displaying iMIP messages. The buttons are not supposed to work (yet).

Let's drop them from this PR then so `main` stays releasable

**Comment by st3iny** [comment]
> > Note to reviewers: This is only about displaying iMIP messages. The buttons are not supposed to work (yet).
> 
> Let's drop them from this PR then so `main` stays releasable

Done

**Comment by kesselb** [comment]
```diff
Index: lib/Model/IMAPMessage.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/Model/IMAPMessage.php b/lib/Model/IMAPMessage.php
--- a/lib/Model/IMAPMessage.php	(revision f030aec06ea22037d4cbe4fee43e9aa28c028a9f)
+++ b/lib/Model/IMAPMessage.php	(date 1657640660009)
@@ -406,7 +406,7 @@
 		$allContentTypeParameters = $p->getAllContentTypeParameters();
 		if ($p->getType() === 'text/calendar') {
 			// Also handle event data like a regular attachment
-			if ($p->getDisposition() === 'attachment') {
+//			if ($p->getDisposition() === 'attachment') {
 				$this->attachments[] = [
 					'id' => $p->getMimeId(),
 					'messageId' => $this->messageId,
@@ -416,7 +416,7 @@
 					'cid' => $p->getContentId(),
 					'disposition' => $p->getDisposition()
 				];
-			}
+//			}
 
 			// return if this is a true attachment
 			// the method parameter determines if this is a iMIP message


```
| Before | After |
| --- | --- |
| image | image |

If we don't check `$p->getDisposition() === 'attachment'` it's possible to download the attachment for outlook too. 

image

Downside is that for other invitations two attachments are shown. Thunderbird seems to use the following logic: Show the invitation as attachment when a file name is set. 

```diff
Index: lib/Model/IMAPMessage.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/Model/IMAPMessage.php b/lib/Model/IMAPMessage.php
--- a/lib/Model/IMAPMessage.php	(revision f030aec06ea22037d4cbe4fee43e9aa28c028a9f)
+++ b/lib/Model/IMAPMessage.php	(date 1657641289322)
@@ -406,11 +406,12 @@
 		$allContentTypeParameters = $p->getAllContentTypeParameters();
 		if ($p->getType() === 'text/calendar') {
 			// Also handle event data like a regular attachment
-			if ($p->getDisposition() === 'attachment') {
+			$attachmentName = $p->getName();
+			if ($attachmentName !== null) {
 				$this->attachments[] = [
 					'id' => $p->getMimeId(),
 					'messageId' => $this->messageId,
-					'fileName' => $p->getName() ?? 'calendar.ics',
+					'fileName' => $attachmentName,
 					'mime' => $p->getType(),
 					'size' => $p->getBytes(),
 					'cid' => $p->getContentId(),
```

With this patch I can download the Outlook invitation as attachment. For a Google invitation only one attachment is shown. 


Invitation from Outlook: 
```
Content-Type: text/calendar;method=REQUEST;
	charset="US-ASCII";name="meeting.ics"
Content-transfer-encoding: 7bit
```

Invitation from Google:
```
Content-Type: text/calendar; charset="UTF-8"; method=REQUEST
Content-Transfer-Encoding: 7bit
```
```
Content-Type: application/ics; name="invite.ics"
Content-Disposition: attachment; filename="invite.ics"
Content-Transfer-Encoding: base64
```

The difference is that Google include a second version of the invitation (with a different content type). 

I think we should allow the user to download the invitation from Outlook. I don't have a strong opinion about the second point (show one or two attachment). Roundcube for example show's two attachments for a Google invitation.

**Comment by miaulalala** [comment]
Implemented your suggestions @kesselb, I think it's a good way to provide operability for Outlook. Just wondering if there is ever a case where the filename is not set.

**Comment by kesselb** [comment]
> Just wondering if there is ever a case where the filename is not set.

```
Content-Type: text/calendar; charset="UTF-8"; method=REQUEST
Content-Transfer-Encoding: 7bit
```

Here ;) From a Google Calendar invitation. It's the part we read to show the scheduling data. The user will download the other version (base64 encoded).

**Review by kesselb — APPROVED** [review]

**Comment by Luncheon3462** [comment]
@ChristophWurst @miaulalala @st3iny snappymail plug-in for nextcloud handles this perfectly. I’m not a coder but if the MIME is the same, and snappymail works as needed, can code be reused?

Snappymail is Rainloop fork by @the-djmaze. https://github.com/the-djmaze/snappymail

**Comment by Luncheon3462** [comment]
@ChristophWurst @miaulalala @st3iny snappymail plug-in for nextcloud handles this perfectly. I’m not a coder but if the MIME is the same, and snappymail works as needed, can code be reused?

Snappymail is Rainloop fork by @the-djmaze. https://github.com/the-djmaze/snappymail

**Comment by the-djmaze** [comment]
@Luncheon3462 

https://github.com/the-djmaze/snappymail/blob/fffc04499875531bd3dd626d01baaf7a86452cd3/plugins/nextcloud/js/message.js#L111-L179

**Pull request merged**
