### PR TITLE
Vue

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires https://github.com/nextcloud/mail/projects/4

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@nextcloud/mail please let me know *when* you're okay with the integration of this rework branch. With the exception of the account settings (which, frankly, were pretty much unusable before) we're pretty much feature complete with the old version *I think*: https://github.com/nextcloud/mail/projects/4

**Comment by LEDfan** [comment]
@ChristophWurst seems to work already very well :+1: must have been a lot of work!
Overall I don't see broken things, however some small things I encountered when testing in a fresh installation: 
 - after adding the account, the account is displayed twice in the sidebar, as soon as you reload it's fixed
screenshot_2018-12-15 e-mail - nextcloud 
 - had the same with messages
 - there is a lot of whitespace between message and the form to reply:
selection_999 023
 - also the forward button seems a bit weir placed
 - if I click first on the account name (then get the TODO warning) and then on "Inbox" the "loading accounts" appears and my account appears twice again
 - really nitpicking: the "shortcuts" button doesn't look like a button and the view with shortcuts likes some padding I guess:
selection_999 024

I guess it's fine to merge and fix things, but I'm not really a Mail app developer.  I'll re-try the app when you release a beta (or earlier :smile: )

**Comment by ChristophWurst** [comment]
> @ChristophWurst seems to work already very well +1 must have been a lot of work!
> Overall I don't see broken things, however some small things I encountered when testing in a fresh installation

Thanks a lot for your feedback :raised_hands: 

The work was okay-ish. It took a bit of time but I also wasn't focusing on it a 100% for the last few weeks/months but just when time allowed, so this is quite okay :)

**Comment by ChristophWurst** [comment]
Today is the day, @nextcloud/mail. I take your lack of feedback as either "don't care", "no objections" or "we fully trust you" :wink: 

This will also put a bit more pressure on me having new bugs on master so let's hope I will release the 0.12 after my christmas vacation.

**Comment by ChristophWurst** [comment]
One feature that will be dropped for the time being is drag-and-drop. I simply couldn't get it to work with Vue and to be honest it wasn't the smoothest experience before either and not discoverable so I can live with that.

**Comment by jancborchardt** [comment]
Some feedback, not sure if it’s related to the rewrite or generally:
- [ ] The "from" selector has this extra arrow which is not needed (background is enough)
   mail from selector
- [ ] The "to" elements are not left-aligned with "from" and Subject, too far to left. Also don’t have the "to" label anymore
   mail to align
- [ ] If I reply to a mail sent to me, my own email address is in the "to" field again
- [ ] The menu says "Seen" which is confusing. Should be "Mark unread" if it’s read, and "Mark read" if the mail is unread:
   mail seen



- [ ] Some mails have this strange code stuff on the top and bottom (see @skjnldsv’s recent mails for example):
```
--Q0iKeM0xJGawfT3eP9mlXvmFLnd9pMDe0
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable
```

- [ ] Downloading attachment causes server error:
```

Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 127.0.0.1
    Request ID: LAT2nELOvel6NysK4LuI
    Type: TypeError
    Code: 0
    Message: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in /home/jan/nextcloud/apps/mail/lib/Controller/MessagesController.php on line 257
    File: /home/jan/nextcloud/apps/mail/lib/Http/AttachmentDownloadResponse.php
    Line: 42


Trace

#0 /home/jan/nextcloud/apps/mail/lib/Controller/MessagesController.php(257): OCA\Mail\Http\AttachmentDownloadResponse->__construct('--oSV0i4SqRoUxp...', NULL, 'application/oct...')
#1 /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\Mail\Controller\MessagesController->downloadAttachment(2, 'SU5CT1g=', 10331, 1)
#2 /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'downloadAttachm...')
#3 /home/jan/nextcloud/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'downloadAttachm...')
#4 /home/jan/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Mail\\Contro...', 'downloadAttachm...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#5 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#6 /home/jan/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#7 /home/jan/nextcloud/lib/base.php(987): OC\Route\Router->match('/apps/mail/api/...')
#8 /home/jan/nextcloud/index.php(42): OC::handleRequest()
#9 {main}

```

**Comment by skjnldsv** [comment]
> * [ ]  The "from" selector has this extra arrow which is not needed (background is enough)

Because the last fixes on the vue components are not out yet :)
It will be fixed automatically there once released ;)

**Comment by ChristophWurst** [comment]
Thank you for the feedback.

Please open tickets for these minor issues and assign the 0.12 milestone. I will address all these regressions in follow-up PRs.

**Comment by ChristophWurst** [comment]
Also @LEDfan please file that as new tickets and I will have a look. Thanks a lot :v:

**Comment by MorrisJobke** [comment]
@ChristophWurst BTW: This one caused the transifex sync to break because the `build/extractTranslations.php` doesn't work anymore because the folder `js/template` is not there anymore. Let me fix that.

**Comment by MorrisJobke** [comment]
> @ChristophWurst BTW: This one caused the transifex sync to break because the `build/translation-extractor.php` doesn't work anymore because the folder `js/template` is not there anymore. Let me fix that.

Fixed the sync job in the meantime.

**Pull request merged**
