### PR TITLE
remove subject autocompletion

### PR DESCRIPTION
**Pull request by jancborchardt**
Has been annoying me for some time now. :)

Please review @nextcloud/mail, you can see it when composing a new mail.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
👍 thanks

**Comment by jancborchardt** [comment]
@skjnldsv :D anything else which annoys you a lot about the Mail app and I can fix?

**Comment by skjnldsv** [comment]
EHeh, I don't use it as much as I would want to! But the last long batch of PR improved the app a LOT!
I don't have really something in mind, but If I find something new, I would probably make a pr for it :p

**Comment by jancborchardt** [comment]
@skjnldsv great to hear! :) And yes, if you find something just go for it. And pull request reviews are always very much appreciated!

**Pull request merged**
