### PR TITLE
Store special mailboxes as preference of the account

### PR DESCRIPTION
**Pull request by ChristophWurst**
… instead of using a fragile autodetection every time we need one of
those. We will still try to auto-detect the mailboxes but the users will
have to option to change the destinations.

Todo
- [x] Adjust db schema
- [x] Move autodetection to the ~~account setup~~ mailbox sync
- [x] Extend settings UI for the new attributes ~~(requires https://github.com/nextcloud/mail/pull/3569)~~
- [x] Add check (e.g. for message sending) that a special mailbox is set

Follow-up tasks
- ~~Better handling of mailboxes deleted in other clients~~ that should actually be handled already

Fixes https://github.com/nextcloud/mail/issues/2035

### CODE REVIEW

**Comment by ChristophWurst** [comment]
cc @getriebesand @palto42 @beccon4 it's ready :)

**Review by st3iny — APPROVED** [review]

**Comment by st3iny** [comment]
I tested it on my local instance. Only skimmed through the diff.

The icons of the selected special mailboxes are not adjusted. That should be addressed in a follow up.

**Review by GretaD — APPROVED** [review]
niceee, the design we will fix it in a different PR

**Comment by ChristophWurst** [comment]
> The icons of the selected special mailboxes are not adjusted. That should be addressed in a follow up.

I tried to summarize it at https://github.com/nextcloud/mail/issues/3917

Btw this PR now already updates the navigation to show the user-picked special mailboxes in the collapsed state. So as you change the drafts/sent/trash mailbox preference, the navigation will update instantly :)

**Pull request merged**
