### PR TITLE
Enhanced doc

### PR DESCRIPTION
**Pull request by ChristophWurst**
Documents https://github.com/nextcloud/mail/pull/28
Fixes https://github.com/nextcloud/mail/issues/543, https://github.com/nextcloud/mail/issues/536#issuecomment-330537927

### CODE REVIEW

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/tree/doc/enhanced-doc for a preview of what it will look like :)

**Comment by jancborchardt** [comment]
Good point to move the advanced stuff out of the readme to keep it a bit cleaner. :) I would however keep the sections Installation, Developer setup info and Keyboard shortcuts. As that is the essential info and should be directly visible – the Readme is some kind of a landing page after all.

Advanced stuff like resetting, improving, further configuration etc can go in an »Advanced configuration« document I’d say.

**Comment by ChristophWurst** [comment]
> Installation, Developer

IMO those actually *are* advanced topics. Usually people shouldn't have to know about the repo at all, as they install the app comfortably via the app store. They will only look for code on GitHub if they've found a bug, have questions/requests or want to contribute. The updatd readme would even list where to find what ;)

**Comment by jancborchardt** [comment]
> They will only look for code on GitHub if they've found a bug, have questions/requests or want to contribute.

Ok, but then the developer setup instructions should be in the readme. :) The other things (install, keyboard shortcuts) can stay out.

**Comment by ChristophWurst** [comment]
> Ok, but then the developer setup instructions should be in the readme still. :) The other things (install, keyboard shortcuts) can stay out. It’s very important to get people involved that the dead simple developer setup is immediately visible.

Done

**Comment by ChristophWurst** [comment]
> Done

Apparently that was the only objection by @jancborchardt, thus I'm merging this PR now that its resolved.

**Comment by ChristophWurst** [comment]
> Damn right that was my only objection ;)

**Pull request merged**
