### PR TITLE
fallback for incorrectly advertised SORT capability

### PR DESCRIPTION
**Pull request by MZellhofer**
See https://github.com/nextcloud/mail/issues/50: Mailserver might advertise SORT capability but internally reject SORT. In this case try again without SORT.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
thanks for fixing this so quickly @MZellhofer :rocket: 

@zeugmatis could you please test this patch with your setup, too? Thanks.

**Comment by ChristophWurst** [comment]
@MZellhofer is your git configured correctly? Apparently GitHub shows different avatars for your user and for your commits

**Comment by ChristophWurst** [comment]
Oh, you commited with a different email address

**Comment by MZellhofer** [comment]
Ah damn - different Notebook tonight. Do you want me to change the email address in the commit?

**Comment by zeugmatis** [comment]
Tested and confirmed to fix here!  👍

**Comment by ChristophWurst** [comment]
:+1: thanks!

**Pull request merged**
