### PR TITLE
Restyle envelope view

### PR DESCRIPTION
**Pull request by GVodyanov**
See https://github.com/nextcloud-libraries/nextcloud-vue/pull/5871, this is just adjusting mail for the real party down at Nextcloud vue

### CODE REVIEW

**Comment by GVodyanov** [comment]
Right so now I have moved all the new styling to the `EnvelopeSkeleton.vue` component, rendering the Nextcloud vue PR no longer needed. `EnvelopeSkeleton` is still basically `NcListItem`, but with some unnecessary stuff cut out and a class structure slightly more relevant for mail. I also shifted all the CSS around as there were lots of duplicate selectors in `NcListItem`, hopefully what is here will now be easier to understand.

| Normal View | Oneline |
| - | - |
| Screenshot from 2024-08-09 13-00-26 |  Screenshot from 2024-08-09 12-59-45 |

The only bad thing is in order for the avatar icon to be the same size as the first two lines (as per @marcoambrosini's request), I needed to use some deep selectors at the end, due to the size being set by server styling.

CC @ChristophWurst

**Review by marcoambrosini — COMMENTED** [review]
Amazing @GVodyanov, I would just move the date to the top in line with the title, could you post screenshots of action menu on hover and of selected item?

**Comment by GVodyanov** [comment]
> Amazing @GVodyanov, I would just move the date to the top in line with the title, could you please post screenshots of action menu on hover and of selected item? Thanks :)

There you go, here is the date aligned up top now:
Screenshot from 2024-08-10 19-44-46

I also just noticed that the top padding is a bit larger than the side padding, now I made it `calc(var(--default-grid-baseline) * 2)` everywhere. Here are some various screenshots:

**On hover**
Screenshot from 2024-08-10 19-55-51

**Actions menu opened**
Screenshot from 2024-08-10 19-55-56

**Selected**
Screenshot from 2024-08-10 19-56-06

**Selected and on hover**
Screenshot from 2024-08-10 19-56-09

**Selected and actions menu opened**
Screenshot from 2024-08-10 19-56-17

**A few of them together, to see how the new padding looks**
image

**Comment by GVodyanov** [comment]
@ChristophWurst I understand this is pretty urgent, and I'm going on vacation next week. If you approve, I reckon you should merge this without waiting for me, so I just rebased everything after implementing Marco's review to make it as easy as possible.

**Review by ChristophWurst — APPROVED** [review]
Works very well :clap:

**Pull request merged**
