### PR TITLE
Release 0.7

### PR DESCRIPTION
**Pull request by ChristophWurst**
Still some work left to do, but let's have a PR to cleanly prepare all necessary steps for the next and long awaited release.

1. [x] increase version number
2. [x] write changelog
3. [ ] sign and package
4. [x] notify beta testers

If all goes well so far, then 

5. [ ] upload to app store
6. [ ] announce
7. [ ] celebrate 🍻 🎊

### CODE REVIEW

**Comment by Gomez** [comment]
Congrats! Will ship it to my Portknox beta testers.

**Comment by ChristophWurst** [comment]
Alright, many important PRs have been merged recently and we're close to finishing all ticket that have been set for the 0.7 milestone: https://github.com/nextcloud/mail/milestone/4

Hence I packaged a new nightly release that you can find [here on Github](https://github.com/nextcloud/mail/releases/tag/nightly-20170823) and on apps.nextcloud.com.

@nextcloud/mail @plastikschnitzer in case you aren't already, it would be great if you all could upgrade to this latest version and give it a good testing. Depending on how stable the app is right now, I'd like to release it ASAP.

**Comment by plastikschnitzer** [comment]
Great! I will test today and get back to you later with my result!

**Comment by skjnldsv** [comment]
Yepee! 🔔 🍾

**Pull request merged**
