### PR TITLE
Safari 100% height in message

### LINKED ISSUE #2973: Broken Style with macOS Safari
### Expected behavior
Nice style that could read whole email in a page.
Screenshot 2020-04-23 at 14 08 19

### Actual behavior
Reading area is so small I could almost not read anything
Screenshot 2020-04-23 at 14 08 10

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP Server

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48)
Safari

**Operating system:** (e.g. Arch Linux)
macOS

### PR DESCRIPTION
**Pull request by clementhk**
Fix #2973
Note that I'm not a frontend developer so I have no idea if this is the right way to do it, but it fixes the issue for me.

### CODE REVIEW

**Comment by clementhk** [comment]
The second commit removed a background that I'm not sure what it is for, disabling it shows no difference for me in Chrome, and fixed a style issue in Safari.

Screenshot 2020-04-27 at 04 15 54

Screenshot 2020-04-27 at 04 20 21

**Comment by ChristophWurst** [comment]
@nextcloud/mail does anyone have access to safari?

**Comment by clementhk** [comment]
I really hope to get it soon as I had to patch my production environment...
Any one? @nextcloud/Mac @nextcloud/ios  ?
Or at least can someone from design confirm that this wouldn't break other browsers? I've checked Safari/Chrome/Firefox on macOS and iOS and it works well, but it would be nice to know that it is technically correct.

**Comment by violoncelloCH** [comment]
`flex: 1` is basically a shorthand for `flex-grow: 1`, `flex-shrink: 1` and `flex-base: 0` (as opposed to `flex-base: auto`)... so probably the flex-base: 0 is what makes the difference on Safari, because this affects the calculation  of the "free" space to grow

**Comment by jancborchardt** [comment]
Just for reference regarding the linear-gradient: It is in place so that the mail text doesn't interfere too much visually with the Send button and the 3-dot-menu when you have a long mail text and they overlap.

But we can also simply give the 3-dot menu a half-transparent white background to fix that. :)

**Comment by clementhk** [comment]
> Just for reference regarding the linear-gradient: It is in place so that the mail text doesn't interfere too much visually with the Send button and the 3-dot-menu when you have a long mail text and they overlap.
> 
> But we can also simply give the 3-dot menu a half-transparent white background to fix that. :)

Ahh I see, I can't just remove it then.
It is fixed now by changing `transparent` to `rgba(255,255,255,0)`, it means the same thing but fixed the funny background for Safari.
See https://stackoverflow.com/questions/11829410/css3-gradient-rendering-issues-from-transparent-to-white

"Problem being transparent isn't a colour, it is black with 0 alpha, setting to specifically white with 0 alpha fixes the issue. (thanks @carisenda)

This still points on inconsistencies with how browser vendors are dealing with alpha transparency in CSS3 gradients."

**Comment by jancborchardt** [comment]
Oooh perfect @clementhk, thanks a lot for looking into this! cc @nextcloud/designers for reference, in case we ever run into this issue with Safari and gradients to transparency again.

**Comment by jancborchardt** [comment]
@clementhk you are also a member of the Nextcloud organization on Github, so you can also work on branches of this repository, and don’t need your own fork anymore. :) This makes it easier to collaborate in case changes are needed.

Also, we have a "Mail team" channel on our Nextcloud Talk instance – we can invite you to that as well if you like? :)

**Comment by clementhk** [comment]
> @clementhk you are also a member of the Nextcloud organization on Github, so you can also work on branches of this repository, and don’t need your own fork anymore. :) This makes it easier to collaborate in case changes are needed.
> 
> Also, we have a "Mail team" channel on our Nextcloud Talk instance – we can invite you to that as well if you like? :)

My contribution will be limited to fixing bugs I'm facing myself, if that's ok for you guys then sure!

**Comment by jancborchardt** [comment]
> > @clementhk you are also a member of the Nextcloud organization on Github, so you can also work on branches of this repository, and don’t need your own fork anymore. :) This makes it easier to collaborate in case changes are needed.
> > Also, we have a "Mail team" channel on our Nextcloud Talk instance – we can invite you to that as well if you like? :)
> 
> My contribution will be limited to fixing bugs I'm facing myself, if that's ok for you guys then sure!

Sure, no worries. Just makes it easier for you to ask if you have any questions about the code, and you can spend as much or as little time as you want. :)

**Pull request merged**
