### PR TITLE
feat(autoresponder): implement subject placeholder

### LINKED ISSUE #7216: Incorporate original subject in autoresponder
### Is your feature request related to a problem? Please describe.

As a user I set an autoresponder for vacation, sickness or other absence. To give the recipient of an automatically generated response context about the message, I would like the email to contain the original subject.

### Describe the solution you'd like

When I set my responder subject to *Out of office* someone contacts me with subject *Oversize pulley wheels are a scam*, then the autoresponder should be *Out of office, RE: Oversize pulley wheels are a scam*.

If I read https://dovecot.org/pipermail/dovecot/2008-July/032237.html correctly this should be possible with Sieve.

### Describe alternatives you've considered

N/a

### Additional context

cc @st3iny

### PR DESCRIPTION
**Pull request by st3iny**
Fix #7216

Can be tested locally via https://github.com/ChristophWurst/docker-imap-devel/pull/5.

image

### CODE REVIEW

**Comment by nimishavijay** [comment]
Nice! Would it be possible to use some other string in the input field? Perhaps something like `${subject of the original message}`. That would eliminate the need for helper text :)

If that is not possible, then we could do "${subject} will be replaced with the subject of the message you are responding to"

**Comment by st3iny** [comment]
> Nice! Would it be possible to use some other string in the input field? Perhaps something like `${subject of the original message}`. That would eliminate the need for helper text :)
> 
> If that is not possible, then we could do "${subject} will be replaced with the subject of the message you are responding to"

Thanks for your feedback! Unfortunately, spaces are not allowed. I adjusted the help text to your version.

**Review by GretaD — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Clever use of Sieve variables

**Comment by ChristophWurst** [comment]
Please squash and sign-off

**Pull request merged**
