### PR TITLE
enhancement: sort tags alphabetically

### PR DESCRIPTION
**Pull request by JohannesGGE**
Fixes: #8328

Sort tags alphabetically (after default and used tags)

### CODE REVIEW

**Review by hamza221 — COMMENTED** [review]
Sorting tags in message search can also be useful here, if I got the issue right 
https://github.com/nextcloud/mail/blob/c03ee464bd7c7c9fd14fb28c5d5e2a3e43a54cdd/src/components/SearchMessages.vue#L337-L339

**Comment by ChristophWurst** [comment]
Makes sense to sort them consistently everywhere

**Comment by JohannesGGE** [comment]
:heavy_check_mark:   Implemented it for the search as well

**Comment by hamza221** [comment]
Test and lgtm
One small thing tho, The default tags are on top only in the Tag Modal. Is that the expected behavior?
**Tag Modal:**
image
**Message search:**
image

**Comment by ChristophWurst** [comment]
@hamza221 could you check another time?

**Review by hamza221 — APPROVED** [review]
Tested and works

**Pull request merged**
