### PR TITLE
Fix image preview position in message attachment

### LINKED ISSUE #6480: Image attachment preview is left-aligned
### Steps to reproduce

1. Send yourself an email with a square image attached
2. Open the mail
3. Click on the attachment

### Expected behavior

A well designed preview.

### Actual behavior

Depending on the pic the design appears broken. Especially square pictures or anything that is higher than wide, will be put to the left of the modal. On the right there is just white space.

Bildschirmfoto vom 2022-05-17 12-08-09

Images with no white background emphasize the design bug.

### Mail app version

v1.12.0

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

Leftover of https://github.com/nextcloud/mail/pull/5898.

### PR DESCRIPTION
**Pull request by GretaD**
I tested it with almost all the pic size i had on my laptop. Please do the same :)
fixes #6480

### CODE REVIEW

**Comment by GretaD** [comment]
> Hm not sure abkut this. Couldn't the image simply get centered inside the modal?

it does not for all sizes. How would you do it?

**Comment by szaimen** [comment]
I can try to fix it. will open a new branch for this...

**Comment by GretaD** [comment]
> I can try to fix it. will open a new branch for this...

you can push here, im fine with it

**Comment by szaimen** [comment]
I pushed my changes to https://github.com/nextcloud/mail/pull/6723. I could not reproduce any problem with these changes anymore. :)

**Comment by GretaD** [comment]
lets continue here #6723

**Pull request closed without merging**
