### PR TITLE
Use PSR-4 loading for normal files

### PR DESCRIPTION
**Pull request by nickvergessen**
@ChristophWurst there are also invalid/missing imports of classes in the following files, but I'm not sure how to fix them:
- IMailBox
- UnifiedMailbox
- AliasesService
- ImapServerDetector
- ImapConnector

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@nickvergessen do you mean the horde classes? Did you install composer deps? 🙈

**Comment by ChristophWurst** [comment]
pushed a small fix for the info.xml structure. php unit tests pass btw 🚀

**Comment by nickvergessen** [comment]
No, I meant my last commit and

## UnifiedMailbox
> bildschirmfoto vom 2016-10-18 09-10-17

## AliasesService
> bildschirmfoto vom 2016-10-18 09-10-41

**Comment by ChristophWurst** [comment]
``NotFoundException`` is indeed missing. cc @tahaalibra 

Is independent of the psr4 changes, 👍 on this therefore

**Pull request merged**
