### PR TITLE
Add ckeditor5-html-embed plugin

### PR DESCRIPTION
**Pull request by ChristophWurst**
Rebased version of https://github.com/nextcloud/mail/pull/7298.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
How it looks

Bildschirmfoto vom 2022-10-14 11-59-26

**Comment by Zupe007** [comment]
@ChristophWurst 
I dont know why it is so small in the beginning. It was the same for me.
I fixed it temporarily by using the Nextcloud CSS APP with

`#select, button:not(.button-vue), input, textarea, div[contenteditable="true"], div[contenteditable="false"]{
        width: unset;
}`

not it looks like this for me.
Signatur



I am not skilled enough to fix the standard behavior.

**Comment by ChristophWurst** [comment]
I will have to discuss this with our designers then. I was under the impression that the HTML plugin would allow the users to edit the sources of the full message. Instead, it allows users to insert a block of HTML.

**Comment by Zupe007** [comment]
Yes it inserts a block. For my company that is exactly the feature we need and it is working quite good. 
For Example:

Creating a signature.
Signatur anlegen


Writing an email, signature is added and shown perfectly.
Signatur in Mail

**Comment by Zupe007** [comment]
@ChristophWurst Hey, is there any chance my Pull request will be or maybe is accepted?

**Comment by technikfrek** [comment]
Is there any progress?
Me and my company are also interested in this feature.

Thanks in advance!

**Comment by ChristophWurst** [comment]
Closing for now. I need designers to sign off this change. It still doesn't look like the right way to do this, sorry.

Ref https://github.com/nextcloud/mail/pull/7427#issuecomment-1283598965

**Pull request closed without merging**
