### PR TITLE
Add hint for autoconfig

### PR DESCRIPTION
**Pull request by DBJRdev**
The possibility for autoconfig seems not to be part of the documentation yet: the hint might be useful especially for admins of smaller Nextcloud instances.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Action required after 1s — DCO

Mind fixing this? :)

**Comment by DBJRdev** [comment]
@ChristophWurst: Actually I don't know what "Action required after 1s - DCO" means, but I'm willing to improve ;)

**Comment by ChristophWurst** [comment]
Oh, sorry. See https://github.com/nextcloud/mail/pull/2484/checks?check_run_id=392066882 for more info :) Let me know if you need help :)

**Comment by DBJRdev** [comment]
@ChristophWurst: I had done the commit via Github web interface, so it took me a while to realize that the problem was with signing off. I think it's fixed now.

**Pull request merged**
