### PR TITLE
fix(quota): Rename placeholder and fix desktop notification

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes https://github.com/nextcloud/mail/issues/8840

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Works now but also works on main when tested with a fake quota

**Comment by miaulalala** [comment]
> Works now but also works on main when tested with a fake quota

That's my experience too.

**Comment by miaulalala** [comment]
Works:

image

image

**Review by ChristophWurst — APPROVED** [review]
:+1: pr/commit titles are outdated

**Pull request merged**
