### PR TITLE
Fix: delete tags unset before confirmation

### PR DESCRIPTION
**Pull request by hamza221**
Tags get unset when clicking on delete tag before confirming

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I'm not sure I understand the problem. Could you describe before/after behavior and how this can be tested? THanks :)

**Comment by hamza221** [comment]
> I'm not sure I understand the problem. Could you describe before/after behavior and how this can be tested? THanks :) 

Before:
- set a test tag on some messages,
- click on delete tags 
- don't confirm
- envelopes get untagged anyways

**Comment by ChristophWurst** [comment]
Doesn't work for me. Untagging still happens before confirm.

**Comment by hamza221** [comment]
Should work now

**Pull request merged**
