### PR TITLE
Catch expired session and reload the page

### PR DESCRIPTION
**Pull request by ChristophWurst**
This is the brute force solution to https://github.com/nextcloud/mail/issues/5714.

A page reload will get the user to the login page with a redirect URL back to the current page.

Fixes https://github.com/nextcloud/mail/issues/5714

### CODE REVIEW

**Comment by GretaD** [comment]
i fixed the lint problem

**Comment by ChristophWurst** [comment]
> i fixed the lint problem

here I'm setting at my computer wondering why git won't let me push to my own branch :see_no_evil:

**Comment by GretaD** [comment]
> > i fixed the lint problem
> 
> here I'm sitting at my computer wondering why git won't let me push to my own branch see_no_evil

what did i do? :scream:

**Comment by GretaD** [comment]
> you force pushed to my branch. so git didn't allow pushing my linear commits. all fine.

yes i did :) i wanted to merge this asap to do a release, but we agreed not to :) thats why i dared to fix the error myself.

**Review by sazanof — APPROVED** [review]
Tested and redirecting =)

**Comment by ChristophWurst** [comment]
Failing tests unrelated

**Pull request merged**
