### PR TITLE
Don't overwrite mimetype

### PR DESCRIPTION
**Pull request by TheLastProject**
This breaks the formatting of some emails from GitLab.

Before this change, the message contains quoted-printable characters and the links are broken:
nextcloud_mail_patch_before

After, the message is correctly interpreted and the links are fixed:
nextcloud_mail_patch_after

I have not seen this change break the formatting of any other emails in my inbox, only fix them.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Hey, thanks for fixing this :v: 

I assume this addresses #1375 and similar reports, right?

**Comment by TheLastProject** [comment]
I'm not sure if it will fix that issue too, but it may help. I just noticed this being broken for GitLab email notifications and found this to be a reliable fix that didn't break anything else, so I'm submitting this to fix an issue I ran into myself.

**Comment by ChristophWurst** [comment]
@nextcloud/mail can anybody reproduce this?

**Comment by jancborchardt** [comment]
Actually can’t reproduce, GitLab notifications (in this case from GNOME Gitlab) look fine here with latest master:
gitlab mail notification

-----

@TheLastProject btw, do you know about the upcoming Contributor Week in Stuttgart, March 11–15? :slightly_smiling_face: 
There’s travel & accomodation support available for contributors as well, check the blog post for more info: https://nextcloud.com/blog/the-contributor-week-is-over-time-to-plan-for-the-next-one/

**Comment by TheLastProject** [comment]
Hmm, I think it's probably caused by the very corporate email signature that was added. I've attached a heavily anonymized .eml with which I can reproduce the problem. (Please rename the extension to .eml, GitHub doesn't allow uploading .eml files, and drag it into Thunderbird or so to add it to your email account and then view it in NextCloud mail).

[Access to the example-team _ example project was granted.txt](https://github.com/nextcloud/mail/files/2744454/Access.to.the.example-team._.example.project.was.granted.txt)

**Comment by TheLastProject** [comment]
@jancborchardt I wasn't aware of the Contributor Week. Thanks for noting, but I'll skip, busy enough for work, and I have my own hobby projects that need more love too. Not enough time :) I'll just occasionally submit fixes as I tend to do :)

**Comment by jancborchardt** [comment]
@TheLastProject sorry for the late reply! I can’t find a way to put the .eml file in my mailbox, neither using Thunderbird nor Geary.

I can open it like that from File → Open message, but then there’s no way to save it in a folder:
screenshot from 2019-01-23 11-49-32


@sahalsaad @ALSai @pierlon @xf- @newhinton can you reproduce or test?

**Comment by ChristophWurst** [comment]
bildschirmfoto von 2019-01-23 12-12-15
I've imported the eml into Evolution and opened the message with this app using the master branch. It renders as expected.

**Comment by TheLastProject** [comment]
And the links also work? How odd... I really can reliably reproduce the issue on this side :/

**Comment by pierlon** [comment]
I also can render the email using the master branch. Using Dovecot as my server.

mail

**Comment by ChristophWurst** [comment]
Closing as it's not reproducible :)

**Pull request closed without merging**
