### PR TITLE
Update app store screenshot

### LINKED ISSUE #8721: App store screenshot is outdated
### Steps to reproduce

1. Open https://apps.nextcloud.com/apps/mail

### Expected behavior

See https://github.com/nextcloud/mail/blob/9218afb5fe30ce22b1934bc33528cab0bc362d4e/screenshots/mail.png or newer

### Actual behavior

See https://github.com/nextcloud/mail/blob/915b0b6ffde69a70fdbbfafa6b48dd2a07ba433c/screenshots/mail.png

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

This has been raised earlier already: https://github.com/nextcloud/mail/issues/7483

### PR DESCRIPTION
**Pull request by GretaD**
fixes #8721

### CODE REVIEW

**Comment by GretaD** [comment]
I am not sure how we generate that url @ChristophWurst

**Comment by ChristophWurst** [comment]
Upload the image into a github comment, then use that URL

**Comment by GretaD** [comment]
mail

**Comment by GretaD** [comment]
the update branch was by accident

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
