### PR TITLE
Fix contacts integration with disabled sharing enumeration option

### PR DESCRIPTION
**Pull request by ChristophWurst**
Contacts integration must not list system users when the sharing option
is set to no enumerate system users.

Fixes https://github.com/nextcloud/mail/issues/848

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@nextcloud/mail @pierreozoux ping

**Comment by pierreozoux** [comment]
@ChristophWurst Thanks for fixing, and really sorry, don't have time to test at the moment, but when released, I'll come here to comment :/ .

**Comment by ChristophWurst** [comment]
> @ChristophWurst Thanks for fixing, and really sorry, don't have time to test at the moment, but when released, I'll come here to comment :/ .

No worries. You can find a pre-release here: https://github.com/nextcloud/mail/releases/tag/v0.8.0-beta1

**Comment by rasos** [comment]
Thanks for fixing. Another brick to meet GDPR requirements.

**Pull request merged**
