### PR TITLE
Show delete outbox feedback

### PR DESCRIPTION
**Pull request by GretaD**
deletoutbox

### CODE REVIEW

**Comment by miaulalala** [comment]
Am I missing something or will this only show a success toast? I would also add a error toast for when the deletion fails :)

**Comment by GretaD** [comment]
> Am I missing something or will this only show a success toast? I would also add a error toast for when the deletion fails :)

the success one was the one missing, the error one was already added, see 2 lines below

**Review by st3iny — APPROVED** [review]
Tested and works!

However, this does not address the mentioned issue #6268. I updated the ticket to clarify what it's about.

**Comment by GretaD** [comment]
> Tested and works!
> 
> However, this does not address the mentioned issue #6268. I updated the ticket to clarify what it's about.

ohh so it was about discarding, not delete. Ok, i'll do that in a separate pr

**Comment by st3iny** [comment]
Failure of static analysis is unrelated.

**Comment by miaulalala** [comment]
Sorry my bad :see_no_evil:

**Pull request merged**
