### PR TITLE
Fixes for dark theme

### PR DESCRIPTION
**Pull request by jancborchardt**
## Fixed mail subtitle
mail subtitle before
mail header after

## Fixed mail composer borders
mail composer borders before
composer borders after

## Tried to fix folder icons
But for some reason inbox, favorites, and trash are not replaced. Any idea why @skjnldsv?
mail folder icons before  mail icons after

Please review @nextcloud/mail  :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Merge?

**Comment by ChristophWurst** [comment]
Sure! I guess the folder icon fix can happen later :)

**Comment by jancborchardt** [comment]
About the folder icons which are not inverted, @skjnldsv said to me:

> Maybe the parser has issues checking the icon?
> You can try the regex in the iconsCacher.php file
> and your svg
> with regex101.com

@ChristophWurst does that help? :)

**Comment by ChristophWurst** [comment]
I have no clue about the icons :man_shrugging:

**Pull request merged**
