### PR TITLE
Fix envelope and message previews showing PGP ciphertext

### PR DESCRIPTION
**Pull request by ChristophWurst**
| Before | After |
|---|---|
| Bildschirmfoto vom 2022-11-07 10-49-44 | Bildschirmfoto vom 2022-11-07 13-08-26 |
| Bildschirmfoto vom 2022-11-07 11-07-18 | Bildschirmfoto vom 2022-11-07 13-08-33 |

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
code looks good

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Looks good, but as per design guidelines we never use italic. Otherwise nice. :)

**Comment by ChristophWurst** [comment]
> as per design guidelines

https://docs.nextcloud.com/server/latest/developer_manual/search.html?q=italic&check_keywords=yes&area=default

**Comment by ChristophWurst** [comment]
Italic styling removed.

**Comment by jancborchardt** [comment]
@ChristophWurst yep, sorry for missing the link :) direct: https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html#typography
> No italics or UPPER CASE as these text styles are less legible

**Review by jancborchardt — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
