### PR TITLE
Support PHP 7.3

### PR DESCRIPTION
**Pull request by xf-**
- [x] Requires https://github.com/nextcloud/mail/pull/1570

### CODE REVIEW

**Comment by xf-** [comment]
@ChristophWurst i think you are the (only|few) maintainer using such a strict version in info.xml. I used the github search an a lot of repos us only min 5.6 or 7. A few use max-version="7"
https://github.com/search?q=org%3Anextcloud+filename%3Ainfo.xml+php+max-version&type=Code

**Comment by xf-** [comment]
I will check the small notices in dependencies.

**Comment by ChristophWurst** [comment]
Such a bummer we still cannot use php7.3 here …

**Comment by xf-** [comment]
@ChristophWurst i use Mail under 7.3. I think syntax problem are in the tests. Logging is empty

**Comment by Xananax** [comment]
Downgrading PHP on my Arch box would be a bummer. Can I just changed the info.xml locally to use mail?

**Comment by ChristophWurst** [comment]
You may change the code to whatever you want, but be aware that you might see bugs due to the incompatibility.

**Comment by Xananax** [comment]
Reporting for anyone encountering the same problem: Changing php max-version to `7.3` and server max-version to `15`. Mail seems to work without problems (tried: accessing inbox and sending email). I have a display issue (the mail interface is small and doesn't stretch to the whole screen, fixed by adding `#app{width:100%}`), but I suppose it's unrelated.

**Comment by tuzohetoruyu** [comment]
please support php 7.3, this app is so nice :+1:  and so sad i cant use it :( :-1:

**Comment by Xananax** [comment]
> please support php 7.3, this app is so nice +1 and so sad i cant use it :( -1

First post in this issue specifies that the problem comes from upstream. There's nothing to fix for them here.

If you're in a hurry, you can do what I did. With some local changes, mail works without issues. Open `apps/mail/appInfo/info.xml`. There, you will find the minimum and maximum PHP and server versions. Change them to support php `7.3` and nextcloud `15`.

**Comment by J0WI** [comment]
This is fixed in Horde [2.6.5](https://github.com/horde/Mail/releases/tag/v2.6.5).

**Comment by ChristophWurst** [comment]
Ref https://github.com/nextcloud/mail/pull/1570

**Comment by ChristophWurst** [comment]
@xf- please update your branch. CI should be green with the latest composer updates. Then we can finally merge this :)

**Comment by ChristophWurst** [comment]
:popcorn:

**Comment by J0WI** [comment]
Can this be backported for NextCloud 15?

**Comment by ChristophWurst** [comment]
Yes, you could backport the horde lib updates.

**Comment by J0WI** [comment]
@ChristophWurst I'm sorry, I don't know how the release process is organized here. There are no stable branches, so I created [11.1](https://github.com/nextcloud/mail/tree/11.1), but CI is disabled there.
Could you guide me though this?

**Comment by ChristophWurst** [comment]
I would suggest to just do it locally. Update the composer dependencies and either just use the git checkout or package a new tarball for your instance. I don't have any plans to make this an official release as we usually don't backport.

**Comment by J0WI** [comment]
@ChristophWurst I'm doing this for https://github.com/nextcloud/docker/pull/706#pullrequestreview-223917430, not for myself ;)
Originally PHP 7.3 support was announced for NextCloud 15, but up to now we failed to upgrade.

**Comment by ChristophWurst** [comment]
Okay, let me try to find some time this week to do this exceptional backport release.

**Comment by ChristophWurst** [comment]
Could you please open a new ticket? THanks

**Comment by MorrisJobke** [comment]
@ChristophWurst Can the backport-request label be removed?

**Comment by ChristophWurst** [comment]
Yes!

**Pull request merged**
