### PR TITLE
Document how admins can collect troubleshoot information

### PR DESCRIPTION
**Pull request by ChristophWurst**
Because I find myself repeating those instructions over and over, though I have some saved replies. @nextcloud/mail I think this will also help you triage bug reports by telling the reporters to see https://github.com/nextcloud/mail/blob/master/doc/admin.md#troubleshooting and post more data for the individual issues.

### CODE REVIEW

**Review by StCyr — CHANGES_REQUESTED** [review]
Where are all these docs (devel, admin, user) published? 

Could you add a link to them in the readme.MD file?

**Comment by StCyr** [comment]
https://apps.nextcloud.com/apps/mail only links to readme.md file

**Comment by ChristophWurst** [comment]
> Where are all these docs (devel, admin, user) published?

Nowhere right now. I'm still unsure how/where to publish them.

> Could you add a link to them in the readme.MD file?

I'll do this in a separate PR :v:

**Comment by ChristophWurst** [comment]
> Could you add a link to them in the readme.MD file?

https://github.com/nextcloud/mail#documentation

**Comment by StCyr** [comment]
> 
> 
> > Could you add a link to them in the readme.MD file?
> 
> https://github.com/nextcloud/mail#documentation

ha ha ha 🤦

**Review by StCyr — APPROVED** [review]

**Pull request merged**
