### PR TITLE
Bump @nextcloud/vue to v7.0.0-beta.0

### PR DESCRIPTION
**Pull request by GretaD**
- [x] add appcontent on setup.vue

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Make sure you are on the latest server master because v7 requires https://github.com/nextcloud/nextcloud-vue/pull/3091. That PR was just merged 2h ago.

**Comment by ChristophWurst** [comment]
Judging by your header bar you are on an old master or another branch. The design should look a lot different.

**Comment by GretaD** [comment]
i cannot reproduce this: https://github.com/nextcloud/nextcloud-vue/pull/3091#issuecomment-1233083761 

all looks good on header

**Comment by ChristophWurst** [comment]
> i cannot reproduce this: [nextcloud/nextcloud-vue#3091 (comment)](https://github.com/nextcloud/nextcloud-vue/pull/3091#issuecomment-1233083761)

yep, I could also not tell what's supposed to be broken

**Review by ChristophWurst — APPROVED** [review]

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
we need to drop nextcloud 24 and older. let's do that carefully

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
