### PR TITLE
Fix app structure for Nextcloud 14

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/server/pull/9982https://github.com/nextcloud/server/pull/9982

My attempt at fixing https://github.com/nextcloud/mail/issues/981.

cc @jancborchardt @skjnldsv input/help would be *very* appreciated. I don't know if it's this apps CSS or the structure that makes is to hard to comply the new structure, but I can't get it right so far. It's a lot worse on master, but it seems that some additional wrapping elements cause the CSS rules not to apply. I can't remove them, however, because they are required for our UI framework (Marionette) …

---

Bugs

- [x] Overall app structure is not compliant with new standard
- [x] Navigation toggle button is shown all the time
- [x] Message details are wrapped in an additional (useless) element
- [x] Message detail header is not fixed anymore
- [x] Message details got narrower as well, doesn't take up the available space
- [x] Messages list got narrower
- [x] Message delete icon in message list is misplaced
- [ ] ~~colors variables dark theme compatibility~~ will fix this in a separate PR
- [x] message list needs fixes for the answered icon and attachment icon
- [x] messages list needs fixes for the loading icon and load more message button
- [x] Need a mobile fix for the narrow screens. (when clicking a message in the list add the 'showdetails' class on the app-content-list)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I will take another attempt at this tomorrow morning when it's below 30°C and I can think clearly :sweat:

**Comment by skjnldsv** [comment]
aaaah, the good old marionette wrapping shitstorm ^^

**Comment by ChristophWurst** [comment]
> I will take another attempt at this tomorrow morning when it's below 30°C and I can think clearly sweat

It's 24.4°C here right now, so I was able to resolve that one tricky wrapping div with some official Marionette kung fu.

What I don't get is the ``<div id="app-navigation-toggle" class="icon-menu"></div>`` part. Do I have to hide/show this manually? This element is now shown all the time and takes up the full width.

**Comment by ChristophWurst** [comment]
> What I don't get is the <div id="app-navigation-toggle" class="icon-menu"></div> part. Do I have to hide/show this manually? This element is now shown all the time and takes up the full width.

Nvm, just discovered that this is added/injected automatically and so I had it there twice (one hidden and once visible).

**Comment by ChristophWurst** [comment]
@skjnldsv I've updated the PR description with a list of bugs that have been fixed already and those I've found but not yet tackled.

**Comment by skjnldsv** [comment]
> What I don't get is the <div id="app-navigation-toggle" class="icon-menu"></div> part. Do I have to hide/show this manually? This element is now shown all the time and takes up the full width.

You shouldn't add this, it should be added by the snapjs I think :thinking:

**Comment by ChristophWurst** [comment]
> You shouldn't add this, it should be added by the snapjs I think thinking

https://github.com/nextcloud/mail/pull/1001#issuecomment-409451123 :wink:

**Comment by skjnldsv** [comment]
Well done !! 🤗 😊

**Comment by ChristophWurst** [comment]
Thanks a lot for your help! :rocket: :hugs:

**Pull request merged**
