### PR TITLE
Fix: Save attachement to files

### LINKED ISSUE #9613: Unable to save attachement to files
### Steps to reproduce

Honestly I'm not too sure..

### Expected behavior

A modal should open allowing you to save an attachment to a specified directory.

### Actual behavior

Nothing. An error is thrown in the console which I'll put in the extra details section.

### Mail app version

3.6.0

### Mailserver or service

_No response_

### Operating system

AIO Nextcloud docker (NextCloud 28 & 29)

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Error that gets thrown (verified the same across Firefox and Chrome)

```log
vue.runtime.esm.js:3065 TypeError: (0 , V.a1)(...).setMultiSelect(...).addMimeTypeFilter(...).setModal is not a function
    at o.saveToCloud (MessageAttachment.vue:196:1)
    at click (MessageAttachment.vue:1:1899)
    at an (vue.runtime.esm.js:3033:30)
    at o.n (vue.runtime.esm.js:1832:20)
    at an (vue.runtime.esm.js:3033:30)
    at e.$emit (vue.runtime.esm.js:3732:17)
    at o.onClick (actionText-jLsEBszD.mjs:118:16)
    at o.handleClick (NcActionButton.mjs:113:12)
    at an (vue.runtime.esm.js:3033:30)
    at HTMLButtonElement.n (vue.runtime.esm.js:1832:20)
on @ vue.runtime.esm.js:3065
sn @ vue.runtime.esm.js:3057
rn @ vue.runtime.esm.js:3024
an @ vue.runtime.esm.js:3040
n @ vue.runtime.esm.js:1832
an @ vue.runtime.esm.js:3033
e.$emit @ vue.runtime.esm.js:3732
onClick @ actionText-jLsEBszD.mjs:118
handleClick @ NcActionButton.mjs:113
an @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
Ya.s._wrapper @ vue.runtime.esm.js:7500
Show 12 more frames
Show less
MessageService.js:71
```

This has been happening for a little while now. It's important to note that it did work a few months ago. Upgrading to a beta version of 3.5.x a while ago seems to be what did it, but even being on the latest stable version seems to be broken. It looks like the "setModal" is deprecated in the @nextcloud/vue and @nextcloud/dialogue repositories, so I'm surprised this hasn't been altered or reported before.

- [Suspect bit of code in repo](https://github.com/nextcloud/mail/blob/a6ec3c14af92f78da22c1bfe2de8a2730d66c8f3/src/components/MessageAttachment.vue#L196)

Feel free to reach out if you need more info. I'll provide whatever I can.

### PR DESCRIPTION
**Pull request by hamza221**
fix #9613

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by Chartman123** [comment]
@hamza221 @ChristophWurst it's still present in the code for multiple attachments

https://github.com/nextcloud/mail/blob/2ea095380d8e865908d5653f6cc046e79c2635f3/src/components/MessageAttachments.vue#L168 for multiple attachments

**Comment by hamza221** [comment]
@Chartman123  Thank you for the heads up , I'll push a fix later today

**Pull request merged**
