### PR TITLE
Fix another case of reply to/cc handling

### PR DESCRIPTION
**Pull request by ChristophWurst**
@jancborchardt I've started fixing https://github.com/nextcloud/mail/issues/591 with writing a test and to my surprise this is correctly handled already. Please see the test code. Did I misunderstand your reproduction steps?

Local test execution blocked by https://github.com/nextcloud/mail/pull/602

### CODE REVIEW

**Comment by jancborchardt** [comment]
Here’s a simpler testcase where I have an error still:
- Nina sends a mail to the company mailing list
→ in the reply, Nina is in the »to«, but no one is in the cc (should be company mailing list)

**Comment by ChristophWurst** [comment]
> a simpler testcase

Sounds simple, yes. But extracting logic out of this is a different story 😉 

So, if you reply to an email where you're neither in the TO field nor in CC, how do you know where to answer to?

It then really depends on the reply strategy, like *answer all*, *answer to group/list* or however mail clients name it.

*answer to group* would be a sensible default IMO, but how do we know what the list is? Can we safely assume only there's only one recipient in that case and that one is the list? Or could there be the list **and** a regular recipient? Then it gets tricky because based on the address I cannot tell which one is a list and which one isn't.

**Comment by jancborchardt** [comment]
We always did answer all. So in my example above, the reply should have Nina in to (cause I'm replying directly to her) and the list in cc.

**Comment by ChristophWurst** [comment]
> the reply should have Nina in to (cause I'm replying directly to her)

Okay, *reply all* it is. Let me see if I can put that into code.

**Comment by ChristophWurst** [comment]
Fixed.

**Comment by ChristophWurst** [comment]
Blocked by #621

**Pull request merged**
