### PR TITLE
Fix missing name of local attachments

### PR DESCRIPTION
**Pull request by ChristophWurst**
Requires #4473

### CODE REVIEW

**Comment by st3iny** [comment]
Just tested this branch on my local instance. Uploading attachments works as expected but attaching files from the cloud does not work. The bug may be unrelated to this PR.

Error when attaching a file from the cloud:
```
ConsoleLogger.js:54 [ERROR] mail: could not choose a file as attachment {app: "mail", uid: "admin", error: TypeError: Cannot read property 'getPatcher' of undefined
    at http://localhost/dev_apps/mail/js/…}app: "mail"error: TypeError: Cannot read property 'getPatcher' of undefined
    at http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15923:63
    at memoized (http://localhost/dev_apps/mail/js/mail.js:18144:23)
    at _callee$ (http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15941:20)
    at tryCatch (http://localhost/dev_apps/mail/js/mail.0.42337b8a25a30c331132.js:184713:40)
    at Generator.invoke [as _invoke] (http://localhost/dev_apps/mail/js/mail.0.42337b8a25a30c331132.js:184943:22)
    at Generator.next (http://localhost/dev_apps/mail/js/mail.0.42337b8a25a30c331132.js:184768:21)
    at asyncGeneratorStep (http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15890:103)
    at _next (http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15892:194)
    at http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15892:364
    at new Promise (<anonymous>)message: "Cannot read property 'getPatcher' of undefined"stack: "TypeError: Cannot read property 'getPatcher' of undefined↵    at http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15923:63↵    at memoized (http://localhost/dev_apps/mail/js/mail.js:18144:23)↵    at _callee$ (http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15941:20)↵    at tryCatch (http://localhost/dev_apps/mail/js/mail.0.42337b8a25a30c331132.js:184713:40)↵    at Generator.invoke [as _invoke] (http://localhost/dev_apps/mail/js/mail.0.42337b8a25a30c331132.js:184943:22)↵    at Generator.next (http://localhost/dev_apps/mail/js/mail.0.42337b8a25a30c331132.js:184768:21)↵    at asyncGeneratorStep (http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15890:103)↵    at _next (http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15892:194)↵    at http://localhost/dev_apps/mail/js/mail.3.c2082b59846d5341d581.js:15892:364↵    at new Promise (<anonymous>)"__proto__: Erroruid: "admin"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
log @ ConsoleLogger.js:54
error @ ConsoleLogger.js:80
_callee$ @ ComposerAttachments.vue?674f:223
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ ComposerAttachments.vue?674f:1
_throw @ ComposerAttachments.vue?674f:3
Promise.then (async)
asyncGeneratorStep @ ComposerAttachments.vue?674f:1
_next @ ComposerAttachments.vue?674f:3
Promise.then (async)
asyncGeneratorStep @ ComposerAttachments.vue?674f:1
_next @ ComposerAttachments.vue?674f:3
(anonymous) @ ComposerAttachments.vue?674f:3
(anonymous) @ ComposerAttachments.vue?674f:3
onAddCloudAttachment @ ComposerAttachments.vue?674f:233
invokeWithErrorHandling @ vue.runtime.esm.js:1854
Vue.$emit @ vue.runtime.esm.js:3888
onAddCloudAttachment @ Composer.vue?1398:721
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
invokeWithErrorHandling @ vue.runtime.esm.js:1854
Vue.$emit @ vue.runtime.esm.js:3888
onClick @ ActionButton.js:43
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917
```

**Comment by ChristophWurst** [comment]
> Error when attaching a file from the cloud:

You need https://github.com/nextcloud/mail/pull/4473 as specified in the PR description, I forgot to rebase the PR

**Review by st3iny — APPROVED** [review]
Uploading and adding attachments from files works after merging the mentioned required PR.

**Pull request merged**
