### PR TITLE
Bump CKEditor to v26

### PR DESCRIPTION
**Pull request by ChristophWurst**
The editor still renders :+1:

### CODE REVIEW

**Comment by ChristophWurst** [comment]
fails because of npm7. will be better after #4706

**Review by StCyr — COMMENTED** [review]
Indeed, it works

**Review by StCyr — APPROVED** [review]
Shall we merge?

**Comment by ChristophWurst** [comment]
Let's wait because linter fails

**Comment by StCyr** [comment]
works good 👍

**Comment by st3iny** [comment]
This error can be fixed by replacing the deprecated package `babel-eslint` with `@babel/eslint-parser` in nextcloud/eslint-config and our package.json.

**Comment by ChristophWurst** [comment]
> This error can be fixed by replacing the deprecated package `babel-eslint` with `@babel/eslint-parser` in nextcloud/eslint-config and our package.json.

You are our hero. I've debugged this for like 20min and couldn't figure that out :speak_no_evil:

**Comment by StCyr** [comment]
> 
> 
> > This error can be fixed by replacing the deprecated package `babel-eslint` with `@babel/eslint-parser` in nextcloud/eslint-config and our package.json.
> 
> You are our hero. I've debugged this for like 20min and couldn't figure that out 🙊

I would love to hear how he debugged that

**Comment by ChristophWurst** [comment]
I for one got lost in this ticket: https://github.com/babel/babel/issues/12857

**Comment by st3iny** [comment]
This error seems to be all over the place. I looked at https://github.com/babel/babel-eslint/issues/799#issuecomment-666741093. Running eslint just works after replacing the package with @babel/eslint-parser :man_shrugging:

**Pull request merged**
