### PR TITLE
Add notification callback prototype

### PR DESCRIPTION
**Pull request by cptMikky**
A "how I think this might be done" solution for logging mentioned in https://github.com/nextcloud/mail/issues/2971.

Not mergeable, it's only supposed to represent the general idea.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@nestorf5 @Anarch157a @filipiff @dengste could you test and review this pull request? You were active in the issue this is supposed to fix: **Mail App Unexpected error during account creation #2971**

Thanks a lot!

**Comment by ChristophWurst** [comment]
> Not mergeable, it's only supposed to represent the general idea.

@jancborchardt the intention was never to have anything mergeable but just to demonstrate the concept.

**Comment by dengste** [comment]
@jancborchardt Sorry for being dense, but I'm not familiar with PHP development. I've applied the patch, where and for what should I look? I'm not seeing any difference in the logs.

**Comment by cptMikky** [comment]
@dengste this concept, as is, doesn't extend the logs. It just shows how the notification callback works. If you want to test it, you need to replace `var_dump` with some actual logging code and copy it under each `case STREAM_NOTIFY_...` clause to get results in log.

**Pull request closed without merging**
