### PR TITLE
docs: Update app maintainers

### PR DESCRIPTION
**Pull request by ChristophWurst**
For https://github.com/nextcloud/groupware/pull/83

@GretaD @kesselb please let me know which name/pseudonym to use :)

### CODE REVIEW

**Comment by GretaD** [comment]
gretad or just greta is fine :)

**Comment by kesselb** [comment]
I'm also okay with Daniel or kesselb

**Comment by ChristophWurst** [comment]
done

**Review by kesselb — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Pull request merged**
