### PR TITLE
Respect allow/disallow group sharing setting in group service

### PR DESCRIPTION
**Pull request by tcitworld**
Some instances don't want to allow sending emails to everyone in a group.

### CODE REVIEW

**Comment by myrho** [comment]
Trying to `make dev-setup` but it fails at `kwi/urllinker`:

```
  - Installing kwi/urllinker (dev-bleeding bc54f1a): Cloning bc54f1afe6
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
```

The repo is not public. How to install that? This is related to mail app installation in gen. I think.

**Comment by myrho** [comment]
I had the same issue one year before: https://github.com/nextcloud/mail/pull/2972

**Comment by ChristophWurst** [comment]
>   - Installing kwi/urllinker (dev-bleeding bc54f1a): Cloning bc54f1afe6
> Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos

https://bitbucket.org/kwi/urllinker was deleted. https://github.com/youthweb/urllinker is a fork that duckduckgo found for me. We could try to switch over.

**Comment by myrho** [comment]
Finally made it to install the app. Looks fine, works as expected.

**Review by ChristophWurst — APPROVED** [review]

**Comment by Art4** [comment]
Hi, I'm the maintainer of [youthweb/urllinker](https://github.com/youthweb/urllinker) and I just found out that you are using my library in Nextcloud. 😄 I'm glad that my work is used by such a great product that I use myself.

**Pull request merged**
