### PR TITLE
Fixed subfolders collapsible

### PR DESCRIPTION
**Pull request by skjnldsv**
| Before | After |
|:---:|:---:|
| kazam_screenshot_00007 | kazam_screenshot_00006 |

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Gomez @lcalaresu @jakobsack mind giving it a test? :)

**Comment by ChristophWurst** [comment]
Doesn't work for me. It looks the same as on master -> broken. Tested on FF58.

**Comment by ChristophWurst** [comment]
Doesn't seem to work on Chrome neither :/

**Comment by ChristophWurst** [comment]
Tried again and cannot spot any difference/improvement …

Before
bildschirmfoto von 2017-11-13 16-13-42

After
bildschirmfoto von 2017-11-13 16-14-26

**Comment by skjnldsv** [comment]
It's missing some commits... 🙈

**Comment by ChristophWurst** [comment]
> It's missing some commits... 🙈

How would I know 🙈

**Comment by skjnldsv** [comment]
@ChristophWurst There is a bug. Look at the commits! 😕

**Comment by skjnldsv** [comment]
@ChristophWurst Okay, fixed! Don't know what happened! ^^'

**Comment by omocinteractive** [comment]
Hi,

the fix with z-index is not working for me (12/0.7.9). I fixed this for me by deleting &.collapsible:not(.open) { > ul, > .folders {...}.

**Comment by ChristophWurst** [comment]
@omocinteractive hey, could you please file a new ticket for that? Thanks!

**Pull request merged**
