### PR TITLE
include bower dependencies in git

### PR DESCRIPTION
**Pull request by ChristophWurst**
Makes people's life easier as discussed in https://github.com/nextcloud/mail/issues/182.

I will add npm deps too once this has been merged.

cc @jancborchardt @nextcloud/mail

### CODE REVIEW

**Comment by jancborchardt** [comment]
Works nicely :+1:

**Comment by jancborchardt** [comment]
Also cc @Henni & @irgendwie from Contacts. This is a thought we should have for Contacts as well since we had problems getting it set up for contributors in the past.

**Comment by skjnldsv** [comment]
Agreed, but I don't think this is why no one work on contacts 😄

**Comment by jancborchardt** [comment]
It can definitely be a factor. At an event I helped someone set up a Contacts dev environment and it was really frustrating with all the dependencies. We ended up needing to copy my vendor files etc. over.

**Pull request merged**
