### PR TITLE
Simple system tests / Screenshot setup generator

### PR DESCRIPTION
**Pull request by ChristophWurst**
Hey @nextcloud/mail,

since I had a hard time reproducing #930 / #1031 on my dev setup, I wrote a script to generate test data on the local Docker IMAP server. Since we could re-use this hacky though working piece of code, I figured we should use this to generate dummy data for our screenshots.

So, I need some creative input on message senders and subjects we want to show in our screenshot. Please comment suggestions below in the form of

```
Sender: Winnie Puuh <w.puuh@disney.com>
Subject: Birthday invitation

```

Bonus points for e-mail addresses that have a Gravatar :wink: 

## Script usage

```
$ php -f tests/System/setup_multiaccount.php 
Creating test user... done: testuser8121508462343602547
Creating test mail accounts... done
Creating test data... done
Credentials: testuser8121508462343602547 : testuser8121508462343602547pwd
You may now log in at https://localhost/login?user=testuser8121508462343602547&redirect_url=/apps/mail
```

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@nextcloud/mail :ping_pong:

**Comment by MariusBluem** [comment]
```
Sender: Leon Green <leon.green@acme.inc>
Subject: Outline for tomorrows meeting
```

```
Sender: Louis Johnson <louis.johnson@acme.inc>
Subject: New projector for room 1.02
```

```
Sender: Christine Scott <christine.scott@acme.inc>
Subject: Parental leave of Leon Green
```

```
Sender: Christine Scott <christine.scott@acme.inc>
Subject: Parental leave of Leon Green
```

```
Sender: Molly Allen <molly.allen@acme.inc>
Subject: Our homepage is down :(
```

**Comment by ChristophWurst** [comment]
@MariusBluem thanks a lot!

This is what we've currently got:
bildschirmfoto von 2018-08-21 09-35-11

**Comment by MariusBluem** [comment]
@ChristophWurst Will create more this week :)

**Comment by ChristophWurst** [comment]
@MariusBluem :ping_pong: :wink:

**Comment by ChristophWurst** [comment]
Let's close for now. No time to finish this.

**Pull request closed without merging**
