### PR TITLE
Adds "sass" as a dependency to fix some build error

### PR DESCRIPTION
**Pull request by StCyr**
Fixes https://github.com/nextcloud/mail/issues/4485

(From https://stackoverflow.com/questions/62705395/angular-error-postcss-received-undefined-instead-of-css-string/62925718)

Signed-off-by: Cyrille Bollu <cyr.debian@bollu.be>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
I think the package-lock.json change is missing. Could you `npm i` on this branch and ammend your commit? :)

**Comment by ChristophWurst** [comment]
eslint fails again and I don't know why :shrug:

**Comment by StCyr** [comment]
> eslint fails again and I don't know why 🤷

My npm version which is higher than yours? (I had to change field « lockfileVersion »back to 1 manually. Maybe some other unwanted changes went through)

**Comment by ChristophWurst** [comment]
> My npm version which is higher than yours? (I had to change field « lockfileVersion »back to 1 manually. Maybe some other unwanted changes went through)

I'm still on 6.x :cold_sweat:

**Comment by st3iny** [comment]
@StCyr Please rebase, discard the lock and recreate it (via `npm install`) so we can get this merged :)

**Review by st3iny — APPROVED** [review]
Eslint error is unrelated.

**Pull request merged**
