### PR TITLE
Add text on 3rd outbox column

### LINKED ISSUE #6270: Add Outbox Description in rightmost column
### Steps to reproduce

1. Open a outbox folder.
2. See that the content (third column) is empty. 

### Expected behavior

The content should include a message "Pending or not sent messages will show up here".

### Actual behavior

Content is empty.
image

### Mail app version

1.12.0

### Mailserver or service

Not relevant

### Operating system

Not relevant

### PHP engine version

Not relevant

### Web server

Not relevant

### Database

Not relevant

### Additional info

Not relevant

### PR DESCRIPTION
**Pull request by GretaD**
fixes #6270

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
Looks good! Shuld we make a content centered (EmptyContent)?
image

**Comment by GretaD** [comment]
> Looks good! Shuld we make a content centered (EmptyContent)? image

its not ready for review

**Comment by GretaD** [comment]
> > Looks good! Shuld we make a content centered (EmptyContent)?

this is a good question actually.
This is not really empty content and in general we add messages like this on center-top of the screen, like for example, "no message selected"
nomessages

@ChristophWurst @st3iny what do you think, should we style it as emptycontent, or as nomessageselected?

**Comment by ChristophWurst** [comment]
I would say make the three views look consistent

**Comment by GretaD** [comment]
I will change everything to look consistent here: #6387

while im moving on with this one and style it on center to have it consistent with the second column

**Review by JuliaKirschenheuter — DISMISSED** [review]
unfortunately on a big screen i can see not centered message

**Comment by GretaD** [comment]
thirdcol

**Review by st3iny — APPROVED** [review]
Tested and works.

**Pull request merged**
