### PR TITLE
Add PHP8.1 support

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/groupware/issues/27

* [x] Update info.xml requirements
* [x] Update composer.json requirements
* [x] Update test matrix
* [x] Update lint matrix
* [x] Fix the code
  * [x] https://github.com/bytestream/Mail/pull/3
  * [x] https://github.com/bytestream/Mail/pull/2
  * [x] https://github.com/bytestream/Mail/pull/1
  * [x] https://github.com/bytestream/Imap_Client/pull/3
  * [x] https://github.com/bytestream/Imap_Client/pull/4
  * [x] https://github.com/bytestream/Mime/pull/2
  * [x] https://github.com/bytestream/Mime/pull/3
  * [x] https://github.com/bytestream/Support/pull/2
  * [x] https://github.com/bytestream/Stream_Filter/pull/2
* [x] Requires https://github.com/nextcloud/mail/pull/6532
* [ ] Requires https://github.com/nextcloud/mail/pull/6536
* [ ] Requires https://github.com/nextcloud/mail/pull/6537

### CODE REVIEW

**Comment by ChristophWurst** [comment]
The tests crash with xdebug but pass without. I'll wait for PHP8.1.4 https://www.php.net/ChangeLog-8.php and try again.

**Comment by ChristophWurst** [comment]
The action still uses 8.1.3.

**Comment by ChristophWurst** [comment]
https://launchpad.net/%7Eondrej/+archive/ubuntu/php/+index?batch=75&direction=backwards&memo=225&start=150 still only ships 8.1.3 and the action is built off that package source.

**Comment by ChristophWurst** [comment]
Something to fix in Horde

```
PHP Deprecated:  strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 147
PHP Deprecated:  strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 147
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 171
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 185
PHP Deprecated:  strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 147
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 171
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 185
PHP Deprecated:  strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 147
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 171
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 185
PHP Deprecated:  strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 147
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 171
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/christoph/workspace/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php on line 185
```

**Comment by ChristophWurst** [comment]
> https://launchpad.net/%7Eondrej/+archive/ubuntu/php/+index?batch=75&direction=backwards&memo=225&start=150 still only ships 8.1.3 and the action is built off that package source.

8.1.4 is available now. Time for another test.

**Comment by ChristophWurst** [comment]
Still fails.

**Comment by miaulalala** [comment]
https://github.com/nextcloud/server/issues/31212

FYI.

Detect encoding is not working as expected any longer, see https://github.com/php/php-src/issues/8279

**Comment by st3iny** [comment]
> Detect encoding is not working as expected any longer, see [php/php-src#8279](https://github.com/php/php-src/issues/8279)

Damn, what can we do about it? Wait for an upstream patch of php?

**Comment by ChristophWurst** [comment]
> Undefined array key 404

(╯°□°）╯︵ ┻━┻

**Comment by ChristophWurst** [comment]
Since this doesn't seem to be triggered by "linear" code, what if it's a shutdown function, a destructor or similar?

**Comment by ChristophWurst** [comment]
> assert($type instanceof Identifier || $type instanceof Name || $type instanceof ComplexType)
> Script phpunit -c tests/phpunit.unit.xml --testdox --debug -v handling the test:unit event returned with error code 2

it now also fails locally when I run ``XDEBUG_MODE=coverage composer run test:unit``

**Comment by ChristophWurst** [comment]
New plan: disable coverage for PHP8.1 for now.

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
