### PR TITLE
Add link picker

### PR DESCRIPTION
**Pull request by hamza221**
closes [#7986](https://github.com/nextcloud/mail/issues/7986)

## To do
- [x] Add picker to composer modal
- [x] Research what happens if the picker is used on Nextcloud 25. Hide the action?
- [x] BUG: resource selection modal has style issues. Heading and close button are moved to the left.

### CODE REVIEW

**Review by ChristophWurst — COMMENTED** [review]
Code looks good so far

Due to https://github.com/nextcloud/nextcloud-vue/issues/3696 I'm unable to build/test the code locally

**Comment by ChristophWurst** [comment]
Styling issues happen for me as well

Bildschirmfoto vom 2023-02-15 19-16-13

**Comment by ChristophWurst** [comment]
Icon size is not consistent in the multiselect

Bildschirmfoto vom 2023-02-15 19-18-26

**Comment by ChristophWurst** [comment]
Styles should come from the vue-richtext package. In Text they are loaded. In Mail they are not.

Text:
Bildschirmfoto vom 2023-02-15 19-22-05

**Comment by ChristophWurst** [comment]
:tada: 

Bildschirmfoto vom 2023-02-15 19-25-29

**Review by julien-nc — CHANGES_REQUESTED** [review]
Small nitpicking.
Looks good to me :+1:

**Review by ChristophWurst — APPROVED** [review]
Works :sparkles:

**Comment by ChristophWurst** [comment]
Squash your commits and :shipit:

**Pull request merged**
