### PR TITLE
Save autoconfigured account too

### PR DESCRIPTION
**Pull request by ChristophWurst**
Still think it's funny how nobody noticed this 🙈 

Well, at least now we've got some tests that make sure the account is always saved.

### CODE REVIEW

**Comment by skjnldsv** [comment]
To be fair I always end up with a timeout or 500 with the autoconfig. 🙈

**Comment by ChristophWurst** [comment]
> To be fair I always end up with a timeout or 500 with the autoconfig. 🙈

Known problem. And I even know the solution to it but still haven't found the time to implement …

**Comment by skjnldsv** [comment]
@ChristophWurst

OH! I always thought it was coming from my setup! ^_^

**Comment by ChristophWurst** [comment]
No it's because we iterate over dozens of possible configurations without any concurrency. That takes a lot of time. Hence I'd like to move some of that logic to the client where we can make use of async requests and this get a concurrent process.

**Comment by ChristophWurst** [comment]
Fix worked for me, is covered by unit tests and CI is green -> merging.

**Pull request merged**
