### PR TITLE
Fix composer change handling and save triggers

### LINKED ISSUE #5908: Empty message saved as draft
## How to reproduce

1) Set up an account
2) Open the composer

### Expected behavior

Nothing happens. Because I haven't put in any information. No recipient. No subject. No content. No attachments.

### Actual behavior

A draft is saved. Or at least so the UI tells me.

Bildschirmfoto von 2021-12-27 11-20-21

### Mail app

**Mail app version:** v1.12

### PR DESCRIPTION
**Pull request by st3iny**
Fix #5908 

cc @JuliaKirschenheuter Feel free to take over or close.

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
@st3iny thanks for this draft PR =)
I tested a different scenarios and this is probably not a perfect solution, but it is a working version. Please review )

**Review by GretaD — APPROVED** [review]
tested and works

**Comment by GretaD** [comment]
backport /stable1.12

**Pull request merged**
