### PR TITLE
Close the action menu after clicking an action

### LINKED ISSUE #9249: Action menu doesnt close after selecting an action
### Steps to reproduce

1. Open mail app and click "New message"
2. Open action menu on the composer and add a attachment
3. The attachment is added and the menu is still open

### Expected behavior

The action menu should be close

### Actual behavior
that is confusing.
Screenshot from 2024-01-17 10-17-44

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Found during design call with new employee

### PR DESCRIPTION
**Pull request by GretaD**
fixes #9249

### CODE REVIEW

**Comment by GretaD** [comment]
> This works for me only on firefox, and not chromium based browsers. Did you happen to test on those as well?

i tested it only on brave, which is chromium based.

**Review by GVodyanov — APPROVED** [review]
So I tested this on firefox and brave (worked), and chrome and chromium (didn't). Honestly not sure what is going on, all are on the latest version available to the arch package repositories. Either way looking into it, that would clearly be a critique to the `:close-after-click` prop of the `NcActionButton` component for not working properly, and not to this code, so I reckon it should be good.

**Comment by ChristophWurst** [comment]
> critique to the `:close-after-click` prop of the `NcActionButton` component for not working properly, and not to this code, so I reckon this PR should be good.

Best reported at https://github.com/nextcloud-libraries/nextcloud-vue/issues

**Review by st3iny — APPROVED** [review]

**Comment by st3iny** [comment]
Backports?

**Pull request merged**
