### PR TITLE
Users can edit recipients list while writing a message

### PR DESCRIPTION
**Pull request by sazanof**
**Hello!**  Link to the discussion of the previously closed PR (my mistake) - https://github.com/nextcloud/mail/pull/6261
!Peek 2022-05-11 11-18
I tried to take into account all the comments in the old PR.
THANKS!
Signed-off-by: Mikhail Sazanov <m@sazanof.ru>

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]
works well, thank you =)

**Comment by jancborchardt** [comment]
Just 1 feedback still design-wise, having 2 icons/actions there is confusing and we should have only 1:
- If there is anyone in cc or bcc field already, no action should hide that (so you don't forget about it)
- Expanding the recipients lists and showing cc/bcc can be toggled using the same button. Basically it's a "show me everything" vs "show me only lines with content, single line each" toggle.

And that icon/action should be in the "to" row since it relates to the recipients. It should not be in "from" as it does not relate to yourself.

Does that make sense @sazanof? :) The icon can be the expand/compact toggle you used.

**Comment by jancborchardt** [comment]
@sazanof almost! :) Once opened, when you click on the collapse toggle:
- If there is no one in cc or bcc: Collapse those rows too
- If there is anyone in cc or bcc: Leave that row displayed (cc if someone is in cc, bcc of someone is in bcc, both if someone in both)

**Comment by sazanof** [comment]
@jancborchardt so, the drum roll.....
Peek 2022-05-16 18-44
Like this?

**Comment by GretaD** [comment]
> by the way, the BCC is not loaded again (into the modal window) after saving the draft (test on `main` branch). `bcc: []` May be there is an open issue, i dont know...

a known issues, yes, #6458

**Comment by jancborchardt** [comment]
@sazanof awesome! This seems perfect indeed. :) A thing I’m wondering about, but it’s probably separate (Vue modal component?) is that everything jumps vertically since the size/height changes.

But I guess it’s not blocking this change? @skjnldsv @marcoambrosini

**Comment by sazanof** [comment]
@st3iny Done. I hope I did everything right =)

**Pull request merged**
