### PR TITLE
Change patched version of horde/Imap_client.

### PR DESCRIPTION
**Pull request by rodrigoaguilera**
I am getting 

Undefined index: H at /var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Data/Sync.php#209

in my log all the time. This is an attempt to solve that.
I integrated in my branch all the changes from icewind1991 + my fix

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Hey, @rodrigoaguilera!

Thanks a lot for your fix. Great to see this issue being fixed. Since the [patch](https://github.com/horde/Imap_Client/pull/3) by @icewind1991 has been integrated into the upstream Horde library I'd like to ask you to submit your patch upstream as well.

Would that be possible?

> First-time contributor

Congrats on your first contribution :fireworks:

**Comment by rodrigoaguilera** [comment]
Done 
https://github.com/horde/Imap_Client/pull/4
I completely forgot the step of submitting the PR

Please feel free to integrate the fix in any other fork that you deem more proper.

**Comment by ChristophWurst** [comment]
Thanks! I subscribed to your upstream PR to get notified about changes and will hopefully update the upstream Horde lib soonish when it incorporates your fix.

**Comment by ChristophWurst** [comment]
I will close this PR for now. When the upstream patch lands in a new release of the horde client package, we will update to that anyway, so these changes will make their way into this app eventually :wink:

**Comment by ChristophWurst** [comment]
@rodrigoaguilera thank you for your (first-time) contribution, I appreciate you looking into this specific bug that is only reproducible with your provider.

**Pull request closed without merging**
