### PR TITLE
Increase the database field length for storing long passwords.

### LINKED ISSUE #340: Account Creation error: 64-byte password
### Steps to reproduce
1. Attempt to create account for e-mail account secured with 64B password

### Expected behaviour
Account should be created, e-mail server accessed.

### Actual behaviour
Creating account failed: An exception occurred while executing 'INSERT INTO ...: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'inbound_password' at row 1

### Mail app

**Mail app version:** 0.6.2

**Mailserver or service:** Gmail

**Transport security - IMAP:** SSL

**Transport security - SMTP:** SSL

**Number of accounts:** First

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0.whatever

**Version:** 11.0.1

**Updated from an older version or fresh install:** Older

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #340.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> #340 said to update info.xml as well to trigger a migration, or am I mistaken?

Yup, that is necessary. Good catch :)

**Comment by toolstack** [comment]
> > #340 said to update info.xml as well to trigger a migration, or am I mistaken?
>>
> Yup, that is necessary. Good catch :)
>
I was going to add it but didn't know what value it should be or if it was updated during the release process.

**Comment by cmtonkinson** [comment]
Thanks all for your work on this; I'm willing to help finish this out if I can be of assistance.

**Comment by ChristophWurst** [comment]
The version in info.xml is already higher than the one of the latest release -> this can be merged 🚀

**Comment by ChristophWurst** [comment]
CI failures are unrelated it seems

**Comment by toolstack** [comment]
:+1:

**Pull request merged**
