### PR TITLE
re-enable ProxyControllerTest::testProxy as it's mockable now

### PR DESCRIPTION
**Pull request by ChristophWurst**
@nickvergessen @irgendwie @nextcloud/mail reasy to review ;-)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@tahaalibra review please ;-)

**Comment by tahaalibra** [comment]
https://github.com/nextcloud/mail/blob/36a173c57fe90cc6ed923834b06805a267590ddc/tests/controller/proxycontrollertest.php#L52

method 'getClient' in the setup is raising a warning, is it used somewhere?

**Comment by tahaalibra** [comment]
rest of it looks ok

**Comment by ChristophWurst** [comment]
ah right, that method does not exist. For some reason my local test runs did not show any warnings. Should be fixed now

**Comment by ChristophWurst** [comment]
cc @llamallama, this is an easy one to review ;-)

**Comment by nickvergessen** [comment]
:+1:

**Comment by ChristophWurst** [comment]
LGTM is broken due to GitHub's new review feature :'-(

**Pull request merged**
