### PR TITLE
Replace tune icon with filter icon

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Fixes: #9942 

Check commit.

**I don't have a test environment. Test from reviewers need.**

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
The icon component is not registered on the Vue component

**Comment by Jerome-Herbinet** [comment]
> The icon component is not registered on the Vue component

@ChristophWurst this is new for me ; how to do that ? Can you help me ?

**Comment by ChristophWurst** [comment]
Delete https://github.com/nextcloud/mail/blob/295a1dcf4c98da0ca46a03847c5bb9a320295f03/src/components/SearchMessages.vue#L299 and replace Tune with FilterIcon at https://github.com/nextcloud/mail/blob/295a1dcf4c98da0ca46a03847c5bb9a320295f03/src/components/SearchMessages.vue#L321

**Review by jancborchardt — CHANGES_REQUESTED** [review]
@ChristophWurst @Jerome-Herbinet I think it will have to be FilterVariantIcon so it is going to be the list/filter icon (not the funnel) as per https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:filter_list:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=filter ?

**Comment by Jerome-Herbinet** [comment]
> Delete
> 
> https://github.com/nextcloud/mail/blob/295a1dcf4c98da0ca46a03847c5bb9a320295f03/src/components/SearchMessages.vue#L299
> and replace Tune with FilterIcon at
> 
> https://github.com/nextcloud/mail/blob/295a1dcf4c98da0ca46a03847c5bb9a320295f03/src/components/SearchMessages.vue#L321

@ChristophWurst OK

**Comment by Jerome-Herbinet** [comment]
@jancborchardt could you test it ?

**Review by jancborchardt — COMMENTED** [review]
@Jerome-Herbinet as per my comment before, the icon probably needs to be "FilterVariant".

It should _not_ look like this [funnel icon](https://pictogrammers.com/library/mdi/icon/filter/), but rather like this [list filter icon](https://pictogrammers.com/library/mdi/icon/filter-variant/).

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet as per my comment before, the icon probably needs to be "FilterVariant".
> 
> It should _not_ look like this [funnel icon](https://pictogrammers.com/library/mdi/icon/filter/), but rather like this [list filter icon](https://pictogrammers.com/library/mdi/icon/filter-variant/).

OK @jancborchardt ; to make finding icons easier, can you tell me how (and/ore where) you easily browse your entire Nextcloud icon collection to select the right one (AFAIK I can't open files viewed as an image...).

**Comment by jancborchardt** [comment]
@Jerome-Herbinet as far as I know, that is https://pictogrammers.com/library/mdi/ – but a frontender would have to help here.

**Review by st3iny — COMMENTED** [review]
Works so far. Just needs the correct icon, as Jan mentioned.

grafik

**Comment by ChristophWurst** [comment]
What was force pushed? The icon is still to be replaced, right?

**Comment by Jerome-Herbinet** [comment]
> What was force pushed? The icon is still to be replaced, right?

Yes, forget it, I still have to make discussed changes.

**Review by jancborchardt — APPROVED** [review]
Seems good – don’t know about the icon naming conventions but it seems the variables usually don’t have "Icon" appended, so you could call it simply "FilterVariant" instead of "FilterVariantIcon"?

**Review by st3iny — APPROVED** [review]
Tested and works. Thank you very much :)

**Pull request merged**
