### PR TITLE
Moving mails

### PR DESCRIPTION
**Pull request by ChristophWurst**
Continuation of https://github.com/nextcloud/mail/pull/90 (closed accidentally and force-pushed).

TODO:
- [x] special folders hack (e.g. favourites search folder)
- [x] visual drop feedback
- [x] add drag/drop scopes to prevent cross-account moves
- [ ] message removal animation
- [x] subfolders are broken

fixes https://github.com/nextcloud/mail/issues/24 :money_with_wings: :moneybag: :dollar: :dancer: 
fixes https://github.com/nextcloud/mail/issues/201

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Alright. Basic move operations seem to work now. Also for nested folders. @Gomez @jancborchardt @nextcloud/mail check it out. Let me know if you experience any bugs. If you have no objections I'd like to add the visual feedback in a follow-up PR.

**Comment by ChristophWurst** [comment]
I've made some small and not necessarily related changes:
* removed more of the useless client-side cache.
* don't trigger reload folders if we have fetched them already.
* don't remove message pages. reload removes them however, because the server-side impl limits to 20 messages.

**Comment by ChristophWurst** [comment]
@nextcloud/mail please review. I'd like to push a new release ASAP and this would be a nice feature for it :-)

**Comment by jancborchardt** [comment]
Hey @Quix0r @plastikschnitzer @seal20 @pierreozoux @MeCias @djibux @GIT-STATA @pierreozoux please check if moving mails works for you with this pull request. :)

**Comment by plastikschnitzer** [comment]
I tried the latest nightly built version of the mail app. After uploading files to the server, the mail app is not loading any more, just a blank page.

**Comment by ChristophWurst** [comment]
@plastikschnitzer weird. do you see anything related in the server log or browser log? I assume you've used NC10 right?

**Comment by irgendwie** [comment]
I am able to move mails between folders :+1: so the basic functionality works :tada: 

Bugs:

- [ ] Sometimes the mail icon freezes and stays at the current position (not sure when)
- [ ] Drag the icon over to the mail body (the mail icon stays at the list), release the mouse button (on the mail body) and go back to the mail ist -> you now have a floating mail icon next to your cursor
-  (Maybe other small glitches)

**Comment by ChristophWurst** [comment]
> Sometimes the mail icon freezes and stays at the current position (not sure when)

Check your browser's log. This happened to me too but only when there was an error in the js code.

> Drag the icon over to the mail body (the mail icon stays at the list), release the mouse button (on the mail body) and go back to the mail ist -> you now have a floating mail icon next to your cursor

So you've dropped the message on an element that is not intended for dropping element. Interesting, I think I did not test that 🙈

**Comment by irgendwie** [comment]
> So you've dropped the message on an element that is not intended for dropping element. Interesting, I think I did not test that :see_no_evil:

Think of a user, wanting to move the mail, readin it again for a short amount of time and simply doesn't want to move it anymore and releasing the cursor

**Comment by Quix0r** [comment]
#202 still lacks code-review (as I can see?).

**Comment by ChristophWurst** [comment]
> #202 still lacks code-review (as I can see?).

No, it doesn't. I has been reviewed and merged already :-) https://github.com/nextcloud/mail/pull/202#event-872486940

**Comment by Quix0r** [comment]
Okay. :-)

**Comment by jancborchardt** [comment]
Sooo, what's missing here? The message vanish animation and the fix of the floating icon when draghed somewhere else?

@Quix0r did you review this too? :)

**Comment by ChristophWurst** [comment]
> So you've dropped the message on an element that is not intended for dropping element. Interesting, I think I did not test that 🙈

Tested: mail icon moves back and nothing is moved ✔️ 

> Edit: Move the cursor (moving mail) to the border of your window -> endless scrolling 😄 @ChristophWurst

Confirmed, but I'm unable to find an easy solution. Any idea how we could prevent that?

**Comment by jancborchardt** [comment]
@ChristophWurst so is this testable or in a usable state so we can merge it? The release was done ;)

**Comment by ChristophWurst** [comment]
@onny @GuillaumeAmat @jancborchardt this is in a mergable state now IMO. The basic functionality works, I've updated the branch and it works on FF and Chromium. Please give it a test :-)

**Comment by ChristophWurst** [comment]
> coverage/coveralls — Coverage decreased (-0.5%) to 32

Will add some tests when I'm in the  mood 🙊 🙉 🙈 probably in another PR

**Comment by onny** [comment]
So far it works good for me. Some kind of animation is missing though. Further, there is no possibility to move mails with the mobile interface.

**Comment by ChristophWurst** [comment]
> Further, there is no possibility to move mails with the mobile interface.

Yup, we have to think about that too. Drag-and-drop is primarily used for desktop use. We'll have to find another solution for mobile. Suggestions are very welcome :-)

**Comment by ChristophWurst** [comment]
> So far it works good for me. Some kind of animation is missing though.

Known issue. And as stated above, I will work on that in a follow-up PR. Counting your test as positive review and therefore I'm merging this now. Thanks you!

**Comment by plastikschnitzer** [comment]
Concerning moving mails on mobile devices: I have 2 ideas:
1. Give the possibility to select (multiple) emails and have a dropdown of options like delete, move, mark as …, and others.
2. Moving mails to the side offers the options from the dropdown options of solution 1 behind the email. Seen in the Samsung Mail app, see my screenshot here: 
screenshot_20161218-174638

Best regards,
Plastikschnitzer

**Comment by ChristophWurst** [comment]
Hey @plastikschnitzer,

thanks for sharing your thoughts on this :-)

> Moving mails to the side offers the options from the dropdown options of solution 1 behind the email. Seen in the Samsung Mail app, see my screenshot here, I moved the mail in the middle of the scrreenshot to the side, now I can select the options:

This is a nice gesture, but I'm afraid it's hard to implement it in a web app taking into account that those gestures do not work as fluent in web as on native applications.

> Give the possibility to select (multiple) emails and have a dropdown of options like delete, move, mark as …, and others.

I totally agree on this, we have to add that add some point.

We should continue the discussion in a new ticket, otherwise it could get lost. @plastikschnitzer could you please open a new issue and describe your ideas there?

**Comment by plastikschnitzer** [comment]
OK, see #255 

:-)

**Comment by pafcioooo** [comment]
Reading this thread I suppose this functionality is working.
But I am on NC 11 with mail 0.6.2 I I have no clue how to move messages - I tried clicking and holding, right clicking, searching for some buttons...
Please advice.

**Comment by MariusBluem** [comment]
Well ... This is merged, but not in a release yet. The milestone for this is `0.6.3` as you can see above 😉

**Comment by pafcioooo** [comment]
@MariusBluem, thank you:-)

**Comment by plastikschnitzer** [comment]
I tested it in the [pre-0.7 release](https://github.com/nextcloud/mail/releases/tag/nightly-20170823) – moving mails in between folders of one account works fine. Moving from the combined inbox does not work, the little mail icon remains at the place you dropped the email, so its not obvious to the user what actually happens here. It would be better if the animation would be like the case when you drop the email somewhere where its not allowed (mail symbol moving back to the initial location).

But so far great feature, love it! Makes this app much more usable!

**Pull request merged**
