### PR TITLE
Add SMTP integration tests

### PR DESCRIPTION
**Pull request by ChristophWurst**
This adds a simple integration test for our mail transmission code. It's very basic now but can be extended to test more complex scenarios like attachments.

~~I'm waiting to get a free account on mailtrap so that we can easily test against a real SMTP server.~~ Let's use a local docker image instead.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@nextcloud/mail easy one to review :)

**Comment by ChristophWurst** [comment]
As a nice side effect, the php testing coverage increased by three percent 🚀

**Comment by ChristophWurst** [comment]
Only effects testing and CI is happy, hence I'm merging this now (without any approval by a second developer).

**Comment by lcalaresu** [comment]
Oh oups, didn't see it was to be reviewed.
I actually tried it yesterday and it was fine to me though ;)
Great job :rocket:

**Comment by ChristophWurst** [comment]
Cool, thanks! :)

**Pull request merged**
