### PR TITLE
Simplify the bug report issue template

### PR DESCRIPTION
**Pull request by ChristophWurst**
For many reports we don't really care about the detailed information like logs. And most people don't get how to access those anyway, so I'd rather not ask for it unless really required and then I can answer with a saved reply.

cc @nextcloud/mail

### CODE REVIEW

**Comment by jancborchardt** [comment]
Very good call! :) You can always save the other parts as a [saved reply](https://github.com/settings/replies) so you can quickly ask for further info.

**Comment by ChristophWurst** [comment]
Yep, that is exactly what I had written in the description :see_no_evil: Maybe it just wasn't clear :wink:

**Comment by jancborchardt** [comment]
Haha, busted! … well I guess it is true what they say about people not reading. :D I did scan and probably stopped after the middle of the second row.

**Comment by ChristophWurst** [comment]
I guess you just scanned without active thinking and then your brain was like "hey, I have this idea..." :wink:

**Pull request merged**
