### PR TITLE
Show active state for mailbox

### LINKED ISSUE #8022: Active mailbox has no hover state any more
### Steps to reproduce

The active mailbox that is currently selected has no hover state in the lefthand sidebar any more:

The actual logic still works, the .active class is still here, but the styling seems weird: 

image

Regression from https://github.com/nextcloud/mail/pull/7707

### Mail app version

2.3.0-alpha.4

### PR DESCRIPTION
**Pull request by GretaD**
fixes #8022

after
Screenshot from 2023-02-20 16-33-11

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by hamza221 — APPROVED** [review]

**Comment by GretaD** [comment]
> @GretaD no backport necessary?

no, the initial pr was released on 2.2

**Comment by ChristophWurst** [comment]
main is 2.3, so we backport to stable2.2?

**Comment by GretaD** [comment]
> ~main is 2.3, so we backport to stable2.2?~ [e3b7466](https://github.com/nextcloud/mail/commit/e3b74663ac814061bae886a6d175ae93055a6e40) is not in 2.2

https://github.com/nextcloud/mail/commit/e3b74663ac814061bae886a6d175ae93055a6e40 is relesead on https://github.com/nextcloud-releases/mail/releases/tag/v2.2.3

**Comment by GretaD** [comment]
> ~main is 2.3, so we backport to stable2.2?~ [e3b7466](https://github.com/nextcloud/mail/commit/e3b74663ac814061bae886a6d175ae93055a6e40) is not in 2.2

right, got confused with the https://github.com/nextcloud-releases/mail/releases/tag/v2.2.3 

- Unread counter position for outbox

**Pull request merged**
