### PR TITLE
fix: new message button misalignment

### LINKED ISSUE #10417: when theres no message selected, the 'new message' button is misplaced
### Steps to reproduce

1. Open mail app
2. Dont select any messages
3. See new message button placed in the end of the page instead below the empty content

### Expected behavior

Placed correctly

### Actual behavior

Image

### Mail app version

_No response_

### Nextcloud version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #10417
Screenshot from 2024-11-27 14-21-10

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Mind linking the ticket this PR fixes?

**Comment by GretaD** [comment]
> Has #10272 caused this regression?
> 
No.



> let's use that please

yes, thanks for checking, should have checked it myself, but when i inspected i didnt see the styling we have on our file, so i assumed some server stuff overlapped.

**Review by ChristophWurst — APPROVED** [review]
Clean and simple 🫧

**Pull request merged**
