### PR TITLE
Update mail.css

### PR DESCRIPTION
**Pull request by blackcrack**
update .submit-message-wrapper 
give a z-index and put it on top and not over the messages ;)
then it is not every bottom in the corner, nope, on top,
where nobady it is disturb and over the 
mail-message-header have z-index: 100
so fit at all :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@blackcrack please again, give a proper title to the pull request and provide a before & after screenshot so we can see what is actually intended to be changed by this. :)

**Comment by jancborchardt** [comment]
@blackcrack ist das hier das gleiche wie https://github.com/nextcloud/mail/pull/304? Oder gehört es dazu?

**Comment by jancborchardt** [comment]
@ChristophWurst or other @nextcloud/mail folks, what do you think about this change?

**Comment by ChristophWurst** [comment]
I don't get what this PR is about. Due to lack of activity I'm closing this now.

**Pull request closed without merging**
