### PR TITLE
Alias provisioning: Skip alias when identical to account email

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
close or finish?

**Comment by ChristophWurst** [comment]
> [kesselb](/kesselb) added this to the [v2.1.0](/nextcloud/mail/milestone/123) milestone [22 minutes ago](#event-7664553899)

https://github.com/nextcloud/mail/pull/7493 :D

**Review by ChristophWurst — APPROVED** [review]
Clean

**Review by miaulalala — APPROVED** [review]
LGTM

**Pull request merged**
