### PR TITLE
:bug: Remove the concatenation from query builder and

### PR DESCRIPTION
**Pull request by miaulalala**
replace with a comma instead...

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]
:1st_place_medal:

**Comment by miaulalala** [comment]
Can't merge bc integration tests are not afjusted yet.

**Comment by ChristophWurst** [comment]
> Can't merge bc integration tests are not afjusted yet.

Could you adjust them please?

**Comment by miaulalala** [comment]
> > Can't merge bc integration tests are not afjusted yet.
> 
> Could you adjust them please?

https://github.com/nextcloud/mail/pull/7306

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/commit/2dcf8b9576326c2bf6e42d63894e2c605803c265 was only added for v2.0

**Pull request merged**
