### PR TITLE
Bump CKEditor packages to v34

### PR DESCRIPTION
**Pull request by ChristophWurst**
This needed a bit of adjustment due to the new Editor.isReadOnly

https://ckeditor.com/docs/ckeditor5/latest/updating/migration-to-34.html

https://github.com/ckeditor/ckeditor5-vue2/blob/master/CHANGELOG.md#300-2022-04-12

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:ping_pong: easiest review you'll see today

**Review by GretaD — APPROVED** [review]

**Comment by GretaD** [comment]
should i work on the adjustments?

**Comment by ChristophWurst** [comment]
adjustments?

**Comment by ChristophWurst** [comment]
They are done with this PR.

**Comment by GretaD** [comment]
ohh, "needed" not "needs"..sorry :v:

**Pull request merged**
