### PR TITLE
Fix new message button header transparency and position

### PR DESCRIPTION
**Pull request by meichthys**
Fixes transparency on new message button.

Current:
image

Changes:
image

### CODE REVIEW

**Comment by meichthys** [comment]
@GretaD I'm on  2.0.0-beta.6 using the built in dark theme on nextcloud.
I've tried both dark and light themes in firefox without any difference.

**Comment by meichthys** [comment]
> Looks like [nextcloud/richdocuments#2426](https://github.com/nextcloud/richdocuments/issues/2426)

Yes, this looks right. I noticed some office css being applied but wasn't sure if that was expected or not.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/richdocuments/pull/2432 should fix the office style leaks

**Comment by ChristophWurst** [comment]
Nevertheless thanks a lot for taking care of this design bug, @meichthys! Highly appreciated :)

**Comment by meichthys** [comment]
NP 👍
Sometimes I feel like i must be the only one using Mail as a daily driver, but I'm going to stick it out!

**Pull request closed without merging**
