### PR TITLE
Show recipients in each thread envelope

### PR DESCRIPTION
**Pull request by st3iny**
Ref #4258 

Here is my suggestion for showing the recipients of individual envelopes in threads. The design is up for discussion.

cc @StCyr @ChristophWurst 

---

**EDIT:** removed outdated gif

### CODE REVIEW

**Comment by StCyr** [comment]
https://github.com/nextcloud/mail/issues/4258#issuecomment-782000007

    another important issue is that you don´t see who is in "from" and who is in "cc".
    for example in gmail you have on the right side of this email list a small arrow.
    when you click on this arrow you see in a popover who is in "from" and who is in "cc".
    at the moment you don´t know if you where in cc or not.

**Comment by st3iny** [comment]
I added a separate line for showing cc recipients. However, I can't come up with a nice way to add a toggle for the additional infos (e.g. cc).

Screenshot_2021-02-22 Mail - Nextcloud(1)

**Comment by StCyr** [comment]
I find it nice but it may take a lot of space on small screens

**Comment by ChristophWurst** [comment]
Take a look at [this](https://cdn.vox-cdn.com/thumbor/_l8F_fXQvqBWZUiOqQrL3SH2AcE=/0x0:2400x1606/2070x1164/filters:focal(1018x172:1402x556):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/66934530/Hey_Imbox.0.png). They have also a list of participants of a thread/message but only with the avatars. We discussed a few times that this is also our goal for the thread participants on top – how about we do the same for the recipients of an individual message?

**Comment by kinimodmeyer** [comment]
can we not make such a icon with the information?
a easy accessible icon would be sufficient:

gm

please also don´t forget to implement the BCC.
at the moment you can not see if you are in BCC.
gmail shows it this way:

gm2

**Comment by st3iny** [comment]
> please also don´t forget to implement the BCC.
at the moment you can not see if you are in BCC.

AFAIK, you cannot disclose the BCC of a received email.

**Comment by st3iny** [comment]
> Take a look at this. They have also a list of participants of a thread/message but only with the avatars. We discussed a few times that this is also our goal for the thread participants on top – how about we do the same for the recipients of an individual message?

We could do that. Our RecipientBubble component uses the UserBubble component from nextcloud-vue. I could implement a new parameter for UserBubble which allows to omit the label span and just show an avatar.

I moved the avatar header to its own component (ThreadAvatarHeader) so all changes will be propagated to both participant/recipient lists.

**Comment by kinimodmeyer** [comment]
> > please also don´t forget to implement the BCC.
> > at the moment you can not see if you are in BCC.
> 
> AFAIK, you cannot disclose the BCC of a received email.

when the sender don´t fill out the "to" but the sender fills out the "bcc" then the email has no "to".
in that case it would be good when nextcloud mail "not lying" and also don´t display a "to".
(have a look at the picture i posted)

**Comment by st3iny** [comment]
@kinimodmeyer Now I get it. Currently, my version is working like Gmail: It shows an empty `To:` line when there are only BCCs.

Take a look at this example (sent using only BCC):
Screenshot_2021-03-04 Mail - Nextcloud(1)

**Comment by st3iny** [comment]
@kinimodmeyer Hmm, I guess showing an empty to line is kind of pointless. I pushed a commit that removes the whole line when it's empty (just like CC).

**Comment by jancborchardt** [comment]
How about we only show that block for each thread envelope if it _differs_ from the main thread?
We could even indicate what the difference is, e.g. "Richard Steinmetz was added" or "Christoph Wurst was removed", which would be great for security even, if someone is added.

This would be much more useful, since otherwise if we just show it for every single envelope, it’s mostly noise repeating the same info over and over again?

**Comment by ChristophWurst** [comment]
@st3iny is this still blocked?

**Comment by st3iny** [comment]
> @st3iny is this still blocked?

We need to figure out how to implement/design it properly. But it's not blocked by dependencies or other PRs.

**Comment by jancborchardt** [comment]
> How about we only show that block for each thread envelope if it _differs_ from the main thread? We could even indicate what the difference is, e.g. "Richard Steinmetz was added" or "Christoph Wurst was removed", which would be great for security even, if someone is added.
> 
> This would be much more useful, since otherwise if we just show it for every single envelope, it’s mostly noise repeating the same info over and over again?

@st3iny what do you think about my comment above?

**Comment by ChristophWurst** [comment]
@st3iny :eyes: :smile:

**Comment by ChristophWurst** [comment]
so

**Comment by ChristophWurst** [comment]
Design specs added to https://github.com/nextcloud/mail/issues/4258#issuecomment-1740566252. Let's do this

**Pull request closed without merging**
