### PR TITLE
Render full links in plain text bodies

### PR DESCRIPTION
**Pull request by st3iny**
We should always show the full link when converting plain text link to `<a>` tags.

## Before
Screenshot 2022-01-18 at 14-23-34 E-Mail - Nextcloud

## After
Screenshot 2022-01-18 at 14-23-50 E-Mail - Nextcloud

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]
LGTM!

**Comment by miaulalala** [comment]
PHP tests fail :)

**Comment by st3iny** [comment]
Tests should be fixed now.

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
