### PR TITLE
Extract content components to nextcloud-vue

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires a nextcloud-vue with https://github.com/nextcloud/nextcloud-vue/pull/382

### CODE REVIEW

**Comment by ChristophWurst** [comment]
```
Hash: 847eeae289e19fd43d9a
Version: webpack 4.39.2
Time: 8005ms
Built at: 26.08.2019 14:06:07
                             Asset      Size  Chunks                    Chunk Names
    mail.0.6a08f95f244f8c39838a.js   436 KiB       0  [emitted]  [big]  
mail.0.6a08f95f244f8c39838a.js.map   345 KiB       0  [emitted]         
    mail.1.1445d83a96d51de611b1.js  19.8 KiB       1  [emitted]         
mail.1.1445d83a96d51de611b1.js.map  74.3 KiB       1  [emitted]         
    mail.2.302a884b24a786c5b4c6.js    24 KiB       2  [emitted]         
mail.2.302a884b24a786c5b4c6.js.map    85 KiB       2  [emitted]         
    mail.4.4f6beb5fe34fdfd26992.js   635 KiB       4  [emitted]  [big]  
mail.4.4f6beb5fe34fdfd26992.js.map     2 MiB       4  [emitted]         
    mail.5.77265ce2d15384548ab3.js  74.3 KiB       5  [emitted]         
mail.5.77265ce2d15384548ab3.js.map   246 KiB       5  [emitted]         
    mail.6.a791acdd31d5259c7a78.js  13.3 KiB       6  [emitted]         
mail.6.a791acdd31d5259c7a78.js.map    17 KiB       6  [emitted]         
    mail.7.df87702942600f05f4d7.js  11.4 KiB       7  [emitted]         
mail.7.df87702942600f05f4d7.js.map  42.4 KiB       7  [emitted]         
    mail.8.875b8afa90aca3cf22c7.js  1.21 KiB       8  [emitted]         
mail.8.875b8afa90aca3cf22c7.js.map  2.24 KiB       8  [emitted]         
                           mail.js   325 KiB       3  [emitted]  [big]  main
                       mail.js.map  1.81 MiB       3  [emitted]         main
Entrypoint main [big] = mail.js mail.js.map
```
on master vs
```
Hash: 57b6aaed9bb6ab6e6398
Version: webpack 4.39.2
Time: 8955ms
Built at: 26.08.2019 14:07:09
                             Asset      Size  Chunks                    Chunk Names
    mail.0.691a26357356692a7d90.js   564 KiB       0  [emitted]  [big]  
mail.0.691a26357356692a7d90.js.map  1.05 MiB       0  [emitted]         
    mail.2.180f0c40c1d3639046c3.js   965 KiB       2  [emitted]  [big]  
mail.2.180f0c40c1d3639046c3.js.map  2.65 MiB       2  [emitted]         
    mail.3.92fff19bb5417a3b9983.js  74.4 KiB       3  [emitted]         
mail.3.92fff19bb5417a3b9983.js.map   247 KiB       3  [emitted]         
    mail.4.78e4b321fd85fbe3ccc2.js  37.2 KiB       4  [emitted]         
mail.4.78e4b321fd85fbe3ccc2.js.map   131 KiB       4  [emitted]         
    mail.5.00ad0749c2d7123a6443.js  15.3 KiB       5  [emitted]         
mail.5.00ad0749c2d7123a6443.js.map  45.3 KiB       5  [emitted]         
    mail.6.20169d3143a6a671d553.js  14.3 KiB       6  [emitted]         
mail.6.20169d3143a6a671d553.js.map    49 KiB       6  [emitted]         
    mail.7.52d363b92123d9921609.js  16.1 KiB       7  [emitted]         
mail.7.52d363b92123d9921609.js.map  66.1 KiB       7  [emitted]         
                           mail.js   327 KiB       1  [emitted]  [big]  main
                       mail.js.map  1.82 MiB       1  [emitted]         main
Entrypoint main [big] = mail.js mail.js.map
```
here. it actually got worse

**Comment by skjnldsv** [comment]
Weird!

**Comment by skjnldsv** [comment]
Capture d’écran_2019-08-26_16-44-22

**Comment by skjnldsv** [comment]
Much better now
Capture d’écran_2019-08-26_16-55-24

**Pull request merged**
