### PR TITLE
Handle itinerary times with and without timezones

### PR DESCRIPTION
**Pull request by vkrause**
Event reservations and calendar event generation will need similar fixes, I'll look into that once my local setup allows me to test those properly.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Sure

**Comment by kesselb** [comment]
@vkrause thanks :+1: 

Could you have a look at the eslint warnings for the code style?

**Comment by vkrause** [comment]
> Could you have a look at the eslint warnings for the code style?

Should be taken care of now, sorry about that.

**Pull request merged**
