### PR TITLE
Investigate integration tests

### PR DESCRIPTION
**Pull request by st3iny**

### CODE REVIEW

**Comment by st3iny** [comment]
> Did they also pass for you on your dev env?

Didn't test yet.

I printed the exception and it is thrown in https://github.com/nextcloud/server/blob/8aea25b5b92dac105f7e862470ee0dcf0e876615/lib/private/Http/Client/Client.php#L191.

**Comment by ChristophWurst** [comment]
Could be related to https://github.com/nextcloud/server/pull/34852 then

**Comment by ChristophWurst** [comment]
\OC\Http\Client\DnsPinMiddleware::addDnsPinning is wrong

**Comment by st3iny** [comment]
Yeah, the exception is thrown in https://github.com/nextcloud/server/blob/c00e590a4f0bd1d7308c5f7b24ca55e3e9c4df78/lib/private/Http/Client/DnsPinMiddleware.php#L139.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/34852/files#r1016569369

**Pull request closed without merging**
