### PR TITLE
Improve HTTP caching

### PR DESCRIPTION
**Pull request by ChristophWurst**
* More immutable cache headers
* Cache itinerary responses
* Cache quota
* Cache contacts integration lookups
* Cache recipient auto completion lookups
* Cache auto config lookups

## How to test
1) Open the app with master
2) Open a mailbox
3) Open a thread
4) Open another thread
5) Go back to the first thread -> this should feel a bit slow

Then switch to this branch and do the same steps.

It should go without saying but don't have your browser cache disabled or you won't see a difference.

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Tested and the app feels quicker. I also tested the recipient search and the responses are properly cached.

The code looks good too.

**Review by CarlSchwan — APPROVED** [review]
Yeah for more caching!

**Comment by ChristophWurst** [comment]
This has to work

**Pull request merged**
