### PR TITLE
Add "download all attachments" function

### PR DESCRIPTION
**Pull request by jakobsack**
This change allows users to download all attachments of an email in a single zip file (see #552)
This currently depends on branch zipresponse of nextcloud/server

### CODE REVIEW

**Comment by jakobsack** [comment]
After merge of nextcloud/server#10967 this PR depends on nextcloud trunk (to be nextcloud 15)

**Comment by ChristophWurst** [comment]
- [ ] Requires Nextcloud 15+

**Comment by ChristophWurst** [comment]
>     * Requires Nextcloud 15+

Forgot to update this :wink: 

I think this needs a bit of an update now with the new Vue frontend.

**Comment by ChristophWurst** [comment]
Closing due to lack of activity. @jakobsack we can still re-open if you want to finish this later :)

**Pull request closed without merging**
