### PR TITLE
fix(outbox): select correct account/alias when opening messages

### LINKED ISSUE #6701: Editing outbox message selects wrong account/alias
### Steps to reproduce

1. Configure two accounts
2. Compose an email from account 2 (the one shown second in the dropdown)
3. Schedule the message
4. Go to the outbox
5. Open the message

### Expected behavior

I see that account 2 is still selected.

### Actual behavior

Account 1 is selected.

### Mail app version

v1.13

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes #6701 

Add comparation of alias id with alias account

### CODE REVIEW

**Comment by GretaD** [comment]
this looks good, but i cannot reproduce the initial problem anymore on v2.1.0-rc1. Can you reproduce it Julia?

**Comment by JuliaKirschenheuter** [comment]
> this looks good, but i cannot reproduce the initial problem anymore on v2.1.0-rc1. Can you reproduce it Julia?

yes, i can. this branch haven't been merged

**Comment by ChristophWurst** [comment]
@GretaD @st3iny could you have another look? The code looks good

**Comment by JuliaKirschenheuter** [comment]
oh still open ;\

**Review by GretaD — APPROVED** [review]
i still cannot reproduce the initial problem, so i have the same result on master and on this pr, but this pr doesnt break anything so let get  it in for people that can reproduce the initial proplem.

**Review by st3iny — CHANGES_REQUESTED** [review]
Does not fix the issue. The field `composerData.aliasId` was always null during my testing.

**Review by st3iny — APPROVED** [review]

**Comment by st3iny** [comment]
Setup: 2 accounts with 2 aliases each (default + custom alias)

## Steps
1. Compose a new message.
2. Select some alias.
3. Send it later at some point in the future.
4. Go to outbox and open the message.
5. The selected account/alias should match the original one (which was selected in step 2).

## Test Cases
1. Default account with default alias.
6. Default account with second alias.
7. Second account with default alias.
8. Second account with second alias.

All 4 cases work as expected.

**Pull request merged**
