### PR TITLE
Revert "Users can clear their mailboxes"

### PR DESCRIPTION
**Pull request by miaulalala**
Reverts nextcloud/mail#6286

Still waiting for feedback from @ChristophWurst to see if the bypassing of the trashbin is ok (Context: https://github.com/nextcloud/mail/pull/6286#pullrequestreview-1010395565)

If it is, we can close this PR.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Still waiting for feedback from @ChristophWurst to see if the bypassing of the trashbin is ok (Context: [#6286 (review)](https://github.com/nextcloud/mail/pull/6286#pullrequestreview-1010395565))

@GretaD please research if a specification for the correct handling exists (RFC) or check how Gmail, Roundcube and Thunderbird handle it.

**Comment by GretaD** [comment]
> @GretaD please research if a specification for the correct handling exists (RFC) or check how Gmail, Roundcube and Thunderbird handle it.

The right way to do it is to send everything to trashbin first, and from there to permanently delete it. In all the apps i checked, its a 2 step action.

**Review by ChristophWurst — COMMENTED** [review]
:+1:

**Comment by ChristophWurst** [comment]
@sazanof this means https://github.com/nextcloud/mail/pull/6286 has to be re-done so it goes through the trash bin.

**Comment by sazanof** [comment]
@ChristophWurst  No problem!I implement this functionality

**Pull request merged**
