### PR TITLE
Makes sure email subject is valid UTF-8

### LINKED ISSUE #2968: Can't read mailbox (spinner running continuously)  when foreign characters are in Sender's address
### Expected behavior
When foreign characters are in  e-mail sender's e-mails , mails are shown in the mailbox's lists.

### Actual behavior
When this particular e-mail sender's e-mails are in mail header, app hang and can not show mailbox content (spinner running all the time). Examples (bold characters): stru**è**nog@exampledomain.com, vo**ð**enje@exampledomain.com, gra**ð**.dnevnika@exampledomain.com...

error log:
`Caused by OCA\Mail\Exception\ServiceException: Sync failed for 26:INBOX: An exception occurred while executing 'INSERT INTO "oc_mail_recipients" ("message_id", "type", "label", "email") VALUES(?, ?, ?, ?)' with params [634589, 0, "\x73\x74\x72\x75\xe8\x6e\x6f\x67\x40\x69\x70\x7a\x2e\x68\x72", "\x73\x74\x72\x75\xe8\x6e\x6f\x67\x40\x69\x70\x7a\x2e\x68\x72"]: SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xe8 0x6e 0x6f`

### Mail app

**Mail app version:** 1.33

**Mailserver or service:** Postfix

### Server configuration

**Operating system**: Debian 9.12

**Web server:** Apache2 - 2.4.25

**Database:** PostgreSQL 9.6.17 on x86_64-pc-linux-gnu

**PHP version:** 7.3.17

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Google Chrome 81.x

**Operating system:** Windows 10

### PR DESCRIPTION
**Pull request by StCyr**
Fixes #2968 

Signed-off-by: Cyrille Bollu <cyr.debian@bollu.be>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Makes sense!

Just one idea from https://github.com/nextcloud/mail/issues/3908#issuecomment-762377816: what if we first try to convert without the ignore option and only if the result is `false` we do another conversation with ignore?

like

```php
$utf8 = iconv('UTF-8', 'UTF-8', $subject);
if ($utf !== false) {
  return $utf8;
}
return iconv('UTF-8', 'UTF-8//IGNORE', $subject);
```

this means that the installations where the ignore part is problematic will less likely run into issues, only if there really is invalid data.

**Comment by StCyr** [comment]
> 
> 
> Makes sense!
> 
> Just one idea from [#3908 (comment)](https://github.com/nextcloud/mail/issues/3908#issuecomment-762377816): what if we first try to convert without the ignore option and only if the result is `false` we do another conversation with ignore?
> 
> like
> 
> ```
> $utf8 = iconv('UTF-8', 'UTF-8', $subject);
> if ($utf !== false) {
>   return $utf8;
> }
> return iconv('UTF-8', 'UTF-8//IGNORE', $subject);
> ```
> 
> this means that the installations where the ignore part is problematic will less likely run into issues, only if there really is invalid data.

Ok. should I update the fix in #3855 ?

**Comment by ChristophWurst** [comment]
> Ok. should I update the fix in #3855 ?

That would be great!

**Pull request merged**
