### PR TITLE
Fix infinite scoll loading, take II

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/5234

Incorporates https://github.com/ChristophWurst/vue-infinite-scroll/pull/1

### CODE REVIEW

**Comment by ChristophWurst** [comment]
CI says no becaues npm pulls through ssh

**Review by miaulalala — APPROVED** [review]

**Comment by ChristophWurst** [comment]
https://github.com/npm/cli/issues/2610#issuecomment-851347583 looks like a promising fix :crossed_fingers:

**Comment by ChristophWurst** [comment]
Now we vendor the lib. Not great but also not terrible for this workaround :shipit:

**Review by GretaD — APPROVED** [review]
it works. On inbox view all looks good. While on PI, i need to scroll twice to make it work.

**Comment by raimund-schluessler** [comment]
> 
> 
> Now we vendor the lib. Not great but also not terrible for this workaround :shipit:

@ChristophWurst Is there something wrong with loading libs from github like so?
```
"vue-infinite-scroll": "github:ChristophWurst/vue-infinite-scroll#748261ea9411bdc2e5c7509d9638e02007c2db50",
```

I just ask, because we do it like this in the Tasks repository (see https://github.com/nextcloud/tasks/blob/master/package.json#L43), and I now wonder if this is not a good idea for some reason?

**Comment by ChristophWurst** [comment]
If CI passes then it's fine ;)

For us CI failed because of https://github.com/npm/cli/issues/2610. This was our only blocker.

**Pull request merged**
