### PR TITLE
Fix action input label size

### LINKED ISSUE #3567: Input submit button has different size
### Expected behavior
The button has the same size as input field

### Actual behavior

Screenshot from 2020-09-08 13-08-18

### PR DESCRIPTION
**Pull request by GretaD**
fixes #3567

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I've also seen this in calendar. I don't think we have ot fix this here but in nc-vue, no?

**Comment by GretaD** [comment]
> I've also seen this in calendar. I don't think we have ot fix this here but in nc-vue, no?

this it is fixed here: https://github.com/nextcloud/nextcloud-vue/commit/f9c77d73eb372fd9dfb1fc281076679e7a9936b6 actually, but it doesnt apply to mail

**Comment by ChristophWurst** [comment]
> this it is fixed here: [nextcloud/nextcloud-vue@f9c77d7](https://github.com/nextcloud/nextcloud-vue/commit/f9c77d73eb372fd9dfb1fc281076679e7a9936b6) actually, but it doesnt apply to mail

That fix is only in 2.6.5. See the linked tag on that page. We have to wait for https://github.com/nextcloud/mail/pull/3617.

**Comment by ChristophWurst** [comment]
> That fix is only in 2.6.5. See the linked tag on that page. We have to wait for #3617.

@GretaD please re-evaluate

**Comment by GretaD** [comment]
fixed

**Pull request closed without merging**
