### PR TITLE
(Re)wrap message ID in '<>' brackets before inserting in the db

### LINKED ISSUE #5597: Cannot delete some mail – Argument 3 passed to MailManager::deleteThread() must be of the type string null given
### Expected behavior

- mail is deleted

### Actual behavior

- mail is not deleted
- generic error shown
- see below for logged backtrace

### Backtrace

```json
{
  "reqId": "8c7OpTinPOgJzlxCLhU4",
  "level": 3,
  "time": "2021-09-29T10:50:50+00:00",
  "remoteAddr": "12.123.123.123",
  "user": "abcdef",
  "app": "mail",
  "method": "DELETE",
  "url": "/apps/mail/api/thread/2115997",
  "message": "Argument 3 passed to OCA\\Mail\\Service\\MailManager::deleteThread() must be of the type string, null given, called in /var/www/html/apps/mail/lib/Controller/ThreadController.php on line 118",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0",
  "version": "22.2.0.1",
  "exception": {
    "Exception": "Exception",
    "Message": "Argument 3 passed to OCA\\Mail\\Service\\MailManager::deleteThread() must be of the type string, null given, called in /var/www/html/apps/mail/lib/Controller/ThreadController.php on line 118",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 301,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1000,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/html/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 158,
    "Previous": {
      "Exception": "TypeError",
      "Message": "Argument 3 passed to OCA\\Mail\\Service\\MailManager::deleteThread() must be of the type string, null given, called in /var/www/html/apps/mail/lib/Controller/ThreadController.php on line 118",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/html/apps/mail/lib/Controller/ThreadController.php",
          "line": 118,
          "function": "deleteThread",
          "class": "OCA\\Mail\\Service\\MailManager",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 217,
          "function": "delete",
          "class": "OCA\\Mail\\Controller\\ThreadController",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 126,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/App.php",
          "line": 156,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Route/Router.php",
          "line": 301,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/var/www/html/lib/base.php",
          "line": 1000,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/var/www/html/index.php",
          "line": 36,
          "function": "handleRequest",
          "class": "OC",
          "type": "::"
        }
      ],
      "File": "/var/www/html/apps/mail/lib/Service/MailManager.php",
      "Line": 688
    },
    "CustomMessage": "Argument 3 passed to OCA\\Mail\\Service\\MailManager::deleteThread() must be of the type string, null given, called in /var/www/html/apps/mail/lib/Controller/ThreadController.php on line 118"
  }
}
```

### LINKED ISSUE #5764: Invalid Message-ID header
### Expected behavior
Create valid Message-ID header.
From syntax rules of https://datatracker.ietf.org/doc/html/rfc822
```
optional-field =
                 /  "Message-ID"        ":"   msg-id

msg-id      =  "<" addr-spec ">"            ; Unique message id

addr-spec   =  local-part "@" domain        ; global address
```
I undestand that should be something like the following example:
```
Message-ID: <20211201100841.Horde.vJATlrnmG0ZJXLLjr-iX2-Z@example.com>
```

### Actual behavior
Current Message-ID doesn't content the domain, it is like the following example: 
```
Message-ID: <20211201100841.Horde.vJATlrnmG0ZJXLLjr-iX2-Z@>
```

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** mailu.io

### Server configuration

**Operating system**: Alpine (docker image nextcloud:21.0.2-fpm-alpine)

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** PHP 7.4.20 (cli) (built: Jun  3 2021 22:19:26) ( NTS )

**Nextcloud Version:** 21.0.2

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #5597

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Fixes #5764

Isn't that ticket about new messages generated in or app? I don't think this PR fixes any of that, does it?

**Comment by miaulalala** [comment]
True, i had the wrong ticket in mind, good catch

**Review by ChristophWurst — APPROVED** [review]
Would be really really cool if we can have tests for the various cases :)

**Pull request merged**
