### PR TITLE
Fix the PI sync when the page is not force loading

### LINKED ISSUE #6125: "Other" section in the priority mailbox not displaying new incoming messages
### Steps to reproduce

1. Be on the priority mailbox tab
2. Get new email
3. Wait for other section to update (it doesn't)

### Expected behavior

The "Other" section shows the incoming message if it isn't important

### Actual behavior

The "Other" section doesn't update until a window reload or using the refresh button

### Mail app version

1.11.6

### Mailserver or service

no info

### Operating system

no info

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #6125 
and possibly this one https://github.com/nextcloud/mail/issues/3049

### CODE REVIEW

**Comment by GretaD** [comment]
backport to stable1.12/13 only?

**Comment by ChristophWurst** [comment]
Both

**Pull request merged**
