### PR TITLE
fix(deps): Apply npm audit fix

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated fix of npm audit

### CODE REVIEW

**Review by ChristophWurst — COMMENTED** [review]
Bumps nextcloud/vue, so this needs a manual test

**Comment by ChristophWurst** [comment]
@GretaD @kesselb please give this a smoke test for nextcloud-vue, and then let's get this in

**Comment by GretaD** [comment]
i have the mentionme issue. Did we backport the fixup for that. I cannot find it because i dont know how it was called.

`{"reqId":"54LSLrdYRFiYJM1HZf8Q","level":3,"time":"2024-11-26T15:09:26+00:00","remoteAddr":"::1","user":"gretad","app":"mail","method":"GET","url":"/index.php/apps/mail/api/messages?mailboxId=81&limit=20","message":"mentionsMe is not a valid attribute","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","version":"31.0.0.5","exception":{"Exception":"BadFunctionCallException","Message":"mentionsMe is not a valid attribute","Code":0,"Trace":[{"file":"/var/www/server/lib/public/AppFramework/Db/Entity.php","line":59,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/server/lib/public/AppFramework/Db/QBMapper.php","line":315,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::"},{"file":"/var/www/server/lib/public/AppFramework/Db/QBMapper.php","line":333,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/server/apps/mail/lib/Db/MessageMapper.php","line":1267,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/server/apps/mail/lib/Service/Search/MailSearch.php","line":134,"function":"findByIds","class":"OCA\\Mail\\Db\\MessageMapper","type":"->"},{"file":"/var/www/server/apps/mail/lib/Controller/MessagesController.php","line":169,"function":"findMessages","class":"OCA\\Mail\\Service\\Search\\MailSearch","type":"->"},{"file":"/var/www/server/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"index","class":"OCA\\Mail\\Controller\\MessagesController","type":"->"},{"file":"/var/www/server/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/server/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/server/lib/private/Route/Router.php","line":306,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/server/lib/base.php","line":1019,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/server/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/server/lib/public/AppFramework/Db/Entity.php","Line":95,"message":"mentionsMe is not a valid attribute","exception":{},"CustomMessage":"mentionsMe is not a valid attribute"}}`

**Comment by ChristophWurst** [comment]
did you go from main to an older checkout?

**Comment by GretaD** [comment]
> did you go from main to an older checkout?

i dont remember, but i did test the main first

**Comment by ChristophWurst** [comment]
the command bot rebased this PR two days ago. make sure you are the latest remote HEAD commit

**Review by GretaD — APPROVED** [review]
tested, looks good

**Pull request merged**
