### PR TITLE
Hide 'clear mailbox' if it doesnt have sufficient rights

### LINKED ISSUE #8071: Show/hide "Clear mailbox" depending on Acl rights
### Is your feature request related to a problem? Please describe.

As a recipient of a shared mailbox I want the app to only show me *Clear mailbox* when I'm allowed to

### Describe the solution you'd like

Hide *Clear mailbox* with ACLs set but insufficient rights.

### Describe alternatives you've considered

_No response_

### Additional context

This is part of https://github.com/nextcloud/mail/issues/7057

### PR DESCRIPTION
**Pull request by GretaD**
fixes #8071

### CODE REVIEW

**Review by ChristophWurst — DISMISSED** [review]
https://datatracker.ietf.org/doc/html/rfc4314.html#section-2.1 x vs t vs e

**Comment by ChristophWurst** [comment]
x right means you can *delete a mailbox*
t right means you can *delete a message*
e right means you can *expunge a mailbox*

our app expunges after message deletion. you need t+e for this operation.

**Review by hamza221 — APPROVED** [review]
I think in this case using  mailboxHasRights() would be better  https://github.com/nextcloud/mail/pull/8024#pullrequestreview-1302908447
than creating a new method. 
If the plan is to change all of them later it lgtm

**Comment by GretaD** [comment]
> mailboxHasRights

ohhh yes, i totally forgot about it, will amend it

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
