### PR TITLE
Handle dovecot sieve folder when subdir of INBOX

### PR DESCRIPTION
**Pull request by j0s**
Pull request #520 introduced special handling of dovecot's
'dovecot.sieve' folder, so that it isn't queried for a sync
token. A common configuration of dovecot is to put all folders as
subfolders of INBOX. This pull request adds support for
cases when the sieve folder is a subfolder of INBOX.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Hey, @j0s!

Thanks a lot for your PR. I think the proper solution would be to fix https://github.com/nextcloud/mail/issues/386 because then the prefix would be removed and thus that wouldn't be an issue, right?

**Comment by j0s** [comment]
That looks like the proper solution, yes, if the solution involves removing the INBOX prefix from all  subfolders. However the fix in https://github.com/nextcloud/mail/pull/652#issuecomment-352427619 does not solve the problem for me. Unfortunately I'm not comfortable enough with docker to create an image for you to test.

**Comment by ChristophWurst** [comment]
I'm fine with accepting this temporary fix if

* You fix the coding style and use camel case variable names and the short array syntax
* Add a source code comment that this is a ~~hack~~ erm … I mean temporary fix 😉 
* Add a notice to #386 so that we don't forge to remove this fix once that ticket has been addressed in a PR

**Comment by ChristophWurst** [comment]
Thanks a lot!

**Comment by ChristophWurst** [comment]
- [ ] blocked by #735

**Comment by ChristophWurst** [comment]
@j0s FYI your email address used for the commits here is not associated with your account. You might want to add it to your account, then GitHub will correctly show you as author 😉

**Comment by ChristophWurst** [comment]
> First-time contributor

Congrats on your first contribution btw 🙌 Looking forward to more contributions ✨ 🚀

**Pull request merged**
