### PR TITLE
Add the option to disable the new account button

### PR DESCRIPTION
**Pull request by miaulalala**
Add the option for the admins to disable the "Add Mail Account" button in the Mail frontend.

This is expecially useful if you are using an account provisioning configuration.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Best thing since cargo pants

**Review by st3iny — APPROVED** [review]
Tested and works.

Navigating to a mailbox directly won't show the new page (e. g. /apps/mail/box/priority). But that is also weird on master and we should redirect to the setup page if no accounts are configured.

**Comment by miaulalala** [comment]
Accidental close?

**Comment by st3iny** [comment]
> Accidental close?

Yeah, because my PR was merged and referenced this PR via `Fix ...`. I didn't know that it also closes PRs. I thought it only closes referenced issues.

**Review by ChristophWurst — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Pull request merged**
