### PR TITLE
feat(composer): minimize composer modal while editing a message

### PR DESCRIPTION
**Pull request by st3iny**
Fixes https://github.com/nextcloud/mail/issues/8338
Fixes https://github.com/nextcloud/mail/issues/6470

## Desktop

https://user-images.githubusercontent.com/1479486/235288432-0de7c51c-2c38-4c6f-b0e1-84644c79c1a6.mp4

## Mobile

grafik

### CODE REVIEW

**Comment by szaimen** [comment]
Maybe adding a signal color on the compose button as long as a draft is active would make sense? having a good highlight on this makes probably sense?

**Comment by st3iny** [comment]
> Maybe adding a signal color on the compose button as long as a draft is active would make sense? having a good highlight on this makes probably sense?

Indeed. I added the primary class as long as a composer session is ongoing.

**Comment by GretaD** [comment]
will this pr resolve also this issue: https://github.com/nextcloud/mail/issues/2831  ?

**Comment by st3iny** [comment]
> will this pr resolve also this issue: #2831 ?

This PR handles the part about browsing mails while editing. However, editing mail in a whole new browser window or popout is not implemented.

**Comment by ChristophWurst** [comment]
When I close/re-open repeatedly I sometimes loose the message. But I'm not able to trigger this consistently.

Minor remark: the *To* input is always focused. This is what we want for new messages, for resumed ones we can jump into the message body, I think.

**Review by jancborchardt — COMMENTED** [review]
My concern is that it’s not very obvious that the message is being saved, even with the notification and the changing of the button text.

Can we put it on the bottom right like Google Mail and Facebook do for messages? Like a floating FAB sort of – @nimishavijay also mentioned this, maybe a mockup would be good there.

Also, is this saving the message as a draft? Cause if not it’s a bit off as you can not continue on mobile or other apps if you started a mail like this.

**Comment by st3iny** [comment]
> Also, is this saving the message as a draft? Cause if not it’s a bit off as you can not continue on mobile or other apps if you started a mail like this.

Yes, the draft is saved immediately when the modal is minimized. It can be opened again on any device/client from the drafts folder.

**Comment by st3iny** [comment]
> My concern is that it’s not very obvious that the message is being saved, even with the notification and the changing of the button text.

Yeah, that is my biggest concern as well. We should definitely promote the feature in a more noticeable way. I was also thinking about adding a dedicated minimize button to the modal. Right now, it can only be minimized by "accidentally" clicking outside.

A mockup would be awesome and highly appreciated.

**Comment by ChristophWurst** [comment]
> A mockup would be awesome and highly appreciated.

Specifically one for desktop and another one for mobile or small screens in general. The floating element could overlap other content.

**Comment by nimishavijay** [comment]
> I was also thinking about adding a dedicated minimize button to the modal. Right now, it can only be minimized by "
"accidentally" clicking outside.

Totally agree! Conveniently, there is a [minimize](https://fonts.google.com/icons?selected=Material%20Icons%3Aminimize%3A) MDI icon :) 

> Specifically one for desktop and another one for mobile or small screens in general. The floating element could overlap other content.

For desktop:
image
image

- [ ] It would be a button on the bottom right of the screen, with an edit icon and text on the left, and an expand button and a close button on the right. in this mockup it's 384px but that is fairly arbitrary. 256px and 300px seem too narrow.
- [ ] The close button gets rid of the floating button 
- [ ] clicking anywhere else would open up the modal
- [ ] The expand button also opens the modal, it's more just visual reassurance that the composer will be maximised. without the expand button it looks like a notification toast that should be dismissed. 
- [ ] If the subject is too long it should be ellipsised
- One possible concern is that the expand and close are very close to each other which may cause misclicks, but since the draft can be accessed from the navigation also I think it's okay. What do you think? also @jancborchardt 


For mobile, I checked Gmail, Outlook, Protonmail and Apple mail and none of them have this. There is a notification that says "Draft saved" and no way to open up the message without going to the drafts folder. However, I do think this feature would be pretty useful. If it is taking too much vertical space it can be easily dismissed with the close button. 

- [ ] It could be full width on mobile or very small screens, and take up a maximum of 30% of the screen for other small screens like tablets.


<p float="left">
  
   
</p>

**Comment by ChristophWurst** [comment]
Clicking *New message* when there is already one in minimized state replaces minimized version, right?

**Comment by ChristophWurst** [comment]
We are technically limited here and the software architecture only allows one new message at a time. We can't leave *Company dinner* minimized and show the new message modal. Our options are

* Disable the *New message* button when there is a minimized message
* Allow clicks on *New message* but save any previous message as draft and remove it from the minimized state

**Comment by st3iny** [comment]
This PR is now ready to review. I also updated the screen recording and added a mobile screenshot to the description.

**Review by jancborchardt — COMMENTED** [review]
Nice! Ideal would be to have a little animation on closing which moves/minimizes the modal towards the bottom right so it's more obvious where the overlay is – but I assume that is out of scope for now?

@st3iny to confirm, when you press the "x" on the bottom right element, the draft stays saved, correct?

**Comment by st3iny** [comment]
> @st3iny to confirm, when you press the "x" on the bottom right element, the draft stays saved, correct?

Yes. If the draft can't be saved for some reason, the indicator will stay (and there will be a toast indicating the error).

---

> Nice! Ideal would be to have a little animation on closing which moves/minimizes the modal towards the bottom right so it's more obvious where the overlay is – but I assume that is out of scope for now?

That is a good idea but as you said it is out of scope. We should prioritize getting the MVP for this feature done and schedule the animation as a followup. Currently, I'm not sure if this is easy to do and we would need to do some investigation on this (as the modal is a shared component in nc-vue).

**Comment by kesselb** [comment]
- [ ] Request a read receipt is not saved

**Comment by kesselb** [comment]
- [ ] The composer modal is closed automatically

[Screencast from 2023-05-02 11-53-36.webm](https://user-images.githubusercontent.com/3902676/235637551-1ef6934b-516b-424e-8011-4e9be80e0f89.webm)

1. New message
2. Enter email, subject and body
3. Press X to close
4. Open message again
5. Continue to write the message
6. The composer closes suddenly

**Comment by st3iny** [comment]
> * [ ]  The composer modal is closed automatically
> 
> 
> Screencast.from.2023-05-02.11-53-36.webm
> 
>     1. New message
> 
>     2. Enter email, subject and body
> 
>     3. Press X to close
> 
>     4. Open message again
> 
>     5. Continue to write the message
> 
>     6. The composer closes suddenly

Nice catch! The indicator should be disabled (not clickable) when it was deliberately closed to prevent this. The indicator can't be hidden right away in case of errors during saving. I'll fix it.

**Review by kesselb — APPROVED** [review]

**Pull request merged**
