### PR TITLE
Allow HTML signatures

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/1659 #2148

### CODE REVIEW

**Comment by edosmedia** [comment]
Hello I love nextcloud but I cannot implement a signature in html when it could be possible, since this gives a lot of precency to the world

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/issues/4707.

**Comment by igorneumann** [comment]
Well, went here to ask for HTML siignatures but I see there are plenty of requests forr the same, too... AWESOME! :-)

Also #5356, #4557 and #2733 so, Ill just leave my "+1 also need this feature".

**Comment by BrodyStone21** [comment]
I wanted to check in on this to see if it's something that has been added?

**Comment by kamilkobak** [comment]
I am also very interested in the possibility of embedding images in a signature

**Comment by GretaD** [comment]
> Reference

If you want to follow the discussion related to your request, is here: https://github.com/nextcloud/mail/issues/2733, in case you want to be updated :)

**Comment by benfavre** [comment]
Can we have HTML signatures plz ?

**Comment by sturlan** [comment]
@ChristophWurst Hi,
I see the status merged, but can't get the html signature working

**Pull request merged**
