### PR TITLE
let urllinker handle html escaping for plain text mails instead of doing it beforehand

### PR DESCRIPTION
**Pull request by icewind1991**
Currently links inside plain text mails containing `&` breaks because it get's escaped into `&amp;` before running the url linker.

The url linker's escape option handles this use case correctly.

As an example, see the spreed invite mail

### CODE REVIEW

**Comment by ChristophWurst** [comment]
There's a ticket for this bug. Will try to find and link it.

Thanks a lot!

**Comment by ChristophWurst** [comment]
Tests have to be updated to this change

```
There was 1 failure:
1) OCA\Mail\Tests\Service\HtmlTest::testLinkDetection with data set #1 ('&lt;&gt;', '&lt;&gt;')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-&lt;&gt;
+&amp;lt;&amp;gt;
/home/travis/build/nextcloud/core/apps/mail/tests/Service/HtmlTest.php:41
FAILURES!
Tests: 365, Assertions: 829, Failures: 1.
```

While at it, could you possibly add a test (if none exists) that covers the issue your PR fixes? That would be awesome.

**Comment by icewind1991** [comment]
done

**Comment by ChristophWurst** [comment]
@icewind1991 does this fix https://github.com/nextcloud/mail/issues/147

**Comment by FlorianFranzen** [comment]
@icewind1991 Thank you for your work!

**Pull request merged**
