### PR TITLE
I'm stepping back from active development

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by Gomez** [comment]
Thanks for the inital development and support! Hope you stay as user! 

Someone else should press merge :)

**Comment by MariusBluem** [comment]
**The PR** LGTM 😁

**Comment by jancborchardt** [comment]
:cry: it’s a bummer. Working on this with you was so much fun.

**Comment by ChristophWurst** [comment]
😢

**Comment by Gomez** [comment]
FYI: You cant step from hosting release barbecue parties :)

**Comment by MariusBluem** [comment]
Thank you for all your work over here 😉

**Pull request merged**
