### PR TITLE
Add local outbox

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/5884

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Let's give this a final test

**Comment by ChristophWurst** [comment]
- [ ] BUG drafts sometimes raise an error https://github.com/nextcloud/mail/pull/6198

**Comment by ChristophWurst** [comment]
- [ ] BUG: Alias ID is silently dropped https://github.com/nextcloud/mail/pull/6202

**Comment by ChristophWurst** [comment]
- [ ] BUG: forcing a send error shows success https://github.com/nextcloud/mail/pull/6203

**Comment by ChristophWurst** [comment]
- [ ] BUG: resending a message duplicates it https://github.com/nextcloud/mail/pull/6204

**Comment by ChristophWurst** [comment]
- [ ] BUG: outbox messages have no recipients https://github.com/nextcloud/mail/pull/6207

**Comment by ChristophWurst** [comment]
- [ ] BUG: *Send now* show success toast even for failures https://github.com/nextcloud/mail/pull/6209

**Review by JuliaKirschenheuter — APPROVED** [review]

**Pull request merged**
