### PR TITLE
Ignore already known UIDs when looking for new ones to satisfy mail_msg_mb_uid_idx

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes issues like https://github.com/nextcloud/mail/issues/5108, https://github.com/nextcloud/mail/issues/5019 and https://github.com/nextcloud/mail/issues/4341

Basically if one sync attempt fails mid way after it had already inserted messages of one chunk (our level of atomicity for transacted and rolled back inserts) then the next sync will fail until the eternity. This patch discards duplicates when we determine new UIDs. Therefore the duplicates are avoided.

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
Code looks good. How could I test this?

**Comment by ChristophWurst** [comment]
> Code looks good. How could I test this?

Throw an arbitrary exception after https://github.com/nextcloud/mail/blob/06edd02616adde377ea2488a8395ff4d8acdc9c4/lib/Db/MessageMapper.php#L347. Then send a message to your inbox and sync again. Your error will show up, but the new message is stored in the DB. Then remove the exception and try again. On master you are in an unrecoverable state. On this branch the code will be able to continue.

**Comment by ChristophWurst** [comment]
FYI deplyed this on my personal instance that was stuck before and it revived my inbox from the dead :raised_hands:

**Review by miaulalala — APPROVED** [review]
LGTM

**Comment by ramezrafla** [comment]
@ChristophWurst 
Thanks so much for this change - a mailbox that was locked also is released now and functional.
Well done!

**Pull request merged**
