### PR TITLE
Release 0.7.1

### PR DESCRIPTION
**Pull request by ChristophWurst**
Package for testing:
~~[mail.tar.gz](https://github.com/nextcloud/mail/files/1259858/mail.tar.gz)~~
[mail.tar.gz](https://github.com/nextcloud/mail/files/1259866/mail.tar.gz)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
🛑 there's a little issue with jquery.autosize and packaging.

**Comment by ChristophWurst** [comment]
> 🛑 there's a little issue with jquery.autosize and packaging.

Fixed in #478

**Comment by ChristophWurst** [comment]
A new package with latest master [mail.tar.gz](https://github.com/nextcloud/mail/files/1260677/mail.tar.gz)

**Comment by ChristophWurst** [comment]
> A new package with latest master mail.tar.gz

@nextcloud/mail @plastikschnitzer please give it a quick test run, then I'll push it to the app store :)

**Comment by skjnldsv** [comment]
> Refused to execute script from 'https://ncdev/apps/mail/node_modules/autosize/build/jquery.autosize.js?v=06aa48d9ff372fa06d95dc808e6e6fb8-16' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
> 15:52:04.470 

Just this library loading error. Everything works fine nonetheless.  :)

**Comment by plastikschnitzer** [comment]
Yes, I confirm its working in nextcloud 12.0.2

In owncloud 10.0.2 its causing a general php error if you call the plugin.

**Comment by ChristophWurst** [comment]
> Just this library loading error. Everything works fine nonetheless. :)

Must be that either the branch was not a 100% up to date or I packaged an outdated version. However, this was fixed by #478 :) Thanks a lot :)

> Yes, I confirm its working in nextcloud 12.0.2

Awesome, thanks for testing :)

> In owncloud 10.0.2 its causing a general php error if you call the plugin.

Yeah, that is expected. Some functionality is only provided by the Nextcloud server and hence it fails hard on Owncloud.

**Pull request merged**
