### PR TITLE
Add liniting config

### LINKED ISSUE #1293: Code formatting issues
### Question

I'm creating a feature from the `refactor/vue` branch, but I'm being bombarded with formatting errors from `eslint` and `prettier`. Should I format the files that I edit, or leave them be?

### PR DESCRIPTION
**Pull request by ChristophWurst**
Supersedes https://github.com/nextcloud/mail/pull/1405 (without all the linting fixes at once, those will follow shortly)

Fixes #1293

All credit still goes to @sahalsaad of course :) I just couldn't solve the rebasing issues in #1405. @sahalsaad is there anything missing?

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> All credit still goes to @sahalsaad of course :) I just couldn't solve the rebasing issues in #1405. @sahalsaad is there anything missing?

@sahalsaad :ping_pong:

**Comment by sahalsaad** [comment]
Looks good. You run the linting in the pipeline. right?

**Comment by ChristophWurst** [comment]
what pipleline?

**Comment by sahalsaad** [comment]
> what pipleline?

Sorry, I mean your build.

**Comment by ChristophWurst** [comment]
not yet. I'm in the process of applying all the autofix changes in a few PRs, separated by directory

**Pull request merged**
