### PR TITLE
chore: welcome back webpack

### PR DESCRIPTION
**Pull request by hamza221**
Reverts https://github.com/nextcloud/mail/pull/9757
Reverts https://github.com/nextcloud/mail/pull/10403
Reverts https://github.com/nextcloud/mail/pull/10341

Closes https://github.com/nextcloud/mail/issues/10427
Closes https://github.com/nextcloud/mail/issues/10428

### CODE REVIEW

**Comment by hamza221** [comment]
I'll squash and sign once approved

**Comment by ChristophWurst** [comment]
I've set a PR description to make the objective of this change clear.

@GretaD you should be able to use the file picker again on this branch

**Comment by kesselb** [comment]
> > ## Footnotes
> > ```
> > 1. We have german informal (de) and german formal (de-DE). The translation only works when using the informal version. The problem seems to exist on stable3.7 too, will log a new issue... [↩](#user-content-fnref-1-660815b2e3d298086ed630f059106c17)
> > ```
> 
> maybe it's not available at the CKEditor side ? https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/ui-language.html#list-of-available-professional-translations

Here's the issue: https://github.com/nextcloud/mail/issues/10488

**Comment by kesselb** [comment]
Thanks for your quick fix :+1: 

Seems to work with your latest commit :pray:

**Review by kesselb — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
I have reviewed all 24812 changed lines. Looks good

**Pull request merged**
