### PR TITLE
refactor and test desktop notifications

### PR DESCRIPTION
**Pull request by ChristophWurst**
* notifications are now triggered by events
* added some simple tests

This is a preparation for the *do not ask for notification permissions before at least one account has been set up* enhancement. cc @jancborchardt 

@nextcloud/mail review please

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Decreasing code coverage by adding new tests, yay

**Comment by ChristophWurst** [comment]
@nextcloud/mail please review. This just moves some code around and adds test. Nothing should break™️  😉

**Comment by Gomez** [comment]
Nice test! :+1:

**Comment by ChristophWurst** [comment]
\o/ thanks!

**Pull request merged**
