### PR TITLE
Fix potentially duplicate keys in navigation by scoping the key

### PR DESCRIPTION
**Pull request by brueckner**
Fixes:

Mail_-_Nextcloud

Signed-off-by: Johannes Brückner <johannes@dotplex.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Excellent

**Comment by ChristophWurst** [comment]
Could you rebase this and your other PR to master so we can hopefully get CI checks as per https://github.com/nextcloud/mail/pull/3957? :)

**Comment by ChristophWurst** [comment]
Good to see CI is running now :)

One little thing: in Nextcloud we tend to prefer clean commit histories before merging a PR. Could you rebase and squash your commits so only the one with the actual changes remains?

Sorry for being so nitpicky. I guess we should document this flow somewhere …

**Comment by brueckner** [comment]
> Sorry for being so nitpicky. I guess we should document this flow somewhere …

Don't worry about it :) It's important to keep things in order.

**Pull request merged**
