### PR TITLE
Use ES6 promise in accountservice

### PR DESCRIPTION
**Pull request by ChristophWurst**
Let's use the ES6 standardized promises instead of jQuery's. I'll create small, reviewable PRs so that we catch possible regressions 🚀 🤖 🕺

### CODE REVIEW

**Comment by ChristophWurst** [comment]
It's easier to review with https://github.com/nextcloud/mail/pull/270/files?w=1

**Comment by jancborchardt** [comment]
@nickvergessen @skjnldsv can you review this? :)

**Comment by skjnldsv** [comment]
Oups sorry! Didn't saw that one! 🙈 
I have issue with the inbox number not being updated when I delete some mails before they are fully loaded and when removing a message, the message stays on the right panel.

I don't think this is related to this however :)

**Comment by nickvergessen** [comment]
@jancborchardt asking me for a js review is like asking you for a php review ;)

**Comment by jancborchardt** [comment]
@nickvergessen :D I only @-mentioned you because Christoph apparently set @skjnldsv and you as reviewers. ;)

**Comment by skjnldsv** [comment]
Mwahaha! 👿 @jancborchardt

**Comment by nickvergessen** [comment]
> And just doing that doesn’t notify those people.

It does, I have more then 30 mails with:

**Comment by jancborchardt** [comment]
Ahh, good to know! :)

**Comment by nickvergessen** [comment]
Assigning also sends an email these days

**Pull request merged**
