### PR TITLE
Remove traling space characters from text strings

### PR DESCRIPTION
**Pull request by StCyr**
Fixes https://github.com/nextcloud/mail/issues/3873

And adds some translations

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Please revert `l10n/en_GB.js`

**Comment by StCyr** [comment]
Another PR?

**Comment by ChristophWurst** [comment]
no, we don't update any of the l10n files ourselves, this is done by the nextcloud bot :)

**Comment by StCyr** [comment]
ah sorry 😞

**Comment by ChristophWurst** [comment]
no worries :)

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
