### PR TITLE
Fine-tune padding of composer elements

### PR DESCRIPTION
**Pull request by ChristophWurst**
| Before | After |
|---|---|
| Bildschirmfoto vom 2022-09-08 18-38-12 | Bildschirmfoto vom 2022-09-08 18-37-22 |
| Bildschirmfoto vom 2022-09-08 18-38-21 | Bildschirmfoto vom 2022-09-08 18-37-31 |
| Bildschirmfoto vom 2022-09-08 18-38-31 | Bildschirmfoto vom 2022-09-08 18-37-50 |

There is still a bit of room for improvements. Consider this the first step.

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by GretaD — APPROVED** [review]
code looks good

**Comment by sazanof** [comment]
Hello! I updated my branch from main and ~see this~ not see subject.

image

Is this a bug, or feature?

image

_If I disturbed you in vain, I apologize_

**Comment by ChristophWurst** [comment]
It's right there, isn't it? What do you expect to see in addition?

**Comment by sazanof** [comment]
I thought that the subject and fields "from" "to" should have the same font size

**Comment by ChristophWurst** [comment]
Very well possible but that didn't change with this PR :)

**Pull request merged**
