### PR TITLE
Fix resumed draft to/cc/bcc values

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/mail/issues/481

I've found another (apparently yet undiscovered *bug*): bcc values are not saved for drafts. Digging into the code showed that horde does not store bcc values. They are just temporary values, used to send the email also to those recipients. Which makes sense. Kind of. This needs more investigation. Here, I focused on the to/cc stuff mainly, which now works.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> When the »to« is a person with name, like "Name Lastname" name@lastname.com, only the "Name Lastname" part gets saved.

Fixed. Please re-test.

**Comment by ChristophWurst** [comment]
@jancborchardt just told me it works and he takes full responsibility if something breaks.

**Comment by ChristophWurst** [comment]
Good to merge then, right?

**Comment by jancborchardt** [comment]
Nope :D

**Comment by jancborchardt** [comment]
screenshot from 2017-09-22 16-46-10

**Pull request merged**
