### PR TITLE
l10n: Change of letters

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
It seems very inconsistent, sometimes they use all upper case, then mixed case :shrug: 

https://en.wikipedia.org/wiki/ZIP_(file_format)#Standardization

**Comment by Valdnet** [comment]
What we do? Do we change or leave it as it is? The name `Zip` is used throughout the NC translation. In my opinion, it must be regulated in some way.

**Comment by ChristophWurst** [comment]
:+1: for consistency

**Review by ChristophWurst — APPROVED** [review]

**Comment by Valdnet** [comment]
@ChristophWurst I'd like a merge, please 😉.

**Comment by Valdnet** [comment]
@ChristophWurst Why was the PR closed if you accepted the changes?

**Comment by ChristophWurst** [comment]
Wrong button, sorry

**Pull request merged**
