### PR TITLE
Open email in a new tab

### PR DESCRIPTION
**Pull request by GretaD**
ref #2830 
@jancborchardt what icon we should use for this?

### CODE REVIEW

**Comment by jancborchardt** [comment]
I would say we do not need this action at all, it’s not really essential and we should really beware of putting lots of actions in the menu. I also haven’t seen an issue report about that – does it solve a specific problem that people encounter?

Also cc @ChristophWurst?

**Comment by GretaD** [comment]
> I would say we do not need this action at all, it’s not really essential and we should really beware of putting lots of actions in the menu. I also haven’t seen an issue report about that – does it solve a specific problem that people encounter?
> 
> Also cc @ChristophWurst?

Yes, it is requested this and also for the composer to be able to open it in a new window. #2830

**Comment by jancborchardt** [comment]
> Yes, it is requested this and also for the composer to be able to open it in a new window(on forum, and i open the ticket here). #2830

Even after searching I can not find the forum post, do you have a link?

**Comment by ChristophWurst** [comment]
https://help.nextcloud.com/t/message-display-window-and-rendering/75444/3

**Comment by GretaD** [comment]
> > Yes, it is requested this and also for the composer to be able to open it in a new window(on forum, and i open the ticket here). #2830
> 
> Even after searching I can not find the forum post, do you have a link?

CHristoph suggested to open a ticket for all those that didnt exist: https://help.nextcloud.com/t/message-display-window-and-rendering/75444/3, i did, and start working on some

**Comment by jancborchardt** [comment]
@GretaD ah, thanks! :) Many of the points in there are valid, and some of them are nicely enough already in the works – but this one I’d say no to.

We already have a bunch of long standing design issues open and we should possibly focus on those before we get new ones in where we don’t yet know if we actually want to have it. :) https://github.com/nextcloud/mail/issues?q=is%3Aopen+is%3Aissue+label%3Adesign

**Comment by jancborchardt** [comment]
Closing this as discussed and we won’t introduce this action for now.

**Pull request closed without merging**
