### PR TITLE
Fix scrolling regressions for long threads

### LINKED ISSUE #7674: Content extends message element
### Steps to reproduce

1. Open the app
2. Configure an account
3. Open a somewhat longer HTML message

### Expected behavior

Well designed app

### Actual behavior

Bildschirmfoto vom 2022-11-24 15-23-43

Bildschirmfoto vom 2022-11-24 15-23-56

### Mail app version

2.2

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

Git bisect leads me to e86cc894aa3cfa8e1cbbb6451fe87e7e90f86c99.

### PR DESCRIPTION
**Pull request by GretaD**
[Screencast from 24.11.2022 17:13:28.webm](https://user-images.githubusercontent.com/12728974/203829027-ba5da01a-6c45-426b-b584-769960ced2f7.webm)

fixes #7674

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Smooth

**Comment by ChristophWurst** [comment]
Backports?

**Comment by GretaD** [comment]
i am not sure about the 1.14 because the initial regression was not backported there, but will check

**Pull request merged**
