### PR TITLE
correctly filter FTP links in mails

### PR DESCRIPTION
**Pull request by ChristophWurst**
* detect FTP urls, so that the proxy controller is used to prevent leaking the request token
* block images served via FTP

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@LukasReschke review please :-)

**Comment by irgendwie** [comment]
- :+1: blocks images from ftp servers
- when unblocking, it seems to correctly use the proxy:
http://localhost:9000/index.php/apps/mail/proxy?src=ftp%3A%2F%2F{url}&requesttoken={token}
- Can't test any further: "Message: cURL error 1: Protocol "ftp" not supported or disabled in libcurl" ;-)

**Comment by ChristophWurst** [comment]
> Can't test any further: "Message: cURL error 1: Protocol "ftp" not supported or disabled in libcurl" ;-)

Where did that pop up?

> Edit: Should it detect sftp too?

Nope, sftp should be blocked generally.

**Comment by irgendwie** [comment]
> Where did that pop up?

Image can't be loaded **in my setup?**, this happens when I copy the image link (the proxy url) and directly try to open it in the browser
=> Unrelated I suppose

**Comment by ChristophWurst** [comment]
For security reasons it's important to block ftp resources by default. But please open an issue so we can addresss that error in the proxy controller too. Thanks :-)

**Pull request merged**
