### PR TITLE
Update php deps

### PR DESCRIPTION
**Pull request by ChristophWurst**
Only minor updates and patches (if those projects comply semver), so nothing should break™️

### CODE REVIEW

**Comment by jancborchardt** [comment]
This is not related to this PR, but I’m getting this composer issue:
```
jan@Rechenknecht:~/nextcloud/apps/mail$ make install-composer-deps 
php composer.phar install
PHP Fatal error:  Uncaught PharException: manifest cannot be larger than 100 MB in phar "/home/jan/nextcloud/apps/mail/composer.phar" in /home/jan/nextcloud/apps/mail/composer.phar:23
Stack trace:
#0 /home/jan/nextcloud/apps/mail/composer.phar(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /home/jan/nextcloud/apps/mail/composer.phar on line 23
Makefile:27 : la recette pour la cible « install-composer-deps » a échouée
make: *** [install-composer-deps] Erreur 255
```

**Comment by jancborchardt** [comment]
Also works :) :+1:

**Comment by ChristophWurst** [comment]
@jancborchardt please do not merge PRs with failing CI runs: https://travis-ci.org/nextcloud/mail/builds/186428264 💥 💥 💥

**Comment by ChristophWurst** [comment]
Revert in https://github.com/nextcloud/mail/pull/265, please review

**Comment by ChristophWurst** [comment]
Rule of thumb: "2. developing" means the PR is *not* ready to be reviewed or merged 😜

**Comment by jancborchardt** [comment]
Dayum, sorry. From the text it sounded like it’s ready :)

**Pull request merged**
