### PR TITLE
Use eslint config

### PR DESCRIPTION
**Pull request by skjnldsv**
Still some errors left.
I separated the commits so it's easier to drop the fix one and re do it again.
I guess we should wait after your upcoming release?

Btw, you're still supporting 7.1?
I see it running on your tests :thinking:

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Btw, you're still supporting 7.1?

Yes, for stable17.

> I guess we should wait after your upcoming release?

Yeah, this will cause conflicts with the open PRs I'm afraid

**Comment by skjnldsv** [comment]
> Yeah, this will cause conflicts with the open PRs I'm afraid

Let's wait, this is not urgent :)

**Comment by ChristophWurst** [comment]
Time to get this in now that we finished a new release. I'll have to go through the linter errors to fix them.

**Comment by skjnldsv** [comment]
Rebased! Still needs some fixes here and there than lint:fix couldn't do automatically @ChristophWurst 
Let's do this as soon as you get back so it's not a nightmare to rebase again :see_no_evil:

**Comment by skjnldsv** [comment]
Merging, I took your rebase as a yes.
All tests were green, blame me when you get back if it created anything bad :stuck_out_tongue_closed_eyes:

**Pull request merged**
