### PR TITLE
Fix composer margin on rich text

### PR DESCRIPTION
**Pull request by hamza221**
Steps to reproduce: 

1. Open composer
2. start typing an email 
3. Enable/disable formatting 

Main: text jumps up/down as formatting is enabled/disabled
Here: text stays consistent

### CODE REVIEW

**Comment by ChristophWurst** [comment]
to review or not to review? :D  

labels say yes, PR state says no

**Comment by hamza221** [comment]
Haha, sorr I just had to make a quick fixup

> to review or not to review? :D
> 
> labels say yes, PR state says no

**Review by ChristophWurst — APPROVED** [review]
Tested & works

**Comment by ChristophWurst** [comment]
@GretaD please take care of any backports

**Comment by GretaD** [comment]
> @GretaD please take care of any backports

yes, @hamza221 please squash your commints

**Pull request merged**
